package com.notificationservice.infrastructure.rabbitmq;import org.springframework.amqp.core.*;import org.springframework.amqp.support.converter.JacksonJsonMessageConverter;import org.springframework.beans.factory.annotation.Value;import org.springframework.context.annotation.*;
@Configuration public class RabbitConfiguration{
 public static final String QUEUE="notification.events.queue",RETRY_QUEUE="notification.events.retry.queue",DLQ="notification.events.dlq",RETRY_EX="notification.retry.exchange",DLX="notification.dlx";
 @Bean TopicExchange authExchange(){return new TopicExchange("auth.exchange",true,false);}@Bean TopicExchange userExchange(){return new TopicExchange("user.exchange",true,false);}@Bean TopicExchange questionExchange(){return new TopicExchange("question.exchange",true,false);}@Bean TopicExchange aiExchange(){return new TopicExchange("ai.exchange",true,false);}@Bean TopicExchange examExchange(){return new TopicExchange("exam.exchange",true,false);}@Bean DirectExchange retryExchange(){return new DirectExchange(RETRY_EX,true,false);}@Bean DirectExchange dlx(){return new DirectExchange(DLX,true,false);}
 @Bean Queue eventQueue(){return QueueBuilder.durable(QUEUE).deadLetterExchange(RETRY_EX).deadLetterRoutingKey("retry").build();}@Bean Queue retryQueue(@Value("${notification.retry-delay-ms}")int ttl){return QueueBuilder.durable(RETRY_QUEUE).ttl(ttl).deadLetterExchange("").deadLetterRoutingKey(QUEUE).build();}@Bean Queue dlq(){return QueueBuilder.durable(DLQ).build();}
 @Bean Binding retryBinding(DirectExchange retryExchange){return BindingBuilder.bind(retryQueue(5000)).to(retryExchange).with("retry");}@Bean Binding dlqBinding(DirectExchange dlx){return BindingBuilder.bind(dlq()).to(dlx).with("dead");}
 @Bean Declarables eventBindings(){Queue q=eventQueue();return new Declarables(BindingBuilder.bind(q).to(authExchange()).with("password.reset.otp.requested"),BindingBuilder.bind(q).to(userExchange()).with("user.approved"),BindingBuilder.bind(q).to(userExchange()).with("user.rejected"),BindingBuilder.bind(q).to(questionExchange()).with("question.submitted"),BindingBuilder.bind(q).to(questionExchange()).with("question.approved"),BindingBuilder.bind(q).to(questionExchange()).with("question.rejected"),BindingBuilder.bind(q).to(questionExchange()).with("question.revision.requested"),BindingBuilder.bind(q).to(aiExchange()).with("ai.generation.completed"),BindingBuilder.bind(q).to(aiExchange()).with("ai.generation.failed"),BindingBuilder.bind(q).to(examExchange()).with("exam.generated"));}
 @Bean JacksonJsonMessageConverter converter(){return new JacksonJsonMessageConverter();}
}
