package com.hau.notification.domain.model;
import com.hau.notification.domain.exception.InvalidNotificationException;import java.time.Instant;import java.util.*;
public final class Notification {
 private final UUID id,userId;private final NotificationType type;private final String title,content,referenceId,referenceType;private final boolean read;private final Instant readAt,createdAt;
 public Notification(UUID id,UUID userId,NotificationType type,String title,String content,String referenceId,String referenceType,boolean read,Instant readAt,Instant createdAt){this.id=Objects.requireNonNull(id);this.userId=Objects.requireNonNull(userId);this.type=Objects.requireNonNull(type);this.title=req(title,200);this.content=req(content,2000);this.referenceId=opt(referenceId,100);this.referenceType=opt(referenceType,64);if(!read&&readAt!=null)throw new InvalidNotificationException("Unread notification cannot have readAt");this.read=read;this.readAt=readAt;this.createdAt=Objects.requireNonNull(createdAt);}
 public static Notification unread(UUID userId,NotificationType type,String title,String content,String referenceId,String referenceType,Instant at){return new Notification(UUID.randomUUID(),userId,type,title,content,referenceId,referenceType,false,null,at);}
 public Notification markRead(Instant at){return read?this:new Notification(id,userId,type,title,content,referenceId,referenceType,true,Objects.requireNonNull(at),createdAt);}
 private static String req(String v,int m){if(v==null||v.isBlank()||v.trim().length()>m)throw new InvalidNotificationException("Invalid notification text");return v.trim();}private static String opt(String v,int m){if(v==null||v.isBlank())return null;if(v.trim().length()>m)throw new InvalidNotificationException("Notification metadata is too long");return v.trim();}
 public UUID getId(){return id;}public UUID getUserId(){return userId;}public NotificationType getType(){return type;}public String getTitle(){return title;}public String getContent(){return content;}public String getReferenceId(){return referenceId;}public String getReferenceType(){return referenceType;}public boolean isRead(){return read;}public Instant getReadAt(){return readAt;}public Instant getCreatedAt(){return createdAt;}
}
