spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

auth:
  jwt:
    private-key-base64: ${JWT_PRIVATE_KEY_BASE64}
    public-key-base64: ${JWT_PUBLIC_KEY_BASE64}
    generate-ephemeral-key: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
