import {useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import {Button,Input,Select} from '../../../components/ui'
import {DocumentPicker} from '../components/DocumentPicker'
import {AiError,AiJobPanel} from '../components/AiShared'
import {aiApi} from '../api/aiApi'
import {generationPayload} from '../model/aiModel'
export function GeneratePage({analysis=false}){
 const [form,setForm]=useState({documentId:'',count:10,difficulty:'',topicId:'',analysisType:'',language:localStorage.getItem('hau-ai-language')||'VI',includeImages:false});const[busy,setBusy]=useState(false);const[error,setError]=useState(null);const[job,setJob]=useState(null);const lock=useRef(false);const field=(name,value)=>{setForm(p=>({...p,[name]:value}));if(name==='language')localStorage.setItem('hau-ai-language',value)}
 async function submit(event){event.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{const body=analysis?{documentId:form.documentId,analysisType:form.analysisType.trim()}:generationPayload(form);setJob(await(analysis?aiApi.analyze(body):aiApi.generate(body)))}catch(reason){setError(reason)}finally{lock.current=false;setBusy(false)}}
 return <div className="ai-stack"><form className="editor-section" onSubmit={submit}><h2>{analysis?'Phân tích tài liệu':'Tạo câu hỏi bằng AI'}</h2><fieldset disabled={busy||Boolean(job)} className="ai-form"><DocumentPicker value={form.documentId} onChange={value=>field('documentId',value)} disabled={busy||Boolean(job)}/>{analysis?<Input label="Yêu cầu phân tích" required value={form.analysisType} onChange={e=>field('analysisType',e.target.value)}/>:<><Input label="Số lượng câu hỏi (1–100)" type="number" required min={1} max={100} value={form.count} onChange={e=>field('count',e.target.value)}/><Select label="Độ khó" value={form.difficulty} options={[{value:'',label:'AI đề xuất'},{value:'EASY',label:'Dễ'},{value:'MEDIUM',label:'Trung bình'},{value:'HARD',label:'Khó'}]} onChange={e=>field('difficulty',e.target.value)}/><Input label="Topic ID (không bắt buộc)" value={form.topicId} onChange={e=>field('topicId',e.target.value.trim())}/><Select label="Ngôn ngữ câu hỏi *" value={form.language} options={[{value:'VI',label:'Tiếng Việt'},{value:'EN',label:'English'}]} onChange={e=>field('language',e.target.value)}/><label className="field"><span>Ảnh minh họa</span><span><input type="checkbox" checked={form.includeImages} onChange={e=>field('includeImages',e.target.checked)}/> Chỉ tạo khi câu hỏi phù hợp</span></label></>}<Button type="submit" loading={busy} disabled={busy||!form.documentId||(analysis&&!form.analysisType.trim())||Boolean(job)}>{analysis?'Bắt đầu phân tích':'Tạo câu hỏi bằng AI'}</Button></fieldset>{error&&<AiError error={error}/>}</form>{job&&<><div className="ai-inline"><p role="status">Đã tiếp nhận tác vụ · {job.status}</p><Link to={`/ai/jobs/${job.jobId}`}>Mở chi tiết tác vụ</Link><Button variant="secondary" onClick={()=>setJob(null)}>Tạo yêu cầu mới</Button></div><AiJobPanel key={job.jobId} id={job.jobId}/></>}</div>
}
