ALTER TABLE ai_jobs DROP CONSTRAINT IF EXISTS ck_job_status;
ALTER TABLE ai_jobs ADD CONSTRAINT ck_job_status
    CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED','CANCELLED','RETRIED'));
