ALTER TABLE ai_settings ADD COLUMN last_checked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE ai_settings ADD COLUMN last_error_code VARCHAR(100);
ALTER TABLE ai_settings ADD COLUMN runtime_status VARCHAR(40) NOT NULL DEFAULT 'CONFIGURED_BUT_UNVERIFIED';
