server:
  port: ${SERVER_PORT:8086}
spring:
  application:
    name: notification-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener.simple:
      acknowledge-mode: manual
      default-requeue-rejected: false
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
  security.oauth2.resourceserver.jwt.jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}
notification:
  mail-from: ${SMTP_FROM:no-reply@hau.edu.vn}
  retry-delay-ms: ${NOTIFICATION_RETRY_DELAY_MS:5000}
  scheduler-delay-ms: ${NOTIFICATION_SCHEDULER_DELAY_MS:5000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

