package com.hau.notification.application.service;
import com.hau.notification.application.dto.IncomingEvent;import com.hau.notification.application.port.in.EventNotificationUseCase;import com.hau.notification.application.port.out.*;import com.hau.notification.domain.model.*;import com.hau.notification.domain.repository.NotificationRepository;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class EventNotificationService implements EventNotificationUseCase{
 private final NotificationRepository notifications;private final ProcessedEventStore inbox;private final RealtimeNotifier realtime;private final EmailSender email;private final Clock clock;
 public EventNotificationService(NotificationRepository n,ProcessedEventStore i,RealtimeNotifier r,EmailSender e,Clock c){notifications=n;inbox=i;realtime=r;email=e;clock=c;}
 @Transactional public boolean handle(IncomingEvent e){if(inbox.exists(e.eventId()))return false;NotificationType type=type(e.eventType());Map<String,Object> p=e.payload()==null?Map.of():e.payload();
  if(type==NotificationType.PASSWORD_RESET_OTP){email.send(required(p,"email"),"Password reset OTP",required(p,"otp"));}
  else {UUID user=UUID.fromString(required(p,"userId"));Notification n=notifications.save(Notification.unread(user,type,title(type),content(type,p),string(p,"referenceId"),string(p,"referenceType"),Instant.now(clock)));realtime.send(n);if((type==NotificationType.USER_APPROVED||type==NotificationType.USER_REJECTED)&&p.get("email")!=null)email.send(string(p,"email"),title(type),content(type,p));}
  inbox.record(e.eventId(),e.eventType(),Instant.now(clock));return true;}
 private NotificationType type(String t){return switch(t){case "PASSWORD_RESET_OTP_REQUESTED"->NotificationType.PASSWORD_RESET_OTP;case "USER_APPROVED"->NotificationType.USER_APPROVED;case "USER_REJECTED"->NotificationType.USER_REJECTED;case "QUESTION_SUBMITTED"->NotificationType.QUESTION_SUBMITTED;case "QUESTION_APPROVED"->NotificationType.QUESTION_APPROVED;case "QUESTION_REJECTED"->NotificationType.QUESTION_REJECTED;case "QUESTION_REVISION_REQUESTED"->NotificationType.QUESTION_REVISION_REQUESTED;case "AI_GENERATION_COMPLETED"->NotificationType.AI_GENERATION_COMPLETED;case "AI_GENERATION_FAILED"->NotificationType.AI_GENERATION_FAILED;case "EXAM_GENERATED"->NotificationType.EXAM_GENERATED;default->throw new IllegalArgumentException("Unsupported event type");};}
 private String title(NotificationType t){return switch(t){case USER_APPROVED->"Registration approved";case USER_REJECTED->"Registration rejected";case QUESTION_SUBMITTED->"Question submitted";case QUESTION_APPROVED->"Question approved";case QUESTION_REJECTED->"Question rejected";case QUESTION_REVISION_REQUESTED->"Question revision requested";case AI_GENERATION_COMPLETED->"AI generation completed";case AI_GENERATION_FAILED->"AI generation failed";case EXAM_GENERATED->"Exam generated";default->"Notification";};}
 private String content(NotificationType t,Map<String,Object> p){Object m=p.get("message");return m==null?title(t):String.valueOf(m);}
 private String required(Map<String,Object> p,String k){String v=string(p,k);if(v==null||v.isBlank())throw new IllegalArgumentException("Missing event field: "+k);return v;}private String string(Map<String,Object> p,String k){Object v=p.get(k);return v==null?null:String.valueOf(v);}
}
