package com.hau.notification.application.service;
import com.hau.notification.application.port.in.ScheduleNotificationUseCase;import com.hau.notification.application.port.out.*;import com.hau.notification.domain.model.*;import com.hau.notification.domain.repository.*;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.UUID;
@Service public class ScheduledNotificationService implements ScheduleNotificationUseCase{
 private final ScheduledNotificationRepository schedules;private final NotificationRepository notifications;private final AudienceResolver audience;private final RealtimeNotifier realtime;private final Clock clock;
 public ScheduledNotificationService(ScheduledNotificationRepository s,NotificationRepository n,AudienceResolver a,RealtimeNotifier r,Clock c){schedules=s;notifications=n;audience=a;realtime=r;clock=c;}
 @Transactional public ScheduledNotification schedule(String role,String faculty,String title,String content,Instant at,UUID creator){return schedules.save(ScheduledNotification.pending(role,faculty,title,content,at,creator,Instant.now(clock)));}
 @Scheduled(fixedDelayString="${notification.scheduler-delay-ms:5000}") @Transactional public void dispatchDue(){for(var s:schedules.findDue(Instant.now(clock),50))dispatch(s);}
 private void dispatch(ScheduledNotification original){var claimed=schedules.save(original.processing(Instant.now(clock)));try{var recipients=audience.resolve(claimed.getTargetRole(),claimed.getTargetFaculty());if(recipients.isEmpty())throw new IllegalStateException("Scheduled audience is empty");for(var r:recipients){var n=notifications.save(Notification.unread(r.userId(),NotificationType.SYSTEM,claimed.getTitle(),claimed.getContent(),claimed.getId().toString(),"SCHEDULED_NOTIFICATION",Instant.now(clock)));realtime.send(n);}schedules.save(claimed.completed(Instant.now(clock)));}catch(Exception e){schedules.save(claimed.failed(Instant.now(clock)));}}
}
