package com.notificationservice.application.service;
import com.notificationservice.application.dto.*; import com.notificationservice.application.port.in.EventNotificationUseCase; import com.notificationservice.application.port.out.*; import com.notificationservice.domain.model.*; import com.notificationservice.domain.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class EventNotificationService implements EventNotificationUseCase {
 private final NotificationRepository notifications; private final DeviceTokenRepository deviceTokens; private final ProcessedEventStore inbox; private final RealtimeNotifier realtime; private final PushProvider push; private final EmailSender email; private final Clock clock; private final UserContactResolver contacts; private final AudienceResolver audience; private final TelegramNotificationService telegram; private final EmailTemplateRenderer renderer;
 public EventNotificationService(NotificationRepository n,DeviceTokenRepository d,ProcessedEventStore i,RealtimeNotifier r,PushProvider p,EmailSender e,Clock c,UserContactResolver u){this(n,d,i,r,p,e,c,u,null,null,new EmailTemplateRenderer());}
 public EventNotificationService(NotificationRepository n,DeviceTokenRepository d,ProcessedEventStore i,RealtimeNotifier r,PushProvider p,EmailSender e,Clock c,UserContactResolver u,AudienceResolver a,TelegramNotificationService t){this(n,d,i,r,p,e,c,u,a,t,new EmailTemplateRenderer());}
 @org.springframework.beans.factory.annotation.Autowired public EventNotificationService(NotificationRepository n,DeviceTokenRepository d,ProcessedEventStore i,RealtimeNotifier r,PushProvider p,EmailSender e,Clock c,UserContactResolver u,AudienceResolver a,TelegramNotificationService t,EmailTemplateRenderer x){notifications=n;deviceTokens=d;inbox=i;realtime=r;push=p;email=e;clock=c;contacts=u;audience=a;telegram=t;renderer=x;}
 @Transactional public boolean handle(IncomingEvent event){if(inbox.exists(event.eventId()))return false;NotificationType type=type(event.eventType());Map<String,Object> p=event.payload()==null?Map.of():event.payload();if(type==NotificationType.PASSWORD_RESET_OTP){email.send(required(p,"email"),"[HAU QM] Mã xác thực đặt lại mật khẩu",renderer.render(null,"Mã xác thực đặt lại mật khẩu",otpBody(p),"Truy cập HAU QM","https://exam.nova.io.vn/"));inbox.record(event.eventId(),event.eventType(),Instant.now(clock));return true;}if(type==NotificationType.NEW_USER_REGISTERED||type==NotificationType.USER_LOGIN_SUCCESS||type==NotificationType.QUESTION_SUBMITTED){fanout(type,p);if(type==NotificationType.NEW_USER_REGISTERED&&p.get("email")!=null)email.send(string(p,"email"),title(type),renderer.render(string(p,"fullName"),title(type),content(type,p),"Truy cập HAU QM","https://exam.nova.io.vn/"));inbox.record(event.eventId(),event.eventType(),Instant.now(clock));return true;}UUID recipient=recipient(type,p);deliver(recipient,type,p);if((type==NotificationType.USER_APPROVED||type==NotificationType.USER_REJECTED)&&p.get("email")!=null)email.send(string(p,"email"),title(type),renderer.render(string(p,"fullName"),title(type),content(type,p),"Đăng nhập HAU QM","https://exam.nova.io.vn/login"));if(isQuestionEmail(type)&&contacts!=null){UserContact c=contacts.resolve(recipient);if(c!=null&&c.email()!=null&&!c.email().isBlank())email.send(c.email(),title(type),renderer.render(c.fullName(),title(type),questionBody(type,p,c),"Xem câu hỏi","https://exam.nova.io.vn/questions/"+string(p,"questionId")));}inbox.record(event.eventId(),event.eventType(),Instant.now(clock));return true;}
 private void fanout(NotificationType type,Map<String,Object> p){if(audience==null)return;String role=type==NotificationType.QUESTION_SUBMITTED?"SUBJECT_ADMIN":"SYSTEM_ADMIN";String faculty=type==NotificationType.QUESTION_SUBMITTED?string(p,"facultyId"):null;for(Recipient r:audience.resolve(role,faculty)){deliver(r.userId(),type,p);if(r.email()!=null&&!r.email().isBlank())email.send(r.email(),title(type),renderer.render(string(p,"fullName"),title(type),content(type,p),"Mở HAU QM","https://exam.nova.io.vn/"));}}
 private void deliver(UUID user,NotificationType type,Map<String,Object> p){Notification n=notifications.save(Notification.unread(user,type,title(type),content(type,p),referenceId(type,p),referenceType(type,p),Instant.now(clock)));realtime.send(n);deviceTokens.findActiveByUser(user).forEach(t->{if(push.send(t,n)==PushProvider.PushResult.INVALID_TOKEN)deviceTokens.save(t.deactivate(Instant.now(clock)));});if(telegram!=null&&telegram.enabled(user)&&telegramAllowed(user,type))try{telegram.send(user,telegramBody(type,p));}catch(Exception ignored){}}
 private boolean telegramAllowed(UUID u,NotificationType t){var p=telegram.preferences(u);return switch(t){case NEW_USER_REGISTERED->p.newUsers();case USER_LOGIN_SUCCESS->p.loginEvents();case QUESTION_SUBMITTED->p.questionPending();case USER_APPROVED,USER_REJECTED,USER_ROLE_CHANGED,USER_FACULTY_CHANGED,USER_STATUS_CHANGED->p.actionable();default->p.systemEvents();};}
 private UUID recipient(NotificationType t,Map<String,Object> p){String f=switch(t){case USER_APPROVED,USER_REJECTED,USER_ROLE_CHANGED,USER_FACULTY_CHANGED,USER_STATUS_CHANGED->"recipientUserId";case QUESTION_APPROVED,QUESTION_REJECTED,QUESTION_REVISION_REQUESTED->p.containsKey("authorUserId")?"authorUserId":"createdBy";case AI_GENERATION_COMPLETED,AI_GENERATION_FAILED->"requestedBy";case EXAM_GENERATED->p.containsKey("requestedBy")?"requestedBy":"createdBy";default->throw new IllegalArgumentException("No recipient contract");};return UUID.fromString(required(p,f));}
 private NotificationType type(String x){return switch(x){case "PASSWORD_RESET_OTP_REQUESTED"->NotificationType.PASSWORD_RESET_OTP;case "USER_REGISTRATION_REQUESTED"->NotificationType.NEW_USER_REGISTERED;case "USER_LOGIN_SUCCESS"->NotificationType.USER_LOGIN_SUCCESS;case "USER_APPROVED"->NotificationType.USER_APPROVED;case "USER_REJECTED"->NotificationType.USER_REJECTED;case "USER_ROLE_CHANGED"->NotificationType.USER_ROLE_CHANGED;case "USER_FACULTY_CHANGED"->NotificationType.USER_FACULTY_CHANGED;case "USER_STATUS_CHANGED"->NotificationType.USER_STATUS_CHANGED;case "QUESTION_SUBMITTED"->NotificationType.QUESTION_SUBMITTED;case "QUESTION_APPROVED"->NotificationType.QUESTION_APPROVED;case "QUESTION_REJECTED"->NotificationType.QUESTION_REJECTED;case "QUESTION_REVISION_REQUESTED"->NotificationType.QUESTION_REVISION_REQUESTED;case "AI_GENERATION_COMPLETED"->NotificationType.AI_GENERATION_COMPLETED;case "AI_GENERATION_FAILED"->NotificationType.AI_GENERATION_FAILED;case "EXAM_GENERATED"->NotificationType.EXAM_GENERATED;default->throw new IllegalArgumentException("Unsupported event type");};}
 private String title(NotificationType t){return switch(t){case NEW_USER_REGISTERED->"Người dùng mới đăng ký";case USER_LOGIN_SUCCESS->"Đăng nhập mới";case USER_APPROVED->"[HAU QM] Tài khoản của bạn đã được phê duyệt";case USER_REJECTED->"[HAU QM] Thông báo đăng ký tài khoản";case USER_ROLE_CHANGED->"Vai trò tài khoản của bạn đã được cập nhật";case USER_FACULTY_CHANGED->"Đơn vị/Khoa của bạn đã được thay đổi";case USER_STATUS_CHANGED->"Trạng thái tài khoản của bạn đã được cập nhật";case QUESTION_SUBMITTED->"Có câu hỏi mới cần phê duyệt";case QUESTION_APPROVED->"[HAU QM] Câu hỏi đã được phê duyệt";case QUESTION_REJECTED->"[HAU QM] Câu hỏi đã bị từ chối";case QUESTION_REVISION_REQUESTED->"[HAU QM] Câu hỏi cần chỉnh sửa";case AI_GENERATION_COMPLETED->"AI generation completed";case AI_GENERATION_FAILED->"AI generation failed";case EXAM_GENERATED->"Exam generated";default->"Notification";};}
 private String content(NotificationType t,Map<String,Object> p){String name=string(p,"fullName"),code=string(p,"lecturerCode");return switch(t){case NEW_USER_REGISTERED->name+" ("+code+") vừa đăng ký tài khoản. Vui lòng truy cập HAU QM để kiểm tra và phê duyệt.";case USER_LOGIN_SUCCESS->(name==null?code:name+" ("+code+")")+" vừa đăng nhập vào hệ thống lúc "+string(p,"occurredAt")+".";case QUESTION_SUBMITTED->"Có câu hỏi mới cần phê duyệt. Môn học: "+string(p,"subjectId")+". Người gửi: "+(name==null?code:name)+".";case USER_APPROVED->"Xin chào "+name+", tài khoản HAU QM của bạn đã được phê duyệt.";case USER_REJECTED->"Xin chào "+name+", yêu cầu đăng ký tài khoản HAU QM chưa được chấp thuận.";default->string(p,"message")!=null?string(p,"message"):title(t);};}
 private String telegramBody(NotificationType t,Map<String,Object> p){return "HAU QM\n\n"+content(t,p)+"\n\nMở HAU QM để xem chi tiết:\nhttps://exam.nova.io.vn/";}
 private String otpBody(Map<String,Object> p){return "Xin chào,\n\nMã xác thực đặt lại mật khẩu HAU QM của bạn là:\n\n        "+required(p,"otp")+"\n\nMã có hiệu lực trong 5 phút. Nếu bạn không yêu cầu, hãy bỏ qua email này.";}
 private String questionBody(NotificationType t,Map<String,Object> p,UserContact c){return "Xin chào "+c.fullName()+",\n\nCâu hỏi "+string(p,"questionId")+" đã được "+(t==NotificationType.QUESTION_APPROVED?"phê duyệt":"cập nhật trạng thái")+".\n\nTruy cập HAU QM để xem chi tiết:\nhttps://exam.nova.io.vn/";}
 private boolean isQuestionEmail(NotificationType t){return t==NotificationType.QUESTION_APPROVED||t==NotificationType.QUESTION_REJECTED||t==NotificationType.QUESTION_REVISION_REQUESTED;}
 private String referenceId(NotificationType t,Map<String,Object> p){return t==NotificationType.NEW_USER_REGISTERED?null:string(p,"questionId");} private String referenceType(NotificationType t,Map<String,Object> p){return t==NotificationType.NEW_USER_REGISTERED?"PENDING_USERS":t==NotificationType.QUESTION_SUBMITTED||isQuestionEmail(t)?"QUESTION":null;}
 private String required(Map<String,Object> p,String k){String v=string(p,k);if(v==null||v.isBlank())throw new IllegalArgumentException("Missing event field: "+k);return v;} private String string(Map<String,Object> p,String k){Object v=p.get(k);return v==null?null:String.valueOf(v);}
}
