package com.notificationservice.application.service;
import com.notificationservice.application.port.out.SupportImageStorage; import com.notificationservice.domain.exception.*; import com.notificationservice.domain.model.SupportStatus; import com.notificationservice.infrastructure.persistence.entity.*; import com.notificationservice.infrastructure.persistence.repository.*; import com.notificationservice.presentation.response.SupportResponses; import org.springframework.data.domain.*; import org.springframework.messaging.simp.SimpMessagingTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import java.time.Instant; import java.util.*;
@Service public class SupportChatService {
 private static final Set<String> TYPES=Set.of("image/png","image/jpeg","image/webp"); private final SupportConversationRepository conversations; private final SupportMessageRepository messages; private final SupportAttachmentRepository attachments; private final SupportImageStorage storage; private final SimpMessagingTemplate realtime;
 public SupportChatService(SupportConversationRepository c,SupportMessageRepository m,SupportAttachmentRepository a,SupportImageStorage s,SimpMessagingTemplate r){conversations=c;messages=m;attachments=a;storage=s;realtime=r;}
 @Transactional public SupportResponses.Conversation create(UUID actor,String role,String faculty,String subject,String content){if(!Set.of("USER","SUBJECT_ADMIN").contains(role))throw new ForbiddenNotificationAccessException();if(subject==null||subject.isBlank())throw new IllegalArgumentException("Subject is required");var now=Instant.now();var c=new SupportConversationEntity();c.setId(UUID.randomUUID());c.setCreatedByUserId(actor);c.setCreatedByRole(role);c.setFacultyId(faculty);c.setSubject(subject.trim());c.setStatus(SupportStatus.OPEN);c.setCreatedAt(now);c.setUpdatedAt(now);c.setLastMessageAt(now);var saved=conversations.save(c);if(content!=null&&!content.isBlank())saveMessage(saved,actor,role,content,null);return SupportResponses.Conversation.from(saved);}
 @Transactional(readOnly=true) public Page<SupportResponses.Conversation> listMine(UUID actor,int page,int size){return conversations.findByCreatedByUserIdOrderByLastMessageAtDesc(actor,pageable(page,size)).map(SupportResponses.Conversation::from);}
 @Transactional(readOnly=true) public Page<SupportResponses.Conversation> listAdmin(SupportStatus status,int page,int size){var p=pageable(page,size);return (status==null?conversations.findAllByOrderByLastMessageAtDesc(p):conversations.findByStatusOrderByLastMessageAtDesc(status,p)).map(SupportResponses.Conversation::from);}
 @Transactional(readOnly=true) public SupportResponses.Conversation getConversation(UUID id,UUID actor,String role){return SupportResponses.Conversation.from(access(id,actor,role));}
 @Transactional(readOnly=true) public Page<SupportResponses.Message> history(UUID id,UUID actor,String role,int page,int size){access(id,actor,role);return messages.findByConversationIdOrderByCreatedAtDesc(id,pageable(page,size)).map(m->SupportResponses.Message.from(m,attachments.findByMessageId(m.getId())));}
 @Transactional public SupportResponses.Message send(UUID id,UUID actor,String role,String content,MultipartFile file){var c=access(id,actor,role);String body=content==null?null:content.trim();if((body==null||body.isBlank())&&(file==null||file.isEmpty()))throw new IllegalArgumentException("Message content or image is required");return saveMessage(c,actor,role,body,file==null||file.isEmpty()?null:store(file));}
 @Transactional public SupportResponses.Conversation status(UUID id,UUID actor,SupportStatus value){var c=access(id,actor,"SYSTEM_ADMIN");c.setStatus(value);c.setUpdatedAt(Instant.now());return SupportResponses.Conversation.from(conversations.save(c));}
 @Transactional public int markRead(UUID id,UUID actor,String role){access(id,actor,role);var all=messages.findByConversationIdOrderByCreatedAtDesc(id,Pageable.ofSize(100));int count=0;for(var m:all)if(!actor.equals(m.getSenderId())&&m.getReadAt()==null){m.setReadAt(Instant.now());messages.save(m);count++;}return count;}
 @Transactional(readOnly=true) public long unread(UUID actor,String role){return "SYSTEM_ADMIN".equals(role)?messages.countUnreadForAdmin(actor):messages.countUnreadForCreator(actor);}
 private SupportResponses.Message saveMessage(SupportConversationEntity c,UUID actor,String role,String body,SupportImageStorage.StoredImage stored){var now=Instant.now();var m=new SupportMessageEntity();m.setId(UUID.randomUUID());m.setConversationId(c.getId());m.setSenderId(actor);m.setSenderRole(role);m.setContent(body==null||body.isBlank()?null:body);m.setCreatedAt(now);var saved=messages.save(m);if(stored!=null){var a=new SupportAttachmentEntity();a.setId(UUID.randomUUID());a.setMessageId(saved.getId());a.setType("IMAGE");a.setFileName(stored.fileName());a.setContentType(stored.contentType());a.setFileSize(stored.fileSize());a.setUrl(stored.url());a.setPublicId(stored.publicId());a.setCreatedAt(now);attachments.save(a);}c.setUpdatedAt(now);c.setLastMessageAt(now);conversations.save(c);var dto=SupportResponses.Message.from(saved,attachments.findByMessageId(saved.getId()));Map<String,Object> event=new HashMap<>();event.put("eventType","SUPPORT_MESSAGE_CREATED");event.put("conversationId",c.getId());event.put("messageId",saved.getId());event.put("sender",actor);event.put("senderRole",role);event.put("createdAt",now);event.put("message",dto);realtime.convertAndSend("/topic/support/admin",(Object)event);realtime.convertAndSendToUser(c.getCreatedByUserId().toString(),"/queue/support",event);return dto;}
 private SupportImageStorage.StoredImage store(MultipartFile f){String type=f.getContentType()==null?"":f.getContentType().toLowerCase(Locale.ROOT);if(!TYPES.contains(type))throw new IllegalArgumentException("Unsupported image type");if(f.getSize()<=0||f.getSize()>storage.maxSize())throw new IllegalArgumentException("Image size is invalid");String name=f.getOriginalFilename()==null?"image":f.getOriginalFilename().replaceAll("[^A-Za-z0-9._-]","_");try{byte[] b=f.getBytes();if(!signatureMatches(b,type))throw new IllegalArgumentException("Image signature is invalid");return storage.upload(b,name,type,f.getSize());}catch(java.io.IOException e){throw new IllegalArgumentException("Upload failed",e);}}
 private boolean signatureMatches(byte[] b,String type){if("image/png".equals(type))return b.length>8&&b[0]==(byte)137&&b[1]==80&&b[2]==78&&b[3]==71;if("image/jpeg".equals(type))return b.length>3&&(b[0]&255)==255&&(b[1]&255)==216&&(b[2]&255)==255;if("image/webp".equals(type))return b.length>12&&b[0]=='R'&&b[1]=='I'&&b[2]=='F'&&b[3]=='F'&&b[8]=='W'&&b[9]=='E'&&b[10]=='B'&&b[11]=='P';return false;}
 private SupportConversationEntity access(UUID id,UUID actor,String role){var c=conversations.findById(id).orElseThrow(()->new NotificationNotFoundException(id));if(!"SYSTEM_ADMIN".equals(role)&&!actor.equals(c.getCreatedByUserId()))throw new ForbiddenNotificationAccessException();return c;}
 private Pageable pageable(int page,int size){return PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),50));}
}
