import {useCallback,useEffect,useRef,useState} from 'react'
import {authStore} from '../../../stores/authStore'
import {api} from '../../../services/api/client'
import {supportChatApi} from '../api/supportChatApi'
import {connectNotificationSocket} from '../../../services/websocket/notificationSocket'
import {Icon} from '../../../components/ui'
import '../support-chat.css'

export function HumanChatDropdown(){
 const {role}=authStore.getSnapshot();const root=useRef(null);const picker=useRef(null);const[open,setOpen]=useState(false),[contacts,setContacts]=useState([]),[list,setList]=useState([]),[current,setCurrent]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[file,setFile]=useState(null),[unread,setUnread]=useState(0),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const [people,conversations,count]=await Promise.all([api.get('/api/v1/users/me/chat-contacts'),role==='SYSTEM_ADMIN'?supportChatApi.adminList({size:30}):supportChatApi.mine({size:20}),supportChatApi.unread()]);setContacts(people||[]);setList(conversations?.content||[]);setUnread(Number(count)||0)}catch(e){setError(e.message)}},[role]);
 useEffect(()=>{queueMicrotask(()=>void load());const stop=connectNotificationSocket({onMessage:()=>{},onSupport:e=>{const m=e.message;if(!m)return;setMessages(x=>x.some(y=>y.id===m.id)?x:[...x,m]);if(!open)setUnread(x=>x+1)},onStatus:()=>{}});const outside=e=>{if(!root.current?.contains(e.target))setOpen(false)};document.addEventListener('pointerdown',outside);return()=>{stop();document.removeEventListener('pointerdown',outside)}},[load,open]);
 async function openConversation(conversation){setCurrent(conversation);try{const p=await supportChatApi.messages(conversation.id,{size:30});setMessages((p?.content||[]).reverse());await supportChatApi.read(conversation.id);setUnread(Number(await supportChatApi.unread())||0)}catch(e){setError(e.message)}}
 async function openContact(contact){try{const conversation=await supportChatApi.create(`Trao đổi với ${contact.displayName}`,'');await openConversation(conversation)}catch(e){setError(e.message)}}
 async function send(e){e.preventDefault();if(!current||(!text.trim()&&!file))return;const body=text;setText('');try{const message=await supportChatApi.send(current.id,body,file);setMessages(x=>x.some(y=>y.id===message.id)?x:[...x,message]);setFile(null)}catch(e){setError(e.message);setText(body)}}
 return <div className="human-chat" ref={root}><button type="button" className="human-chat-button" aria-label="Mở tin nhắn nội bộ" onClick={()=>setOpen(x=>!x)}><Icon name="messages" size={18}/>{unread>0&&<b>{unread>99?'99+':unread}</b>}</button>{open&&<section className="human-chat-panel" aria-label="Tin nhắn nội bộ">{!current?<><header><strong>Tin nhắn</strong></header><div className="human-chat-list">{contacts.map(c=><button key={`contact-${c.userId}`} onClick={()=>void openContact(c)}><span className="human-avatar">{c.avatarUrl?<img src={c.avatarUrl} alt=""/>:String(c.displayName||'U').slice(0,2)}</span><span><strong>{c.displayName}</strong><small>{c.role} · {c.facultyId||'Toàn hệ thống'}</small></span></button>)}{list.map(c=><button key={c.id} onClick={()=>void openConversation(c)}><span className="human-avatar">{String(c.createdByUserId||'U').slice(0,2)}</span><span><strong>{c.subject}</strong><small>{c.createdByRole} · {c.status}</small></span></button>)}{!contacts.length&&!list.length&&<p>Chưa có người liên hệ.</p>}</div></>:<><header><button onClick={()=>setCurrent(null)} aria-label="Quay lại">‹</button><div><strong>{current.subject}</strong><small>{current.createdByRole} · {current.facultyId||''}</small></div><button onClick={()=>setOpen(false)} aria-label="Đóng">×</button></header><div className="human-chat-messages">{messages.map(m=><article key={m.id} className={m.senderId===authStore.getSnapshot().currentUser?.id?'mine':'theirs'}><small>{m.senderRole}</small>{m.content&&<p>{m.content}</p>}{m.attachments?.map(a=><img key={a.id} src={a.url} alt={a.fileName}/>)}</article>)}</div><form className="human-chat-composer" onSubmit={send}><div>{file&&<span>{file.name}<button type="button" onClick={()=>setFile(null)}>×</button></span>}</div><textarea value={text} onChange={e=>setText(e.target.value)} onPaste={e=>{const item=[...(e.clipboardData?.items||[])].find(i=>i.type.startsWith('image/'));if(item){e.preventDefault();setFile(item.getAsFile())}}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();void send(e)}}} placeholder="Nhập tin nhắn…" rows="2"/><div><button type="button" onClick={()=>picker.current?.click()} aria-label="Đính kèm ảnh"><Icon name="paperclip"/></button><input ref={picker} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={!text.trim()&&!file} aria-label="Gửi">➤</button></div></form></>}{error&&<p className="support-error">{error}</p>}</section>}</div>
}
