import {useCallback,useEffect,useRef,useState} from "react";
import {authStore} from "../../../stores/authStore"; import {supportChatApi} from "../api/supportChatApi"; import {connectNotificationSocket} from "../../../services/websocket/notificationSocket"; import {Icon} from "../../../components/ui/Icon"; import "../support-chat.css";
const quick=["Báo lỗi hệ thống","Hỏi cách sử dụng","Liên hệ quản trị viên"];
export function SupportChatWidget(){
 const {role}=authStore.getSnapshot(); const [open,setOpen]=useState(false),[list,setList]=useState([]),[current,setCurrent]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(""),[file,setFile]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[unread,setUnread]=useState(0),[connection,setConnection]=useState("connecting"),[pos,setPos]=useState(()=>{try{return JSON.parse(localStorage.getItem("hau-support-position"))}catch{return null}}); const input=useRef(null),picker=useRef(null),drag=useRef(null),moved=useRef(false);
 const load=useCallback(async()=>{try{const p=role==="SYSTEM_ADMIN"?await supportChatApi.adminList({size:30}):await supportChatApi.mine({size:20});setList(p?.content||[])}catch(e){setError(e.message)}},[role]);
 const history=useCallback(async(id)=>{try{const p=await supportChatApi.messages(id,{size:30});setMessages((p?.content||[]).reverse());await supportChatApi.read(id)}catch(e){setError(e.message)}},[]);
 useEffect(()=>{if(!role)return;const timer=setTimeout(()=>{void load();supportChatApi.unread().then(n=>setUnread(Number(n)||0)).catch(()=>{})},0);const disconnect=connectNotificationSocket({onStatus:setConnection,onSupport:e=>{const m=e.message;if(!m)return;setMessages(old=>old.some(x=>x.id===m.id)?old:[...old,m]);if(!open&&m.senderId!==authStore.getSnapshot().currentUser?.id)setUnread(n=>n+1)}});return()=>{clearTimeout(timer);disconnect()}},[role,load,open]);
 useEffect(()=>{if(open)input.current?.focus()},[open,current]);
 async function create(subject){try{const c=await supportChatApi.create(subject);setList(x=>[c,...x]);setCurrent(c);setMessages([])}catch(e){setError(e.message)}}
 async function send(e){e?.preventDefault();if(!current||busy||(!text.trim()&&!file))return;const body=text;setText("");setBusy(true);try{const m=await supportChatApi.send(current.id,body,file);setMessages(x=>x.some(i=>i.id===m.id)?x:[...x,m]);setFile(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 function key(e){if(e.key==="Enter"&&!e.shiftKey&&!e.isComposing){e.preventDefault();void send(e)}} function paste(e){const i=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith("image/"));if(i){e.preventDefault();setFile(i.getAsFile())}}
 function down(e){drag.current={x:e.clientX,y:e.clientY,ox:pos?.x??window.innerWidth-72,oy:pos?.y??window.innerHeight-120};moved.current=false;e.currentTarget.setPointerCapture(e.pointerId)} function move(e){if(!drag.current)return;const d=drag.current,x=Math.min(Math.max(8,d.ox+e.clientX-d.x),innerWidth-60),y=Math.min(Math.max(8,d.oy+e.clientY-d.y),innerHeight-60);if(Math.abs(e.clientX-d.x)+Math.abs(e.clientY-d.y)>5)moved.current=true;setPos({x,y})} function up(){if(moved.current){try{localStorage.setItem("hau-support-position",JSON.stringify(pos))}catch(e){void e}}drag.current=null}
 if(!role)return null;return <div className="support-widget"><button className="support-fab" style={pos?{left:pos.x,top:pos.y,right:"auto",bottom:"auto"}:undefined} aria-label="Mở hỗ trợ" onPointerDown={down} onPointerMove={move} onPointerUp={up} onClick={()=>!moved.current&&(setOpen(true),setUnread(0))}><Icon name="support" size={24}/>{unread>0&&<b>{unread>9?"9+":unread}</b>}</button>{open&&<section className="support-window" aria-label="Hỗ trợ hệ thống"><header><div><strong>HAU QM</strong><span>Hỗ trợ hệ thống · {connection==="connected"?"Đang kết nối":"Đang kết nối lại…"}</span></div><button aria-label="Thu nhỏ" onClick={()=>setOpen(false)}>×</button></header>{!current?<div className="support-start"><h2>Xin chào</h2><p>Bạn đang gặp vấn đề gì với HAU QM?</p>{list.map(c=><button key={c.id} onClick={()=>{setCurrent(c);void history(c.id)}}>{c.subject}</button>)}{role!=="SYSTEM_ADMIN"&&quick.map(x=><button key={x} onClick={()=>void create(x)}>{x}</button>)}</div>:<><div className="support-conversation-head"><button onClick={()=>setCurrent(null)}>‹</button><div><strong>{current.subject}</strong><small>{current.status}</small></div>{role==="SYSTEM_ADMIN"&&<select value={current.status} onChange={async e=>{const c=await supportChatApi.status(current.id,e.target.value);setCurrent(c)}}><option>OPEN</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>CLOSED</option></select>}</div><div className="support-messages">{messages.map(m=><article key={m.id} className={m.senderRole===role?"mine":"theirs"}><span>{m.senderRole===role?"Bạn":m.senderRole==="SYSTEM_ADMIN"?"Quản trị viên":"Người dùng"}</span>{m.content&&<p>{m.content}</p>}{m.attachments?.map(a=><a key={a.id} href={a.url} target="_blank" rel="noreferrer"><img src={a.url} alt={a.fileName}/></a>)}<time>{new Date(m.createdAt).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}</time></article>)}</div><form className="support-composer" onSubmit={send}><div className="support-preview">{file&&<span>{file.name}<button type="button" onClick={()=>setFile(null)} aria-label="Xóa ảnh">×</button></span>}</div><textarea ref={input} value={text} onChange={e=>setText(e.target.value)} onKeyDown={key} onPaste={paste} aria-label="Nhập tin nhắn" placeholder="Nhập tin nhắn…" rows="2"/><div><button type="button" aria-label="Đính kèm ảnh" onClick={()=>picker.current?.click()}><Icon name="paperclip"/></button><input ref={picker} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={busy||(!text.trim()&&!file)} aria-label="Gửi">➤</button></div></form></>}{error&&<p className="support-error" role="alert">{error}</p>}</section>}</div>;
}
