package com.questionservice.presentation.controller;
import com.questionservice.application.model.*; import com.questionservice.application.service.QuestionService; import com.questionservice.domain.model.*; import com.questionservice.presentation.request.*; import com.questionservice.presentation.response.*; import com.questionservice.presentation.support.ActorResolver; import jakarta.validation.Valid; import java.util.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/questions") public class QuestionController {
 private final QuestionService service;private final ActorResolver actors;public QuestionController(QuestionService s,ActorResolver a){service=s;actors=a;}
 @PostMapping @PreAuthorize("hasRole('USER')") public ApiResponse<QuestionResponse> create(@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody QuestionRequest r){return ApiResponse.ok(QuestionResponse.from(service.create(actors.from(jwt),input(r))));}
 @PutMapping("/{id}") @PreAuthorize("hasRole('USER')") public ApiResponse<QuestionResponse> update(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt,@Valid @RequestBody QuestionRequest r){return ApiResponse.ok(QuestionResponse.from(service.update(id,actors.from(jwt),input(r))));}
 @DeleteMapping("/{id}") @PreAuthorize("hasRole('USER')") public ApiResponse<Void> delete(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt){service.delete(id,actors.from(jwt));return ApiResponse.ok(null);}
 @GetMapping("/{id}") public ApiResponse<QuestionResponse> get(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt){return ApiResponse.ok(QuestionResponse.from(service.getForActor(id,actors.from(jwt))));}
 @GetMapping public ApiResponse<PageResult<QuestionResponse>> search(@AuthenticationPrincipal Jwt jwt,@RequestParam(required=false)String facultyId,@RequestParam(required=false)UUID subjectId,@RequestParam(required=false)UUID chapterId,@RequestParam(required=false)UUID topicId,@RequestParam(required=false)Difficulty difficulty,@RequestParam(required=false)QuestionStatus status,@RequestParam(required=false)QuestionSource source,@RequestParam(required=false)UUID createdBy,@RequestParam(required=false)String keyword,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="createdAt,desc")String sort){var p=service.search(actors.from(jwt),new QuestionCriteria(facultyId,subjectId,chapterId,topicId,difficulty,status,source,createdBy,keyword,page,size,sort));return ApiResponse.ok(new PageResult<>(p.items().stream().map(QuestionResponse::from).toList(),p.page(),p.size(),p.totalElements(),p.totalPages()));}
 @PostMapping("/{id}/submit") @PreAuthorize("hasRole('USER')") public ApiResponse<QuestionResponse> submit(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt,@RequestHeader(value="X-Correlation-Id",required=false)UUID c){return ApiResponse.ok(QuestionResponse.from(service.submit(id,actors.from(jwt),c)));}
 @PostMapping("/{id}/approve") @PreAuthorize("hasRole('SUBJECT_ADMIN')") public ApiResponse<QuestionResponse> approve(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt,@RequestHeader(value="X-Correlation-Id",required=false)UUID c,@RequestBody(required=false)ReviewRequest r){return ApiResponse.ok(QuestionResponse.from(service.approve(id,actors.from(jwt),r==null?null:r.reason(),c)));}
 @PostMapping("/{id}/reject") @PreAuthorize("hasRole('SUBJECT_ADMIN')") public ApiResponse<QuestionResponse> reject(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt,@RequestHeader(value="X-Correlation-Id",required=false)UUID c,@Valid @RequestBody ReviewRequest r){return ApiResponse.ok(QuestionResponse.from(service.reject(id,actors.from(jwt),r.reason(),c)));}
 @PostMapping("/{id}/request-revision") @PreAuthorize("hasRole('SUBJECT_ADMIN')") public ApiResponse<QuestionResponse> revision(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt,@RequestHeader(value="X-Correlation-Id",required=false)UUID c,@Valid @RequestBody ReviewRequest r){return ApiResponse.ok(QuestionResponse.from(service.requestRevision(id,actors.from(jwt),r.reason(),c)));}
 @PostMapping("/{id}/archive") @PreAuthorize("hasAnyRole('USER','SUBJECT_ADMIN')") public ApiResponse<QuestionResponse> archive(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt){return ApiResponse.ok(QuestionResponse.from(service.archive(id,actors.from(jwt))));}
 private static QuestionInput input(QuestionRequest r){return new QuestionInput(r.facultyId(),r.subjectId(),r.chapterId(),r.topicId(),r.content(),r.imageUrl(),r.storageKey(),r.type(),r.difficulty(),r.options().stream().map(o->new QuestionOption(null,o.label(),o.content(),o.imageUrl(),o.storageKey(),o.correct(),o.sortOrder())).toList());}
}
