import {useEffect,useMemo,useRef,useState} from 'react'
import {facultiesApi} from '../api/facultiesApi'
import {normalizePage} from '../model/userModel'

export function FacultyCombobox({value,onChange,label='Khoa',allowClear=false}){
  const root=useRef(null);const[items,setItems]=useState([]);const[query,setQuery]=useState('');const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
  useEffect(()=>{let active=true;facultiesApi.list({active:true,page:0,size:100}).then(result=>{if(active)setItems(normalizePage(result).items)}).catch(()=>{if(active)setError('Không tải được danh sách khoa.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
  useEffect(()=>{function outside(event){if(!root.current?.contains(event.target))setOpen(false)}document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[])
  const selected=items.find(item=>(item.code||item.id)===value)
  const filtered=useMemo(()=>{const keyword=query.trim().toLocaleLowerCase('vi-VN');return items.filter(item=>!keyword||item.name.toLocaleLowerCase('vi-VN').includes(keyword)||item.code.toLocaleLowerCase('vi-VN').includes(keyword))},[items,query])
  return <div className="faculty-combobox field" ref={root}><span>{label}</span><button type="button" className="faculty-combobox-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(current=>!current)}><span>{selected?.name||(allowClear?'Tất cả khoa':'Chọn khoa')}</span><small>{selected?.code||''}</small><b aria-hidden="true">⌄</b></button>{open&&<div className="faculty-combobox-popover"><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Tìm theo tên hoặc mã khoa" aria-label="Tìm khoa"/>{loading&&<p>Đang tải danh sách khoa…</p>}{error&&<p className="field-error">{error}</p>}{!loading&&!error&&!filtered.length&&<p>Không tìm thấy khoa phù hợp.</p>}{!loading&&!error&&<div role="listbox">{allowClear&&<button type="button" role="option" aria-selected={!value} onClick={()=>{onChange('');setQuery('');setOpen(false)}}><strong>Tất cả khoa</strong></button>}{filtered.map(item=><button type="button" role="option" aria-selected={(item.code||item.id)===value} key={item.id||item.code} onClick={()=>{onChange(item.code||item.id);setQuery('');setOpen(false)}}><strong>{item.name}</strong><small>{item.code}</small></button>)}</div>}</div>}</div>
}
