import {test,expect,ids} from './fixtures.js'

test('login restores an authenticated UI session',async({page,gateway})=>{await gateway.login('USER');await expect(page.getByText('HAU-EXAM').first()).toBeVisible()})
test('register reaches pending approval',async({page,gateway})=>{void gateway;await page.goto('/register');await page.getByLabel('Mã giảng viên').fill('E2E_NEW_USER');await page.getByLabel('Họ và tên').fill('E2E New User');await page.getByLabel('Email').fill('new-user@example.test');await page.getByLabel('Khoa').fill('CNTT');await page.getByLabel('Mật khẩu').fill('test-password');await page.getByRole('button',{name:'Đăng ký'}).click();await expect(page).toHaveURL(/registration-pending/);await expect(page.getByRole('status')).toBeVisible()})
test('forgot password reaches OTP and reset screens',async({page,gateway})=>{void gateway;await page.goto('/forgot-password');await page.getByLabel('Mã giảng viên').fill('E2E_USER');await page.getByRole('button',{name:'Gửi mã OTP'}).click();await expect(page).toHaveURL(/verify-otp/);await page.getByLabel('Mã OTP').fill('123456');await page.getByRole('button',{name:'Xác minh'}).click();await expect(page).toHaveURL(/reset-password/);await page.getByLabel('Mật khẩu mới').fill('new-password');await page.getByRole('button',{name:'Đặt lại mật khẩu'}).click();await expect(page).toHaveURL(/login/)})
test('SYSTEM_ADMIN approves a pending registration',async({page,gateway})=>{await gateway.login('SYSTEM_ADMIN');await page.goto('/admin/registrations');await expect(page.getByText('E2E_USER').last()).toBeVisible();await page.getByRole('button',{name:'Duyệt'}).click();await page.getByRole('dialog').getByRole('button',{name:'Duyệt'}).click();await expect(page.getByText('ACTIVE')).toBeVisible()})
test('USER creates and submits a question, SUBJECT_ADMIN approves it',async({page,gateway})=>{await gateway.login('USER');await page.goto('/questions/new');await page.getByLabel('Question Content').fill('E2E question content');await page.getByLabel('Subject').selectOption(ids.subject);await page.getByLabel('Chapter').selectOption(ids.chapter);for(const input of await page.getByLabel('Nội dung phương án').all())await input.fill('Answer content');await page.getByRole('radio').first().check();await page.getByRole('button',{name:'Lưu câu hỏi'}).click();await expect(page).toHaveURL(new RegExp(`/questions/${ids.question}`));await page.getByRole('button',{name:'Gửi duyệt'}).click();await page.getByRole('dialog').getByRole('button',{name:'Gửi duyệt'}).click();const adminPage=await page.context().newPage();await gateway.login('SUBJECT_ADMIN',adminPage);await adminPage.goto(`/review/${ids.question}`);await adminPage.getByRole('button',{name:'Phê duyệt'}).click();await adminPage.getByRole('dialog').getByRole('button',{name:'Phê duyệt'}).click();await expect(adminPage.getByRole('status')).toBeVisible()})
test('notification can be marked read through the UI',async({page,gateway})=>{await gateway.login('USER');await page.goto('/notifications');await expect(page.getByText('Question approved').first()).toBeVisible();await page.getByRole('button',{name:'Chưa đọc: Question approved'}).click();await expect(page.getByText('0 chưa đọc')).toBeVisible()})
test('AI job UI uses deterministic processing fixture',async({page,gateway})=>{await gateway.login('USER');await page.goto(`/ai/jobs/${ids.job}`);await expect(page.getByText(/PROCESSING|COMPLETED/).first()).toBeVisible();await page.reload();await expect(page.getByText(/COMPLETED|Generated question/).first()).toBeVisible()})
test('exam matrix generate flow reaches generated exam UI',async({page,gateway})=>{await gateway.login('SUBJECT_ADMIN');await page.goto('/exams/generate?matrixId='+ids.matrix);await page.getByLabel('Tên bộ đề').fill('E2E Exam');await page.getByRole('button',{name:'Sinh bộ đề'}).click();await expect(page).toHaveURL(new RegExp(`/exams/${ids.exam}`))})
