import {test,expect,ids} from './fixtures.js'
test('login restores an authenticated UI session',async({page,gateway})=>{await gateway.login('USER');await expect(page.getByText('HAU-EXAM').first()).toBeVisible()})
test('an authenticated request refreshes once after a 401',async({page,gateway})=>{
  await gateway.login('USER')
  gateway.expireNextProfile()
  await page.getByLabel('Mở menu tài khoản').click()
  await page.getByRole('group').getByRole('link',{name:'Hồ sơ cá nhân'}).click()
  await expect(page.getByRole('heading',{name:'Hồ sơ cá nhân'})).toBeVisible()
  await expect.poll(()=>gateway.refreshCalls()).toBe(1)
})
test('logout clears the session and returns to login',async({page,gateway})=>{
  await gateway.login('USER')
  await page.getByRole('complementary',{name:'Điều hướng chính'}).getByRole('button',{name:'Đăng xuất'}).click()
  await expect(page).toHaveURL(/\/login$/)
})
test('register reaches pending approval',async({page,gateway})=>{void gateway;await page.route('**/api/v1/public/faculties*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,data:{content:[{id:'faculty-cntt',code:'CNTT',name:'CNTT',active:true}]}})}));await page.goto('/register');await page.getByLabel('Mã giảng viên').fill('E2E_NEW_USER');await page.getByLabel('Họ và tên').fill('E2E New User');await page.getByLabel('Email').fill('new-user@example.test');await page.locator('select[name="facultyId"]').selectOption('CNTT');await page.getByLabel('Mật khẩu').first().fill('test-password');await page.getByLabel('Xác nhận mật khẩu').fill('test-password');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Đăng ký tài khoản'}).click();await expect(page).toHaveURL(/registration-pending/);await expect(page.getByRole('status')).toBeVisible()})
test('forgot password reaches OTP and reset screens',async({page,gateway})=>{void gateway;await page.goto('/forgot-password');await page.getByLabel('Mã giảng viên').fill('E2E_USER');await page.getByRole('button',{name:'Gửi mã OTP'}).click();await expect(page).toHaveURL(/verify-otp/);await page.getByLabel('Mã OTP').fill('123456');await page.getByRole('button',{name:'Xác minh'}).click();await expect(page).toHaveURL(/reset-password/);await page.getByLabel('Mật khẩu mới').fill('new-password');await page.getByRole('button',{name:'Đặt lại mật khẩu'}).click();await expect(page).toHaveURL(/login/)})
test('SYSTEM_ADMIN approves a pending registration',async({page,gateway})=>{await gateway.login('SYSTEM_ADMIN');await page.goto('/admin/registrations');await expect(page.getByText('E2E_USER').last()).toBeVisible();await page.getByRole('button',{name:'Duyệt'}).click();await page.getByRole('dialog').getByRole('button',{name:'Duyệt'}).click();await expect(page.getByText('Đang hoạt động')).toBeVisible()})
test('USER creates and submits a question, SUBJECT_ADMIN approves it',async({page,gateway})=>{await gateway.login('USER');await page.goto('/questions/new');await page.getByLabel('Nội dung câu hỏi').fill('E2E question content');await page.getByLabel('Môn học').selectOption(ids.subject);await page.getByLabel('Chương').selectOption(ids.chapter);for(const input of await page.getByLabel('Nội dung phương án').all())await input.fill('Answer content');await page.getByRole('radio').first().check();await page.getByRole('button',{name:'Lưu câu hỏi'}).click();await expect(page).toHaveURL(new RegExp(`/questions/${ids.question}`));await page.getByRole('button',{name:'Gửi duyệt'}).click();await page.getByRole('dialog').getByRole('button',{name:'Gửi duyệt'}).click();const adminPage=await page.context().newPage();await gateway.login('SUBJECT_ADMIN',adminPage);await adminPage.goto(`/review/${ids.question}`);await adminPage.getByRole('button',{name:'Phê duyệt'}).click();await adminPage.getByRole('dialog').getByRole('button',{name:'Phê duyệt'}).click();await expect(adminPage.getByRole('status')).toBeVisible()})
test('notification can be marked read through the UI',async({page,gateway})=>{await gateway.login('USER');await page.goto('/notifications');await expect(page.getByText('Question approved').first()).toBeVisible();await page.getByRole('button',{name:'Chưa đọc: Question approved'}).click();await expect(page.getByText('0 chưa đọc')).toBeVisible()})
test('AI job UI uses deterministic processing fixture',async({page,gateway})=>{await gateway.login('USER');await page.goto(`/ai/jobs/${ids.job}`);await expect(page.getByText(/PROCESSING|COMPLETED/).first()).toBeVisible();await page.reload();await expect(page.getByText(/COMPLETED|Generated question/).first()).toBeVisible()})
test('AI generation requires a document, subject and chapter',async({page,gateway})=>{await gateway.login('USER');await page.goto('/ai/generate');await page.getByLabel('Tài liệu nguồn').selectOption(ids.document);await page.getByLabel('Môn học *').selectOption(ids.subject);await page.getByLabel('Chương *').selectOption(ids.chapter);await page.getByRole('button',{name:'Tạo câu hỏi bằng AI'}).click();await expect(page.getByText('Đã tiếp nhận tác vụ')).toBeVisible()})
test('assistant widget answers and exposes a valid navigation action',async({page,gateway})=>{await gateway.login('USER');await page.getByRole('button',{name:'Mở Trợ lý HAU QM'}).click();await page.getByLabel('Câu hỏi cho trợ lý').fill('Cách tạo câu hỏi từ tài liệu?');await page.getByRole('button',{name:'Gửi câu hỏi'}).click();await expect(page.getByText(/chọn tài liệu, môn học và chương/i)).toBeVisible();await expect(page.getByRole('button',{name:'Mở tạo câu hỏi AI'})).toBeVisible()})
test('admin support chat shows the user display name instead of an id or category',async({page,gateway})=>{await gateway.login('SYSTEM_ADMIN');await page.getByRole('button',{name:'Mở tin nhắn với quản trị viên'}).click();await expect(page.getByText('Nguyễn Văn An')).toBeVisible();await expect(page.getByText('Trao đổi với quản trị viên')).toHaveCount(0);await page.getByText('Nguyễn Văn An').click();await expect(page.getByText('Tôi cần hỗ trợ tạo câu hỏi.')).toBeVisible()})
test('admin dashboard shows Vercel traffic by day, week and month',async({page,gateway})=>{await gateway.login('SYSTEM_ADMIN');await expect(page.getByRole('heading',{name:'Người truy cập website'})).toBeVisible();await expect(page.getByText('Hôm nay')).toBeVisible();await expect(page.getByText('7 ngày gần nhất')).toBeVisible();await expect(page.getByText('Tháng này')).toBeVisible();await expect(page.getByText('14')).toBeVisible();await expect(page.getByText('82')).toBeVisible();await expect(page.getByText('241')).toBeVisible()})
test('system settings uploads a document for AI chunking and shows Cloudinary status',async({page,gateway})=>{await gateway.login('SYSTEM_ADMIN');await page.goto('/admin/settings');await expect(page.getByText('e2e-cloud')).toBeVisible();await page.getByLabel('Tên tài liệu').fill('Quy chế đào tạo');await page.getByLabel('Tệp tài liệu').setInputFiles({name:'quy-che.txt',mimeType:'text/plain',buffer:Buffer.from('Nội dung quy chế.')});await page.getByRole('button',{name:'Tải lên và chunking'}).click();await expect(page.getByText(/chia 3 đoạn tri thức/)).toBeVisible();await expect(page.getByText('3 chunk')).toBeVisible()})
test('exam matrix generate flow reaches generated exam UI',async({page,gateway})=>{await gateway.login('SUBJECT_ADMIN');await page.goto('/exams/generate?matrixId='+ids.matrix);await page.getByLabel('Tên bộ đề').fill('E2E Exam');await page.getByRole('button',{name:'Sinh bộ đề'}).click();await expect(page).toHaveURL(new RegExp(`/exams/${ids.exam}`))})
test('SMTP settings keep configured password private and omit a blank password on save',async({page,gateway})=>{
  await gateway.login('SYSTEM_ADMIN')
  let savedBody
  page.on('request',request=>{if(new URL(request.url()).pathname==='/api/v1/admin/email-settings'&&request.method()==='PUT')savedBody=request.postDataJSON()})
  await page.goto('/admin/settings')
  const password=page.locator('input[name="smtpPassword"]')
  await expect(password).toHaveValue('')
  await expect(page.getByText(/Mật khẩu SMTP đã được cấu hình/)).toBeVisible()
  await expect(password).toHaveAttribute('type','password')
  await page.locator('.email-settings-card').getByRole('button',{name:'Hiện mật khẩu'}).click()
  await expect(password).toHaveAttribute('type','text')
  await page.locator('.email-settings-card').getByRole('button',{name:'Lưu cấu hình'}).click()
  await expect.poll(()=>savedBody).toBeTruthy()
  expect(savedBody).not.toHaveProperty('smtpPassword')
  expect(savedBody).not.toHaveProperty('passwordConfigured')
})
test('Gmail security selects recommended ports and blocks SSL_TLS on 587',async({page,gateway})=>{
  await gateway.login('SYSTEM_ADMIN')
  await page.goto('/admin/settings')
  const security=page.getByLabel('Bảo mật')
  const port=page.locator('input[name="smtpPort"]')
  await security.selectOption('SSL_TLS')
  await expect(port).toHaveValue('465')
  await security.selectOption('STARTTLS')
  await expect(port).toHaveValue('587')
  await security.selectOption('SSL_TLS')
  await port.fill('587')
  await expect(page.getByText('Gmail cổng 587 sử dụng STARTTLS. SSL/TLS sử dụng cổng 465.')).toBeVisible()
  await expect(page.locator('.email-settings-card').getByRole('button',{name:'Lưu cấu hình'})).toBeDisabled()
  await expect(page.getByRole('button',{name:'Gửi email kiểm tra'})).toBeDisabled()
})
test('SMTP test endpoint success stays on settings page',async({page,gateway})=>{
  await gateway.login('SYSTEM_ADMIN')
  await page.goto('/admin/settings')
  await page.locator('input[name="testRecipient"]').fill('recipient@example.test')
  await page.getByRole('button',{name:'Gửi email kiểm tra'}).click()
  await expect(page.getByRole('status')).toHaveText('Email kiểm tra đã được gửi thành công.')
  await expect(page).toHaveURL(/admin\/settings/)
})
test('contact reply failure keeps the loaded list and shows an action error',async({page,gateway})=>{
  await gateway.login('SYSTEM_ADMIN')
  await page.goto('/admin/contact')
  await expect(page.getByText('Nguyễn Văn A')).toBeVisible()
  await page.getByRole('button',{name:'Xem chi tiết'}).click()
  await page.getByLabel('Phản hồi').fill('Nội dung phản hồi')
  await page.getByRole('dialog').getByRole('button',{name:'Gửi phản hồi'}).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toHaveText('Không thể gửi email.')
  await expect(page.getByRole('cell',{name:'Nguyễn Văn A'})).toBeVisible()
})
