import {test,expect,ids} from './fixtures.js'

test('subject admin opens, sends and reloads one direct conversation with a user',async({page,gateway})=>{
  await gateway.login('SUBJECT_ADMIN')
  await page.getByRole('button',{name:'Mở tin nhắn'}).click()
  const newContact=page.locator('.human-chat-contacts button').filter({hasText:'Nguyễn Văn An'})
  await expect(newContact).toBeVisible()
  await newContact.click()
  await expect(page.locator('.human-chat-conversation-head')).toContainText('Nguyễn Văn An')
  expect(gateway.conversationCreates()).toBe(1)

  await page.getByLabel('Nhập tin nhắn').fill('Kiểm tra direct chat')
  await page.getByRole('button',{name:'Gửi',exact:true}).click()
  await expect(page.getByText('Tin nhắn kiểm thử')).toBeVisible()

  await page.reload()
  await page.getByRole('button',{name:'Mở tin nhắn'}).click()
  await expect(page.locator('.human-chat-list').getByText('Nguyễn Văn An')).toBeVisible()
  await page.locator('.human-chat-list button').filter({hasText:'Nguyễn Văn An'}).click()
  await expect(page.locator('.human-chat-conversation-head')).toContainText('Nguyễn Văn An')
  await expect(page.getByText('Tin nhắn kiểm thử')).toBeVisible()
  expect(gateway.conversationCreates()).toBe(1)
  expect(ids.conversation).toBe('00000000-0000-0000-0000-000000000090')
})

test('user resolves the existing direct conversation with a subject admin',async({page,gateway})=>{
  await gateway.login('USER')
  await page.getByRole('button',{name:'Mở tin nhắn'}).click()
  const subjectAdmin=page.locator('.human-chat-contacts button').filter({hasText:'ThS Nguyễn Văn A'})
  await expect(subjectAdmin).toBeVisible()
  await subjectAdmin.click()
  await expect(page.locator('.human-chat-conversation-head')).toContainText('ThS Nguyễn Văn A')
  await expect(page.getByText('Tôi cần hỗ trợ tạo câu hỏi.')).toBeVisible()
  expect(gateway.conversationCreates()).toBe(0)
})

test('theme, cursor and Kute preferences apply immediately and persist',async({page,gateway})=>{
  await gateway.login('USER')
  await page.getByLabel('Mở menu tài khoản').click()
  await page.getByRole('button',{name:'Cài đặt giao diện'}).click()
  await page.getByRole('radio',{name:'Tối'}).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await page.getByRole('radio',{name:'Sáng'}).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme','light')
  await page.emulateMedia({colorScheme:'dark'})
  await page.getByRole('radio',{name:'Tự động'}).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await page.emulateMedia({colorScheme:'light'})
  await expect(page.locator('html')).toHaveAttribute('data-theme','light')

  await page.getByRole('button',{name:'Hiệu ứng con trỏ'}).click()
  await page.getByRole('radio',{name:'Sao nhỏ'}).click()
  await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('hau-qm-ui-preferences-v1')).cursorEffect)).toBe('stars')

  const kuteSwitch=page.getByRole('switch',{name:'Hiển thị Trợ lý Kute'})
  await expect(kuteSwitch).toHaveAttribute('aria-checked','true')
  await kuteSwitch.click()
  await expect(page.getByRole('button',{name:'Mở Trợ lý Kute'})).toBeHidden()
  await page.reload()
  await expect(page.getByRole('button',{name:'Mở Trợ lý Kute'})).toBeHidden()
  await page.getByLabel('Mở menu tài khoản').click()
  await page.getByRole('switch',{name:'Hiển thị Trợ lý Kute'}).click()
  await expect(page.getByRole('button',{name:'Mở Trợ lý Kute'})).toBeVisible()
})

test('reduced motion prevents cursor animation setup',async({page,gateway})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await gateway.login('USER')
  await page.getByLabel('Mở menu tài khoản').click()
  await page.getByRole('button',{name:'Hiệu ứng con trỏ'}).click()
  await page.getByRole('radio',{name:'Hạt'}).click()
  await expect(page.locator('.cursor-effects')).toHaveJSProperty('width',300)
  await expect(page.locator('.cursor-effects')).toHaveJSProperty('height',150)
})
