ALTER TABLE telegram_bot_settings ADD COLUMN last_checked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE telegram_connections ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE telegram_connections ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
