spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${QUESTION_DB_URL:jdbc:postgresql://postgres:5432/question_db}
    username: ${QUESTION_DB_USERNAME}
    password: ${QUESTION_DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI}

ai:
  service:
    url: ${AI_SERVICE_URL:http://ai-service:8085}
  internal:
    result-token: ${INTERNAL_SERVICE_TOKEN}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}
