package com.hau.ai.application.service;
import com.hau.ai.application.port.out.*;import com.hau.ai.domain.exception.*;import com.hau.ai.domain.model.*;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class AiJobProcessor{
 private final AiJobRepository jobs;private final DocumentRepository docs;private final StoragePort storage;private final TextExtractor extractor;private final AiProvider provider;private final AiResultRepository results;private final ProcessedEventRepository inbox;private final AiEventPublisher events;private final StructuredOutputValidator validator;private final Clock clock;
 public AiJobProcessor(AiJobRepository j,DocumentRepository d,StoragePort s,TextExtractor x,AiProvider p,AiResultRepository r,ProcessedEventRepository i,AiEventPublisher e,StructuredOutputValidator v,Clock c){jobs=j;docs=d;storage=s;extractor=x;provider=p;results=r;inbox=i;events=e;validator=v;clock=c;}
 @Transactional public void process(UUID eventId,UUID jobId,UUID correlation){if(inbox.exists(eventId))return;var job=jobs.findById(jobId).orElseThrow(()->new NotFoundException("AI job not found"));if(job.status()==JobStatus.COMPLETED||job.status()==JobStatus.FAILED){inbox.record(eventId,"AI_GENERATION_REQUESTED");return;}if(job.status()==JobStatus.PENDING){job.start(Instant.now(clock));jobs.save(job);}String source="";if(job.documentId()!=null){var d=docs.findById(job.documentId()).orElseThrow(()->new NotFoundException("Document not found"));source=extractor.extract(d.contentType(),storage.read(d.storageKey()));}try{String raw=switch(job.type()){case QUESTION_GENERATION->provider.generateQuestions(source,job.requestJson());case ANALYSIS->provider.analyze(source,job.requestJson());case CHAT->provider.chat(source,job.requestJson());};String valid=job.type()==JobType.QUESTION_GENERATION?validator.validateQuestions(raw):validateTextJson(raw);String ref=results.save(job.id(),valid);job.complete(ref,Instant.now(clock));jobs.save(job);inbox.record(eventId,"AI_GENERATION_REQUESTED");events.completed(job,correlation);}catch(ProviderException e){if(e.retryable())throw e;fail(job,"PROVIDER_FAILURE",e.getMessage(),correlation);inbox.record(eventId,"AI_GENERATION_REQUESTED");}catch(InvalidAiOutputException e){fail(job,"INVALID_AI_OUTPUT",e.getMessage(),correlation);inbox.record(eventId,"AI_GENERATION_REQUESTED");}}
 @Transactional public void failAfterRetries(UUID eventId,UUID jobId,UUID correlation,String message){if(inbox.exists(eventId))return;var j=jobs.findById(jobId).orElseThrow(()->new NotFoundException("AI job not found"));if(j.status()!=JobStatus.COMPLETED&&j.status()!=JobStatus.FAILED)fail(j,"PROVIDER_RETRY_EXHAUSTED",message,correlation);inbox.record(eventId,"AI_GENERATION_REQUESTED");}
 private void fail(AiJob j,String c,String m,UUID correlation){j.fail(c,m,Instant.now(clock));jobs.save(j);events.failed(j,correlation);}private String validateTextJson(String raw){try{var n=new tools.jackson.databind.ObjectMapper().readTree(raw);if(n==null||!n.isObject())throw new InvalidAiOutputException("AI result must be JSON object");return n.toString();}catch(InvalidAiOutputException e){throw e;}catch(Exception e){throw new InvalidAiOutputException("Malformed AI JSON",e);}}
}
