import { Link } from 'react-router-dom'
import { PublicLayout } from '../../components/layout/PublicLayout'

const pages={
  '/gioi-thieu':{title:'Giới thiệu HAU Exam',eyebrow:'VỀ HAU EXAM',description:'Giới thiệu HAU Exam, hệ thống hỗ trợ quản lý ngân hàng câu hỏi và đề thi trắc nghiệm tại Trường Đại học Kiến trúc Hà Nội.',body:['HAU Exam / HAU QM là hệ thống hỗ trợ hoạt động chuyên môn trong việc tạo, quản lý, phê duyệt câu hỏi và xây dựng đề thi trắc nghiệm.','Hệ thống được định hướng cho giảng viên, quản trị viên chuyên môn và quản trị viên hệ thống; phân quyền theo vai trò và phạm vi khoa.']},
  '/tinh-nang':{title:'Tính năng HAU Exam',eyebrow:'NĂNG LỰC HỆ THỐNG',description:'Các tính năng HAU Exam cho ngân hàng câu hỏi, AI hỗ trợ, phê duyệt chuyên môn, ma trận và quản lý đề thi.',body:['HAU Exam hỗ trợ ngân hàng câu hỏi có cấu trúc, học liệu, quy trình phê duyệt, thông báo và trao đổi.','Các tính năng AI chỉ đóng vai trò trợ lý; nội dung vẫn cần được người dùng và quản trị viên chuyên môn kiểm tra.']},
  '/ngan-hang-cau-hoi':{title:'Ngân hàng câu hỏi trắc nghiệm | HAU Exam',eyebrow:'NGÂN HÀNG CÂU HỎI',description:'Tìm hiểu cách HAU Exam tổ chức Subject, Chapter, Topic, mức độ, hình ảnh, AI hỗ trợ và phê duyệt câu hỏi.',body:['Ngân hàng câu hỏi được tổ chức theo Subject, Chapter, Topic và mức độ để dễ tìm kiếm, phân loại và tái sử dụng trong ma trận đề.','Câu hỏi có thể được tạo thủ công hoặc với AI hỗ trợ, sau đó gửi qua quy trình review. Trang công khai này không hiển thị dữ liệu câu hỏi riêng tư.']},
  '/quan-ly-de-thi':{title:'Quản lý ngân hàng đề thi trắc nghiệm | HAU Exam',eyebrow:'QUẢN LÝ ĐỀ THI',description:'Tìm hiểu ma trận, phân bố câu hỏi đã duyệt, tạo đề và quản lý phiên bản trong HAU Exam.',body:['Exam Service hỗ trợ xây dựng ma trận theo chương và độ khó, chọn câu hỏi đã được phê duyệt và tạo bộ đề.','Người dùng có thể quản lý phiên bản và xuất đề khi chức năng được bật trong hệ thống. HAU Exam không phải nền tảng tổ chức thi trực tuyến.']},
  '/huong-dan':{title:'Hướng dẫn sử dụng | HAU Exam',eyebrow:'HƯỚNG DẪN',description:'Hướng dẫn tổng quan cách sử dụng HAU Exam cho tài khoản, ngân hàng câu hỏi, AI và đề thi.',body:['Bắt đầu bằng đăng nhập hoặc đăng ký tài khoản. Sau khi được phê duyệt, giảng viên có thể tạo câu hỏi, upload học liệu và theo dõi trạng thái.','Quản trị viên chuyên môn thực hiện review trong phạm vi khoa; quản trị viên hệ thống quản lý tài khoản, vai trò và cấu hình cấp hệ thống.']}
}
export function PublicFeaturePage({path}){const page=pages[path]||pages['/gioi-thieu'];return <PublicLayout seo={{title:page.title,description:page.description,path,image:'/src/assets/banner.jpg'}}><article className="public-info-card public-feature-page"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1>{page.body.map(text=><p key={text}>{text}</p>)}<div className="public-actions"><Link className="button button-primary" to="/login">Đăng nhập</Link><Link className="button button-secondary" to="/">Về trang chủ</Link></div></article></PublicLayout>}
