package com.notificationservice.presentation.controller;
import com.notificationservice.application.service.SupportChatService; import com.notificationservice.domain.model.SupportStatus; import com.notificationservice.presentation.request.SupportRequests; import com.notificationservice.presentation.response.*; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.util.*;
@RestController public class SupportChatController {private final SupportChatService service; public SupportChatController(SupportChatService s){service=s;}
 @PreAuthorize("hasAnyRole('USER','SUBJECT_ADMIN')") @PostMapping("/api/v1/support/conversations") public ResponseEntity<ApiResponse<SupportResponses.Conversation>> create(@AuthenticationPrincipal Jwt j,@Valid @RequestBody SupportRequests.CreateConversation r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(service.create(user(j),role(j),j.getClaimAsString("facultyId"),r.subject(),r.content(),r.recipientUserId())));}
 @PreAuthorize("hasAnyRole('USER','SUBJECT_ADMIN')") @GetMapping("/api/v1/support/conversations/my") public ApiResponse<?> mine(@AuthenticationPrincipal Jwt j,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return ApiResponse.success(service.listMine(user(j),page,size));}
 @PreAuthorize("hasRole('SUBJECT_ADMIN')") @GetMapping("/api/v1/support/conversations/assigned") public ApiResponse<?> assigned(@AuthenticationPrincipal Jwt j,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return ApiResponse.success(service.listAssigned(user(j),j.getClaimAsString("facultyId"),page,size));}
 @GetMapping("/api/v1/support/conversations/{id}") public ApiResponse<?> get(@AuthenticationPrincipal Jwt j,@PathVariable UUID id){return ApiResponse.success(service.getConversation(id,user(j),role(j),j.getClaimAsString("facultyId")));}
 @GetMapping("/api/v1/support/conversations/{id}/messages") public ApiResponse<?> history(@AuthenticationPrincipal Jwt j,@PathVariable UUID id,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="30")int size){return ApiResponse.success(service.history(id,user(j),role(j),j.getClaimAsString("facultyId"),page,size));}
 @PostMapping(value="/api/v1/support/conversations/{id}/messages",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<ApiResponse<SupportResponses.Message>> send(@AuthenticationPrincipal Jwt j,@PathVariable UUID id,@RequestPart(value="content",required=false)String content,@RequestPart(value="file",required=false)MultipartFile file){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(service.send(id,user(j),role(j),j.getClaimAsString("facultyId"),content,file)));}
 @PatchMapping("/api/v1/support/conversations/{id}/read") public ApiResponse<Integer> read(@AuthenticationPrincipal Jwt j,@PathVariable UUID id){return ApiResponse.success(service.markRead(id,user(j),role(j),j.getClaimAsString("facultyId")));}
 @GetMapping("/api/v1/support/unread-count") public ApiResponse<Long> unread(@AuthenticationPrincipal Jwt j){return ApiResponse.success(service.unread(user(j),role(j),j.getClaimAsString("facultyId")));}
 @PreAuthorize("hasRole('SYSTEM_ADMIN')") @GetMapping("/api/v1/admin/support/conversations") public ApiResponse<?> admins(@AuthenticationPrincipal Jwt j,@RequestParam(required=false)SupportStatus status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return ApiResponse.success(service.listAdmin(status,page,size));}
 @PreAuthorize("hasRole('SYSTEM_ADMIN')") @PatchMapping("/api/v1/admin/support/conversations/{id}/status") public ApiResponse<?> status(@AuthenticationPrincipal Jwt j,@PathVariable UUID id,@Valid @RequestBody SupportRequests.Status r){return ApiResponse.success(service.status(id,user(j),r.status()));}
 @PreAuthorize("hasRole('SYSTEM_ADMIN')") @PostMapping(value="/api/v1/admin/support/conversations/{id}/messages",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<ApiResponse<SupportResponses.Message>> adminSend(@AuthenticationPrincipal Jwt j,@PathVariable UUID id,@RequestPart(value="content",required=false)String content,@RequestPart(value="file",required=false)MultipartFile file){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(service.send(id,user(j),role(j),null,content,file)));}
 private UUID user(Jwt j){return UUID.fromString(j.getSubject());} private String role(Jwt j){return j.getClaimAsString("role");}
}
