import {useEffect,useState} from 'react'
import {Link,useParams,useSearchParams} from 'react-router-dom'
import {Button,Icon,Loading} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {QuestionPreview} from '../../questions/components/QuestionPreview'
import {questionsApi} from '../../questions/api/questionsApi'
import {formatDateTime} from '../../questions/model/questionModel'
import {notificationStore} from '../../notifications/store/notificationStore'
import {examsApi} from '../api/examsApi'
import {useExamResource} from '../hooks/useExamResource'
import {ExamError} from '../components/ExamError'
import {Info} from './MatrixPages'

export function ExamDetailPage(){const {id}=useParams();return <ExamDetail key={id} id={id}/>}

function ExamDetail({id}){
  const {data,loading,error,reload}=useExamResource('exam',id);const [params,setParams]=useSearchParams();const [failure,setFailure]=useState(null);const [exporting,setExporting]=useState('');const [catalog,setCatalog]=useState({matrix:null,subjects:[],chapters:[]})
  useEffect(()=>{let active=true;if(data)Promise.all([examsApi.matrix(data.matrixId),questionsApi.subjects(),questionsApi.chapters(data.subjectId)]).then(([matrix,subjects,chapters])=>{if(active)setCatalog({matrix,subjects,chapters})}).catch(()=>{});return()=>{active=false}},[data])
  if(loading)return <Loading label="Đang tải bộ đề"/>;if(error)return <ExamError error={error} onRetry={reload}/>
  const versions=[...(data.versions||[])].sort((a,b)=>code(a)-code(b));const selectedCode=Number(params.get('version'));const chosen=versions.find(item=>code(item)===selectedCode)||versions[0];const subjectName=catalog.subjects.find(subject=>subject.id===data.subjectId)?.name||'Đang cập nhật';const rules=new Map((catalog.matrix?.rules||[]).map(rule=>[rule.id,rule]));const total=chosen?.questionCount??chosen?.questions?.length??0
  async function download(version,type){const key=`${version}-${type}`;setExporting(key);setFailure(null);try{const blob=await examsApi.downloadPdf(id,version,type);save(blob,`${data.examCode}_${version}${type==='ANSWER_KEY'?'_Answer_Key':''}.pdf`);notificationStore.pushToast({title:'Đã xuất PDF',content:`Mã đề ${version} đã được tải xuống.`})}catch(reason){setFailure(reason)}finally{setExporting('')}}
  async function downloadAll(){setExporting('all');setFailure(null);try{save(await examsApi.downloadAll(id),'All_Exam_Versions.zip');notificationStore.pushToast({title:'Đã xuất tất cả mã đề',content:'Tệp ZIP đã được tải xuống.'})}catch(reason){setFailure(reason)}finally{setExporting('')}}
  return <section><PageHeader title={data.name} description="Các mã đề đã lưu, ma trận và tệp xuất có thể tái lập." actions={<Button variant="secondary" loading={exporting==='all'} onClick={downloadAll}><Icon name="download"/> Xuất tất cả mã đề</Button>}/><section className="editor-section"><dl className="exam-metadata"><Info label="Tên đề" value={data.name}/><Info label="Mã quản lý" value={data.examCode}/><Info label="Môn học" value={subjectName}/><Info label="Thời lượng" value={`${data.durationMinutes} phút`}/><Info label="Số câu/mã" value={total}/><Info label="Khoảng mã đề" value={`${data.versionStartCode}–${data.versionEndCode}`}/><Info label="Ngày tạo" value={formatDateTime(data.createdAt)}/><Info label="Ma trận" value={<Link to={'/exam-matrices/'+data.matrixId}>{catalog.matrix?.name||'Xem ma trận'}</Link>}/></dl>{data.reuse?.warning&&<p className="capacity-warning"><Icon name="info"/> {data.reuse.warningMessage} Tỷ lệ dùng lại: {data.reuse.reuseRate}%.</p>}</section>{failure&&<ExamError error={failure}/>}<section className="editor-section exam-versions"><h2>Các mã đề</h2><div className="version-list">{versions.map(version=><article className={chosen?.id===version.id?'version-card version-card-active':'version-card'} key={version.id}><button type="button" onClick={()=>setParams({version:String(code(version))})}><strong>{code(version)}</strong><span>{version.questionCount??version.questions.length} câu · {version.matrixValid?'Ma trận hợp lệ':'Cần kiểm tra'}</span><small>{formatDateTime(version.createdAt)} · Trùng tối đa {version.maxOverlapRate||0}%</small></button><div><Button variant="secondary" loading={exporting===`${code(version)}-STUDENT_EXAM`} onClick={()=>download(code(version),'STUDENT_EXAM')}>Xuất PDF</Button><Button variant="secondary" loading={exporting===`${code(version)}-ANSWER_KEY`} onClick={()=>download(code(version),'ANSWER_KEY')}>Đáp án</Button></div></article>)}</div></section>{chosen&&<section className="editor-section"><h2>Mã đề {code(chosen)}</h2><p><Icon name="check" variant="success"/> {chosen.questionCount??chosen.questions.length} câu · ma trận hợp lệ · seed {chosen.generationSeed}</p><ol className="exam-questions">{[...chosen.questions].sort((a,b)=>a.position-b.position).map(reference=><QuestionReference key={reference.id} reference={reference} rule={rules.get(reference.matrixRuleId)}/>)}</ol></section>}</section>
}

function QuestionReference({reference,rule}){const [open,setOpen]=useState(false);const [state,setState]=useState({});function toggle(){const next=!open;setOpen(next);if(next&&!state.question&&!state.loading){setState({loading:true});questionsApi.get(reference.questionId).then(question=>setState({question})).catch(error=>setState({error}))}}return <li><div className="exam-question-heading"><strong>Câu {reference.position}</strong><span>{rule?.difficulty||'—'}</span><Button variant="secondary" aria-expanded={open} onClick={toggle}>{open?'Thu gọn':'Xem nội dung'}</Button></div>{open&&<div className="exam-question-preview">{state.loading?<Loading label="Đang tải câu hỏi"/>:state.error?<ExamError error={state.error}/>:<QuestionPreview question={state.question}/>}</div>}</li>}
function code(version){return version.versionCode??version.version}
function save(blob,filename){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
