import {useEffect,useRef,useState} from 'react'
import {Link,useParams,useSearchParams} from 'react-router-dom'
import {Button,ConfirmDialog,Loading} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {QuestionPreview} from '../../questions/components/QuestionPreview'
import {questionsApi} from '../../questions/api/questionsApi'
import {formatDateTime} from '../../questions/model/questionModel'
import {examsApi} from '../api/examsApi'
import {useExamResource} from '../hooks/useExamResource'
import {ExamError} from '../components/ExamError'
import {Info} from './MatrixPages'
import {notificationStore} from '../../notifications/store/notificationStore'
import {useAuth} from '../../auth/hooks/useAuth'
import {formatAcademicName} from '../../users/model/academic'
export function ExamDetailPage(){const {id}=useParams();return <ExamDetail key={id} id={id}/>}
function ExamDetail({id}){const {data,loading,error,reload,setData}=useExamResource('exam',id);const {currentUser}=useAuth();const [params,setParams]=useSearchParams();const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);const [failure,setFailure]=useState(null);const [catalog,setCatalog]=useState({matrix:null,subjects:[],chapters:[]});const lock=useRef(false)
 useEffect(()=>{let active=true;if(data)Promise.all([examsApi.matrix(data.matrixId),questionsApi.subjects(),questionsApi.chapters(data.subjectId)]).then(([matrix,subjects,chapters])=>{if(active)setCatalog({matrix,subjects,chapters})}).catch(()=>{});return()=>{active=false}},[data])
 async function regenerate(){if(lock.current)return;lock.current=true;setBusy(true);setFailure(null);try{const result=await examsApi.version(id);setData(result);setParams({version:String(Math.max(...result.versions.map(v=>v.version)))});notificationStore.pushToast({title:'Đã tạo phiên bản đề',content:'Phiên bản mới đã được sinh thành công.'})}catch(reason){setFailure(reason)}finally{lock.current=false;setBusy(false);setConfirm(false)}}
 async function download(version){try{const blob=await examsApi.downloadPdf(id,version);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='exam-'+id+'-v'+version+'.pdf';document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);notificationStore.pushToast({title:'Đã xuất đề PDF',content:'Tệp PDF đã được tải xuống.'})}catch(reason){setFailure(reason)}}
 if(loading)return <Loading label="Đang tải bộ đề"/>;if(error)return <ExamError error={error} onRetry={reload}/>;if(failure?.status===403)return <ExamError error={failure}/>;const versions=[...data.versions].sort((a,b)=>b.version-a.version);const chosen=params.has('version')?versions.find(v=>v.version===Number(params.get('version'))):versions[0]
 const subjectName=catalog.subjects.find(subject=>subject.id===data.subjectId)?.name||'Đang cập nhật';const chapterMap=new Map(catalog.chapters.map(chapter=>[chapter.id,chapter.name]));const rules=new Map((catalog.matrix?.rules||[]).map(rule=>[rule.id,rule]));const chapterCounts=new Map(),difficultyCounts=new Map();for(const reference of chosen?.questions||[]){const rule=rules.get(reference.matrixRuleId);if(!rule)continue;chapterCounts.set(rule.chapterId,(chapterCounts.get(rule.chapterId)||0)+1);difficultyCounts.set(rule.difficulty,(difficultyCounts.get(rule.difficulty)||0)+1)}const total=chosen?.questions?.length||0;const creator=data.createdBy===currentUser?.id?formatAcademicName(currentUser):'Giảng viên trong khoa'
 return <section><PageHeader title={data.name} description="Thông tin đề thi, phân bố câu hỏi và lịch sử phiên bản." actions={<><Button variant="secondary" disabled={!chosen} onClick={()=>chosen&&download(chosen.version)}>Xuất PDF</Button><Button disabled={busy} onClick={()=>setConfirm(true)}>Tạo phiên bản mới</Button></>}/><section className="editor-section"><dl className="exam-metadata"><Info label="Tên đề" value={data.name}/><Info label="Mã đề" value={data.examCode}/><Info label="Môn học" value={subjectName}/><Info label="Thời lượng" value={`${data.durationMinutes} phút`}/><Info label="Số câu" value={total}/><Info label="Người tạo" value={creator}/><Info label="Ngày tạo" value={formatDateTime(data.createdAt)}/><Info label="Phiên bản" value={chosen?.version||'—'}/><Info label="Ma trận" value={<Link to={'/exam-matrices/'+data.matrixId}>{catalog.matrix?.name||'Xem ma trận'}</Link>}/></dl></section>{chosen&&<section className="exam-distribution-grid"><article className="surface exam-distribution"><h2>Phân bố theo chương</h2>{[...chapterCounts].map(([chapterId,count])=><div key={chapterId}><span>{chapterMap.get(chapterId)||'Chương chưa đặt tên'}</span><strong>{count} câu</strong></div>)}</article><article className="surface exam-distribution"><h2>Mức độ</h2>{[['EASY','Dễ'],['MEDIUM','Trung bình'],['HARD','Khó']].map(([key,label])=><div key={key}><span>{label}</span><strong>{total?Math.round((difficultyCounts.get(key)||0)*100/total):0}%</strong></div>)}</article></section>}{failure&&<ExamError error={failure}/>}<section className="editor-section exam-versions"><h2>Danh sách câu hỏi</h2><div className="version-tabs" aria-label="Chọn phiên bản">{versions.map(v=><Button variant={chosen?.id===v.id?'primary':'secondary'} key={v.id} aria-pressed={chosen?.id===v.id} onClick={()=>setParams({version:String(v.version)})}>Phiên bản {v.version} · {v.questions.length} câu</Button>)}</div>{chosen?<><p>Sinh lúc <strong>{formatDateTime(chosen.createdAt)}</strong> · Phiên bản {chosen.version}</p><ol className="exam-questions" key={chosen.id}>{[...chosen.questions].sort((a,b)=>a.position-b.position).map(reference=><QuestionReference key={reference.id} reference={reference}/>)}</ol></>:<p role="status">Không tìm thấy phiên bản được yêu cầu.</p>}</section><ConfirmDialog open={confirm} title="Tạo phiên bản mới?" description="Backend sẽ chọn câu hỏi theo ma trận hiện tại và lưu thêm phiên bản." confirmLabel="Tạo phiên bản" loading={busy} onConfirm={regenerate} onClose={event=>{if(busy){event?.preventDefault();return}setConfirm(false)}}/></section>}
function QuestionReference({reference}){const [open,setOpen]=useState(false);const [state,setState]=useState({loading:true});const [attempt,setAttempt]=useState(0);useEffect(()=>{let active=true;if(open)questionsApi.get(reference.questionId).then(question=>{if(active)setState({question})}).catch(error=>{if(active)setState({error})});return()=>{active=false}},[open,reference.questionId,attempt]);return <li><div className="exam-question-heading"><strong>Câu {reference.position}</strong><Link to={'/questions/'+reference.questionId}>{reference.questionId}</Link><Button variant="secondary" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>{open?'Thu gọn':'Xem nội dung'}</Button></div><small>Quy tắc ma trận: {reference.matrixRuleId}</small>{open&&<div className="exam-question-preview">{state.loading?<Loading label="Đang tải câu hỏi"/>:state.error?<ExamError error={state.error} onRetry={()=>{setState({loading:true});setAttempt(v=>v+1)}}/>:<QuestionPreview question={state.question}/>}</div>}</li>}
