spring:
  config:
    activate:
      on-profile: docker

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}
