package com.examservice.application.service;
import com.examservice.application.port.out.*;import com.examservice.domain.exception.*;import com.examservice.domain.model.*;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.beans.factory.annotation.Autowired;
@Service public class ExamGenerationService{
 private final ExamRepository exams;private final ExamMatrixRepository matrices;private final ExamTemplateRepository templates;private final QuestionCatalogPort questions;private final ExamEventPublisher events;private final Clock clock;
 @Autowired public ExamGenerationService(ExamRepository e,ExamMatrixRepository m,ExamTemplateRepository t,QuestionCatalogPort q,ExamEventPublisher p,Clock c){exams=e;matrices=m;templates=t;questions=q;events=p;clock=c;}
 public ExamGenerationService(ExamRepository e,ExamMatrixRepository m,ExamTemplateRepository t,QuestionCatalogPort q,Clock c){this(e,m,t,q,(exam,user)->{},c);}
 @Transactional public Exam generate(String name,UUID matrixId,UUID templateId,Actor a){var matrix=matrices.findById(matrixId).orElseThrow(()->new NotFoundException("Exam matrix not found"));MatrixService.scope(a,matrix.facultyId());if(templateId!=null){var t=templates.findById(templateId).orElseThrow(()->new NotFoundException("Exam template not found"));if(!t.matrixId().equals(matrixId))throw new InvalidMatrixException("Template belongs to another matrix");}Instant now=Instant.now(clock);var result=exams.save(new Exam(UUID.randomUUID(),name,matrix.facultyId(),matrix.subjectId(),matrix.id(),templateId,a.userId(),List.of(select(matrix,1,a.bearerToken(),now)),now,now));events.generated(result,a.userId());return result;}
 @Transactional public Exam regenerate(UUID examId,Actor a){var exam=get(examId,a);var matrix=matrices.findById(exam.matrixId()).orElseThrow(()->new NotFoundException("Exam matrix not found"));int n=exam.versions().stream().mapToInt(ExamVersion::versionNumber).max().orElse(0)+1;var versions=new ArrayList<>(exam.versions());versions.add(select(matrix,n,a.bearerToken(),Instant.now(clock)));return exams.save(new Exam(exam.id(),exam.name(),exam.facultyId(),exam.subjectId(),exam.matrixId(),exam.templateId(),exam.createdBy(),versions,exam.createdAt(),Instant.now(clock)));}
 @Transactional(readOnly=true) public List<Exam> list(Actor a){MatrixService.role(a);return exams.findByFaculty(a.facultyId());}
 @Transactional(readOnly=true) public Exam get(UUID id,Actor a){var e=exams.findById(id).orElseThrow(()->new NotFoundException("Exam not found"));MatrixService.scope(a,e.facultyId());return e;}
 private ExamVersion select(ExamMatrix m,int version,String token,Instant now){Set<UUID>used=new HashSet<>();List<ExamQuestionReference>refs=new ArrayList<>();int pos=1;for(var rule:m.rules()){var candidates=questions.approvedQuestions(m.facultyId(),m.subjectId(),rule.chapterId(),rule.topicId(),rule.difficulty(),token).stream().filter(q->"APPROVED".equals(q.status())&&m.facultyId().equals(q.facultyId())&&m.subjectId().equals(q.subjectId())&&rule.chapterId().equals(q.chapterId())&&Objects.equals(rule.topicId(),q.topicId())&&rule.difficulty()==q.difficulty()).filter(q->!used.contains(q.id())).sorted(Comparator.comparing(q->q.id().toString())).toList();if(candidates.size()<rule.questionCount())throw new InsufficientQuestionsException("Insufficient APPROVED questions for chapter="+rule.chapterId()+", topic="+rule.topicId()+", difficulty="+rule.difficulty()+": required="+rule.questionCount()+", available="+candidates.size());for(var q:candidates.subList(0,rule.questionCount())){used.add(q.id());refs.add(new ExamQuestionReference(UUID.randomUUID(),q.id(),pos++,rule.id()));}}if(refs.size()!=m.totalQuestions())throw new InvalidMatrixException("Generated version count is inconsistent with matrix");return new ExamVersion(UUID.randomUUID(),version,refs,now);}
}
