import {useCallback,useEffect,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {DataTable,Loading,StatusBadge} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {routes} from '../../../constants/routes'
import {facultiesApi} from '../api/facultiesApi'
import {usersApi} from '../api/usersApi'
import {normalizePage,formatDateTime} from '../model/userModel'
export function FacultyDetailPage(){const{id}=useParams();const[faculty,setFaculty]=useState(null);const[users,setUsers]=useState(null);const[error,setError]=useState(null);const load=useCallback(async()=>{try{const f=await facultiesApi.list({page:0,size:100});const current=f.content?.find(item=>item.id===id)||await facultiesApi.get(id);setFaculty(current);setUsers(normalizePage(await usersApi.list({facultyId:current.code,page:0,size:20})))}catch(e){setError(e)}},[id]);useEffect(()=>{const timer=setTimeout(load,0);return()=>clearTimeout(timer)},[load]);if(error)return <section><PageHeader title="Faculty detail"/><div className="surface admin-error"><p>{error.message}</p></div></section>;if(!faculty||!users)return <section><PageHeader title="Faculty detail"/><div className="surface admin-loading"><Loading label="Loading faculty"/></div></section>;const admins=users.items.filter(user=>user.role==='SUBJECT_ADMIN');return <section><PageHeader title={faculty.name} description={faculty.description||'Faculty scope and lecturer management.'} actions={<Link className="button button-secondary" to={routes.faculties}>Back to faculties</Link>}/><div className="faculty-detail-head"><div className="faculty-code">{faculty.code.slice(0,2)}</div><div><span className="mono">{faculty.code}</span><h2>{faculty.name}</h2><StatusBadge status={faculty.active?'ACTIVE':'DISABLED'}/></div></div><div className="admin-kpi-grid faculty-kpis"><div className="admin-kpi"><small>Total lecturers</small><strong>{users.totalElements}</strong></div><div className="admin-kpi"><small>Subject admins</small><strong>{admins.length}</strong></div><div className="admin-kpi"><small>Subjects</small><strong>—</strong><span>API chưa hỗ trợ aggregate</span></div><div className="admin-kpi"><small>Question bank</small><strong>—</strong><span>API chưa hỗ trợ aggregate</span></div></div><section className="surface admin-panel"><header><div><span className="eyebrow">FACULTY MEMBERS</span><h2>Giảng viên thuộc Khoa</h2></div><span className="result-count">{users.totalElements} kết quả</span></header><DataTable rows={users.items} emptyTitle="Chưa có giảng viên thuộc Khoa." columns={[{key:'lecturerCode',header:'Mã GV',render:u=><span className="mono">{u.lecturerCode}</span>},{key:'fullName',header:'Họ và tên'},{key:'email',header:'Email'},{key:'role',header:'Vai trò',render:u=><StatusBadge status={u.role}/>},{key:'status',header:'Trạng thái',render:u=><StatusBadge status={u.status}/>},{key:'createdAt',header:'Ngày tham gia',render:u=>formatDateTime(u.createdAt)}]}/></section></section>}
