import {useCallback,useEffect,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {Avatar} from '../../../components/shared/Avatar'
import {Button,DataTable,Dialog,Loading,Select,StatusBadge} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {routes} from '../../../constants/routes'
import {facultiesApi} from '../api/facultiesApi'
import {usersApi} from '../api/usersApi'
import {normalizePage,formatDateTime} from '../model/userModel'

export function FacultyDetailPage(){
 const{id}=useParams();const[faculty,setFaculty]=useState(null);const[users,setUsers]=useState(null);const[selected,setSelected]=useState('');const[open,setOpen]=useState(false);const[error,setError]=useState(null);const[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{try{const f=await facultiesApi.list({page:0,size:100});const current=f.content?.find(item=>item.id===id)||await facultiesApi.get(id);setFaculty(current);setUsers(normalizePage(await usersApi.list({facultyId:current.code,page:0,size:100})))}catch(e){setError(e)}},[id]);useEffect(()=>{const timer=setTimeout(load,0);return()=>clearTimeout(timer)},[load])
 async function assign(){setBusy(true);setError(null);try{await facultiesApi.assignSubjectAdmin(faculty.id,selected||null);setOpen(false);await load()}catch(e){setError(e)}finally{setBusy(false)}}
 if(error&&!faculty)return <section><PageHeader title="Chi tiết Khoa"/><div className="surface admin-error"><p>{error.message}</p></div></section>;if(!faculty||!users)return <section><PageHeader title="Chi tiết Khoa"/><div className="surface admin-loading"><Loading label="Đang tải Khoa"/></div></section>
 const admins=faculty.subjectAdmins?.length?faculty.subjectAdmins:users.items.filter(user=>user.role==='SUBJECT_ADMIN');const eligible=users.items.filter(user=>user.status==='ACTIVE'&&(user.role==='USER'||user.role==='SUBJECT_ADMIN'))
 return <section><PageHeader title={faculty.name} description={faculty.description||'Phạm vi Khoa và quản lý giảng viên.'} actions={<Link className="button button-secondary" to={routes.faculties}>Quay lại danh sách Khoa</Link>}/><div className="faculty-detail-head"><div className="faculty-code">{faculty.code.slice(0,2)}</div><div><span className="mono">{faculty.code}</span><h2>{faculty.name}</h2><StatusBadge status={faculty.active?'ACTIVE':'DISABLED'}/></div></div><div className="admin-kpi-grid faculty-kpis"><div className="admin-kpi"><small>Tổng giảng viên</small><strong>{users.totalElements}</strong></div><div className="admin-kpi"><small>Quản trị viên chuyên môn</small><strong>{admins.length}</strong></div><div className="admin-kpi"><small>Môn học</small><strong>—</strong><span>Chưa có dữ liệu tổng hợp</span></div><div className="admin-kpi"><small>Ngân hàng câu hỏi</small><strong>—</strong><span>Chưa có dữ liệu tổng hợp</span></div></div><section className="surface admin-panel faculty-admin-panel"><header><div><span className="eyebrow">QUẢN TRỊ CHUYÊN MÔN</span><h2>Quản trị viên chuyên môn</h2></div><Button variant="secondary" onClick={()=>{setSelected(admins[0]?.id||'');setOpen(true)}}>{admins.length?'Đổi quản trị viên':'Gán quản trị viên'}</Button></header>{admins.length?<div className="faculty-admin-list">{admins.map(admin=><div className="faculty-admin-person" key={admin.id}><Avatar user={{...admin,avatarUrl:admin.avatarUrl}} size="sm"/><div><strong>{admin.fullName}</strong><small>{admin.lecturerCode} · {admin.email||'Chưa có email'}</small></div></div>)}</div>:<p className="admin-online-empty">Chưa gán quản trị viên chuyên môn.</p>}</section><section className="surface admin-panel"><header><div><span className="eyebrow">GIẢNG VIÊN THUỘC KHOA</span><h2>Giảng viên thuộc Khoa</h2></div><span className="result-count">{users.totalElements} kết quả</span></header><DataTable rows={users.items} emptyTitle="Chưa có giảng viên thuộc Khoa." columns={[{key:'lecturerCode',header:'Mã GV',render:u=><span className="mono">{u.lecturerCode}</span>},{key:'fullName',header:'Họ và tên'},{key:'email',header:'Email'},{key:'role',header:'Vai trò',render:u=><StatusBadge status={u.role}/>},{key:'status',header:'Trạng thái',render:u=><StatusBadge status={u.status}/>},{key:'createdAt',header:'Ngày tham gia',render:u=>formatDateTime(u.createdAt)}]}/></section><Dialog open={open} title="Gán quản trị viên chuyên môn" onClose={()=>!busy&&setOpen(false)}><Select label="Người dùng" value={selected} onChange={e=>setSelected(e.target.value)} options={[{value:'',label:'Không gán'},...eligible.map(user=>({value:user.id,label:`${user.fullName} · ${user.lecturerCode}`}))]}/><div className="form-actions"><Button variant="secondary" onClick={()=>setOpen(false)}>Hủy</Button><Button loading={busy} onClick={()=>void assign()}>Lưu thay đổi</Button></div></Dialog></section>
}
