import {useCallback,useEffect,useState} from 'react'
import {ConfirmDialog} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {usersApi} from '../api/usersApi'
import {Pagination} from '../components/Pagination'
import {RequestState} from '../components/RequestState'
import {UserFilters} from '../components/UserFilters'
import {UserTable} from '../components/UserTable'
import {normalizePage} from '../model/userModel'

export function PendingRegistrationsPage(){const[draft,setDraft]=useState({keyword:'',role:'',facultyId:''});const[query,setQuery]=useState(draft);const[page,setPage]=useState(0);const[data,setData]=useState(normalizePage());const[loading,setLoading]=useState(true);const[error,setError]=useState(null);const[confirmation,setConfirmation]=useState(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(normalizePage(await usersApi.list({...query,status:'PENDING_APPROVAL',page,size:10})))}catch(reason){setError(reason)}finally{setLoading(false)}},[page,query]);useEffect(()=>{const task=setTimeout(load,0);return()=>clearTimeout(task)},[load]);async function confirm(){const{action,user}=confirmation;setConfirmation(null);try{await usersApi[action](user.id);await load()}catch(reason){setError(reason)}}return <section><PageHeader title="Duyệt đăng ký" description="Xác nhận hoặc từ chối tài khoản đang chờ xét duyệt."/><UserFilters filters={draft} onChange={setDraft} showStatus={false} onSubmit={event=>{event.preventDefault();setPage(0);setQuery(draft)}}/><div className="surface user-table-surface"><RequestState loading={loading} error={error} onRetry={load}/>{!loading&&!error&&<><UserTable users={data.items} pending onApprove={user=>setConfirmation({action:'approve',user})} onReject={user=>setConfirmation({action:'reject',user})}/><Pagination {...data} onPageChange={setPage}/></>}</div><ConfirmDialog open={Boolean(confirmation)} danger={confirmation?.action==='reject'} title={confirmation?.action==='reject'?'Từ chối đăng ký?':'Duyệt đăng ký?'} description={confirmation?.action==='reject'?`Tài khoản ${confirmation?.user.lecturerCode} sẽ bị từ chối.`:`Tài khoản ${confirmation?.user.lecturerCode} sẽ được kích hoạt sau khi sự kiện đồng bộ hoàn tất.`} confirmLabel={confirmation?.action==='reject'?'Từ chối':'Duyệt'} onClose={()=>setConfirmation(null)} onConfirm={confirm}/></section>}
