import {useCallback,useEffect,useState} from 'react'
import {Button,Input,Select} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {Avatar} from '../../../components/shared/Avatar'
import {usersApi} from '../api/usersApi'
import {RequestState} from '../components/RequestState'
import {calculateAge} from '../model/userModel'
import {formatAcademicName,formatRoleFaculty} from '../model/academic'

const roleLabel={SYSTEM_ADMIN:'Quản trị viên hệ thống',SUBJECT_ADMIN:'Quản trị viên chuyên môn',USER:'Giảng viên'}
const rankOptions=[{value:'NONE',label:'Không có'},{value:'PGS',label:'PGS'},{value:'GS',label:'GS'}]
const degreeOptions=[{value:'NONE',label:'Không có'},{value:'CN',label:'Cử nhân'},{value:'KS',label:'Kỹ sư'},{value:'THS',label:'Thạc sĩ'},{value:'TS',label:'Tiến sĩ'}]

export function ProfilePage(){
  const[profile,setProfile]=useState(null);const[form,setForm]=useState({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[avatarUploading,setAvatarUploading]=useState(false);const[previewUrl,setPreviewUrl]=useState('');const[error,setError]=useState(null);const[success,setSuccess]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const result=await usersApi.getMe();setProfile(result);setForm({...result,fullName:result.fullName||'',dateOfBirth:result.dateOfBirth||'',phone:result.phone||'',email:result.email||'',address:result.address||'',academicRank:result.academicRank||'NONE',academicDegree:result.academicDegree||'NONE'})}catch(reason){setError(reason)}finally{setLoading(false)}},[])
  useEffect(()=>{const timer=setTimeout(load,0);return()=>clearTimeout(timer)},[load]);useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl])
  function setField(field,value){setForm(current=>({...current,[field]:value}));setSuccess('')}
  async function submit(event){event.preventDefault();setSaving(true);setError(null);setSuccess('');try{const updated=await usersApi.updateMe({fullName:form.fullName,dateOfBirth:form.dateOfBirth||null,phone:form.phone||null,email:form.email,address:form.address||null,avatar:profile?.avatar||null,academicRank:form.academicRank,academicDegree:form.academicDegree});setProfile(updated||{...profile,...form});setSuccess('Hồ sơ đã được cập nhật.')}catch(reason){setError(reason)}finally{setSaving(false)}}
  async function uploadAvatar(event){const file=event.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)){setError(new Error('Tệp ảnh không hợp lệ.'));return}if(file.size>5*1024*1024){setError(new Error('Ảnh phải nhỏ hơn 5 MB.'));return}const local=URL.createObjectURL(file);setPreviewUrl(local);setAvatarUploading(true);setError(null);setSuccess('');try{const updated=await usersApi.uploadAvatar(file);setProfile(updated);setForm(current=>({...current,avatar:updated.avatar}));setSuccess('Ảnh đại diện đã được cập nhật.')}catch(reason){setError(reason)}finally{setAvatarUploading(false);event.target.value=''}}
  if(loading)return <section><PageHeader title="Hồ sơ cá nhân"/><div className="surface"><RequestState loading/></div></section>
  const displayUser={...profile,avatar:previewUrl||profile?.avatar};const faculty=profile?.facultyName||profile?.faculty?.name||profile?.facultyId||'Chưa được gán'
  return <section><PageHeader title="Hồ sơ cá nhân" description="Quản lý thông tin cá nhân và thông tin học thuật của bạn."/><div className="surface profile-form-card">{error&&<RequestState error={error} onRetry={load}/>} {!error&&<form className="profile-form" onSubmit={submit}><div className="profile-summary"><Avatar user={displayUser} size="lg"/><div><strong>{formatAcademicName(profile||{})}</strong><span>{profile?.lecturerCode||''}</span><span>{formatRoleFaculty(profile||{})}</span></div></div>{success&&<p className="inline-success" role="status">{success}</p>}<div className="form-grid"><Input label="Họ và tên" value={form.fullName||''} onChange={event=>setField('fullName',event.target.value)}/><Input label="Ngày sinh" type="date" value={form.dateOfBirth||''} helper={calculateAge(form.dateOfBirth)!==null?`Tuổi hiện tại: ${calculateAge(form.dateOfBirth)}`:undefined} onChange={event=>setField('dateOfBirth',event.target.value)}/><Input label="Điện thoại" type="tel" value={form.phone||''} onChange={event=>setField('phone',event.target.value)}/><Input label="Email" type="email" value={form.email||''} onChange={event=>setField('email',event.target.value)}/><Input label="Địa chỉ" value={form.address||''} onChange={event=>setField('address',event.target.value)}/><label className="field image-upload-field"><span>Ảnh đại diện</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadAvatar} disabled={avatarUploading}/><small>{avatarUploading?'Đang tải ảnh lên…':'JPEG, PNG, WEBP hoặc GIF, tối đa 5MB.'}</small></label><Select label="Học hàm" value={form.academicRank||'NONE'} options={rankOptions} onChange={event=>setField('academicRank',event.target.value)}/><Select label="Học vị" value={form.academicDegree||'NONE'} options={degreeOptions} onChange={event=>setField('academicDegree',event.target.value)}/><Input label="Khoa" value={faculty} disabled/><Input label="Vai trò" value={roleLabel[profile?.role]||profile?.role||''} disabled/><Input label="Mã giảng viên" value={profile?.lecturerCode||''} disabled/></div><div className="form-actions"><Button type="submit" loading={saving} disabled={avatarUploading}>Lưu thay đổi</Button></div></form>}</div></section>
}
