import {useCallback,useEffect,useState} from 'react'
import {Button,Input} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {usersApi} from '../api/usersApi'
import {RequestState} from '../components/RequestState'
import {calculateAge} from '../model/userModel'
const roleLabel={SYSTEM_ADMIN:'Quản trị viên hệ thống',SUBJECT_ADMIN:'Quản trị viên chuyên môn',USER:'Giảng viên'}
const editableFields=['fullName','dateOfBirth','phone','email','address','avatar']
export function ProfilePage(){const[profile,setProfile]=useState(null);const[form,setForm]=useState({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState(null);const[success,setSuccess]=useState('');const load=useCallback(async()=>{setLoading(true);setError(null);try{const result=await usersApi.getMe();setProfile(result);setForm(Object.fromEntries(editableFields.map(field=>[field,result[field]||''])))}catch(reason){setError(reason)}finally{setLoading(false)}},[]);useEffect(()=>{const timer=setTimeout(load,0);return()=>clearTimeout(timer)},[load]);async function submit(event){event.preventDefault();setSaving(true);setError(null);setSuccess('');try{const updated=await usersApi.updateMe(form);setProfile(updated||{...profile,...form});setSuccess('Hồ sơ đã được cập nhật.')}catch(reason){setError(reason)}finally{setSaving(false)}}if(loading)return <section><PageHeader title="Hồ sơ cá nhân"/><div className="surface"><RequestState loading/></div></section>;const name=profile.fullName||profile.lecturerCode||'Người dùng';const faculty=profile.facultyName||profile.faculty?.name||profile.facultyId||'Chưa được gán';return <section><PageHeader title="Hồ sơ cá nhân" description="Quản lý thông tin cá nhân. Vai trò và Khoa do quản trị viên phụ trách."/><div className="surface profile-form-card">{error&&<RequestState error={error} onRetry={load}/>} {!error&&<form className="profile-form" onSubmit={submit}><div className="profile-summary"><div className="profile-avatar">{profile.avatar?<img src={profile.avatar} alt="Ảnh đại diện"/>:name.slice(0,2).toUpperCase()}</div><div><strong>{name}</strong><span>{profile.lecturerCode||''}</span><span>{roleLabel[profile.role]||profile.role||'Giảng viên'} • Khoa {faculty}</span></div></div>{success&&<p className="inline-success" role="status">{success}</p>}<div className="form-grid"><Input label="Họ và tên" value={form.fullName} onChange={event=>setForm({...form,fullName:event.target.value})}/><Input label="Ngày sinh" type="date" value={form.dateOfBirth} helper={calculateAge(form.dateOfBirth)!==null?`Tuổi hiện tại: ${calculateAge(form.dateOfBirth)}`:undefined} onChange={event=>setForm({...form,dateOfBirth:event.target.value})}/><Input label="Điện thoại" type="tel" value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/><Input label="Email" type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/><Input label="Địa chỉ" value={form.address} onChange={event=>setForm({...form,address:event.target.value})}/><Input label="URL ảnh đại diện" type="url" value={form.avatar} onChange={event=>setForm({...form,avatar:event.target.value})}/><Input label="Khoa" value={faculty} disabled/><Input label="Vai trò" value={roleLabel[profile.role]||profile.role||''} disabled/></div><div className="form-actions"><Button type="submit" loading={saving}>Lưu thay đổi</Button></div></form>}</div></section>}
