import {useCallback,useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {Button,DataTable,DashboardMetricSkeleton,TableSkeleton,ChartSkeleton} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {routes} from '../../../constants/routes'
import {useAuth} from '../../auth/hooks/useAuth'
import {catalogApi} from '../../questions/api/catalogApi'
import {questionsApi} from '../../questions/api/questionsApi'
import {normalizePage} from '../../questions/model/questionModel'
import {QuestionStatusChart} from '../../../components/shared/QuestionStatusChart'

export function SubjectAdminDashboardPage(){
  const{facultyId,currentUser}=useAuth();const[data,setData]=useState(null);const[error,setError]=useState(null)
  const faculty=currentUser?.facultyName||currentUser?.faculty?.name||facultyId||'Chưa phân công'
  const load=useCallback(async()=>{try{const[subjects,all,pending,approved]=await Promise.all([catalogApi.subjects(),questionsApi.list({page:0,size:1}),questionsApi.list({status:'PENDING_REVIEW',page:0,size:5,sort:'createdAt,asc'}),questionsApi.list({status:'APPROVED',page:0,size:1})]);setData({subjects,all:normalizePage(all),pending:normalizePage(pending),approved:normalizePage(approved)})}catch(reason){setError(reason)}},[])
  useEffect(()=>{const timer=setTimeout(load,0);return()=>clearTimeout(timer)},[load])
  if(error)return <section><PageHeader title="Tổng quan chuyên môn" description={'Theo dõi nội dung trong Khoa '+faculty+'.'}/><div className="surface request-error" role="alert"><strong>Không thể tải tổng quan chuyên môn</strong><p>{error.message}</p><Button variant="secondary" onClick={load}>Thử lại</Button></div></section>
  if(!data)return <section className="subject-dashboard"><PageHeader title="Tổng quan chuyên môn" description={'Theo dõi nội dung trong Khoa '+faculty+'.'}/><DashboardMetricSkeleton count={4}/><div className="subject-dashboard-grid"><section className="surface admin-panel"><TableSkeleton rows={5} columns={3}/></section><section className="surface admin-panel"><ChartSkeleton/></section></div></section>
  const stats=[['Môn học phụ trách',data.subjects.length,routes.subjects],['Tổng số câu hỏi',data.all.totalElements,routes.questions],['Chờ phê duyệt',data.pending.totalElements,routes.review],['Đã phê duyệt',data.approved.totalElements,routes.questions]]
  return <section className="subject-dashboard"><PageHeader title="Tổng quan chuyên môn" description={'Theo dõi môn học, ngân hàng câu hỏi và hoạt động xét duyệt trong Khoa '+faculty+'.'} actions={<Link className="button button-primary" to={routes.review}>Mở hàng đợi xét duyệt</Link>}/><div className="admin-kpi-grid subject-kpi-grid">{stats.map(([label,value,to])=><Link className="admin-kpi" to={to} key={label}><span className="kpi-accent"/><small>{label}</small><strong>{value.toLocaleString('vi-VN')}</strong><span>Xem chi tiết →</span></Link>)}</div><div className="subject-dashboard-grid"><section className="surface admin-panel"><header><div><span className="eyebrow">PHÂN BỐ NỘI DUNG</span><h2>Câu hỏi theo Môn học</h2></div><Link to={routes.subjects}>Quản lý môn →</Link></header><DataTable rows={data.subjects} emptyTitle="Chưa có môn học trong Khoa." columns={[{key:'code',header:'Mã môn',render:item=><span className="mono">{item.code}</span>},{key:'name',header:'Môn học'},{key:'facultyId',header:'Khoa',render:item=>item.facultyId||faculty}]}/></section><section className="surface admin-panel chart-card"><header><div><span className="eyebrow">PHÂN BỐ TRẠNG THÁI</span><h2>Trạng thái câu hỏi trong Khoa</h2></div></header><div className="chart-card-body"><QuestionStatusChart counts={{APPROVED:data.approved.totalElements,PENDING_REVIEW:data.pending.totalElements}}/></div></section></div><div className="subject-dashboard-grid"><section className="surface coverage-placeholder"><span className="eyebrow">PHÂN TÍCH</span><h2>Độ bao phủ kiến thức</h2><p>Coverage percentage và target chỉ hiển thị khi backend cung cấp ma trận/target tương ứng.</p><Link className="button button-secondary" to={routes.coverage}>Mở phân tích</Link></section><section className="surface coverage-placeholder"><span className="eyebrow">REVIEW ACTIVITY</span><h2>Hoạt động xét duyệt gần đây</h2><p>Backend hiện chưa có audit/activity feed riêng; hệ thống không hiển thị dữ liệu giả.</p></section></div></section>
}
