import {MatrixListPage,CreateMatrixPage,MatrixPage,ExamsPage,GenerateExamPage,ExamDetailPage} from '../../features/exams'
import {AiWorkspacePage} from '../../features/ai'
import {Navigate,Route,Routes} from 'react-router-dom'
import {AppLayout} from '../layouts/AppLayout'
import {ForbiddenPage} from '../pages/ForbiddenPage'
import {NotFoundPage} from '../pages/NotFoundPage'
import {PublicLandingPage} from '../pages/PublicLandingPage'
import {PlaceholderPage} from '../../components/shared/PlaceholderPage'
import {routes} from '../../constants/routes'
import {useAuth} from '../../features/auth/hooks/useAuth'
import {ForgotPasswordPage} from '../../features/auth/pages/ForgotPasswordPage'
import {LoginPage} from '../../features/auth/pages/LoginPage'
import {RegisterPage} from '../../features/auth/pages/RegisterPage'
import {RegistrationPendingPage} from '../../features/auth/pages/RegistrationPendingPage'
import {ResetPasswordPage} from '../../features/auth/pages/ResetPasswordPage'
import {VerifyOtpPage} from '../../features/auth/pages/VerifyOtpPage'
import {AdminDashboardPage,FacultyDetailPage,FacultyPage,PendingRegistrationsPage,ProfilePage,SubjectAdminDashboardPage,SystemSettingsPage,UserDashboardPage,UserDetailPage,UserListPage} from '../../features/users'
import {HelpPage} from '../../features/help'
import {NotificationsPage} from '../../features/notifications'
import {CoveragePage,CreateQuestionPage,EditQuestionPage,KnowledgeStructurePage,QuestionDetailPage,QuestionListPage,ReviewQueuePage,QuestionReviewPage} from '../../features/questions'
import {SubjectPage} from '../../features/questions/pages/SubjectPage'
import {ProtectedRoute} from './ProtectedRoute'
import {RoleGuard} from './RoleGuard'
import {protectedRoutes} from './routeConfig'
function GuestRoute({children}){const{authenticated}=useAuth();return authenticated?<Navigate to={routes.dashboard} replace/>:children}
function RoutePage({route,role}){if(route.path===routes.dashboard)return role==='USER'?<UserDashboardPage/>:role==='SUBJECT_ADMIN'?<SubjectAdminDashboardPage/>:<AdminDashboardPage/>;if(route.path===routes.matrices)return <MatrixListPage/>;if(route.path==='/exam-matrices/new')return <CreateMatrixPage/>;if(route.path==='/exam-matrices/:id/edit')return <MatrixPage edit/>;if(route.path==='/exam-matrices/:id')return <MatrixPage/>;if(route.path===routes.exams)return <ExamsPage/>;if(route.path==='/exams/generate')return <GenerateExamPage/>;if(route.path==='/exams/:id')return <ExamDetailPage/>;if([routes.documents,routes.generate,routes.aiJobs,routes.chat,'/ai/analysis','/ai/jobs/:id'].includes(route.path))return <AiWorkspacePage/>;if(route.path===routes.review)return <ReviewQueuePage/>;if(route.path==='/review/:id')return <QuestionReviewPage/>;if(route.path===routes.users)return <UserListPage/>;if(route.path===routes.registrations)return <PendingRegistrationsPage/>;if(route.path===routes.faculties)return <FacultyPage/>;if(route.path===routes.facultyDetail)return <FacultyDetailPage/>;if(route.path===routes.settings)return <SystemSettingsPage/>;if(route.path===routes.subjects)return <SubjectPage/>;if(route.path===routes.knowledge)return <KnowledgeStructurePage/>;if(route.path===routes.coverage)return <CoveragePage/>;if(route.path===routes.help)return <HelpPage/>;if(route.path===routes.userDetail)return <UserDetailPage/>;if(route.path===routes.profile)return <ProfilePage/>;if(route.path===routes.notifications)return <NotificationsPage/>;if(route.path===routes.questions||route.path===routes.myQuestions)return <QuestionListPage/>;if(route.path===routes.newQuestion)return <CreateQuestionPage/>;if(route.path==='/questions/:id')return <QuestionDetailPage/>;if(route.path==='/questions/:id/edit')return <EditQuestionPage/>;return <PlaceholderPage title={route.title} description={route.description}/>}
export function AppRouter(){const{role}=useAuth();return <Routes><Route path={routes.login} element={<GuestRoute><LoginPage/></GuestRoute>}/><Route path={routes.register} element={<GuestRoute><RegisterPage/></GuestRoute>}/><Route path={routes.registrationPending} element={<GuestRoute><RegistrationPendingPage/></GuestRoute>}/><Route path={routes.forgotPassword} element={<GuestRoute><ForgotPasswordPage/></GuestRoute>}/><Route path={routes.verifyOtp} element={<GuestRoute><VerifyOtpPage/></GuestRoute>}/><Route path={routes.resetPassword} element={<GuestRoute><ResetPasswordPage/></GuestRoute>}/><Route element={<ProtectedRoute/>}><Route element={<AppLayout/>}>{protectedRoutes.map(route=><Route key={route.path} path={route.path} element={<RoleGuard allowedRoles={route.roles}><RoutePage route={route} role={role}/></RoleGuard>} />)}<Route path={routes.forbidden} element={<ForbiddenPage/>}/></Route></Route><Route path="/" element={<PublicLandingPage/>}/><Route path="*" element={<NotFoundPage/>}/></Routes>}
