import {routes} from '../../constants/routes'
import {roles} from '../../constants/roles'
const allRoles=Object.values(roles)
export const protectedRoutes=[
 {path:routes.dashboard,title:'Dashboard',roles:allRoles},{path:routes.profile,title:'Profile',roles:allRoles},
 {path:routes.questions,title:'Question bank',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:routes.myQuestions,title:'My questions',roles:[roles.USER]},{path:routes.newQuestion,title:'Create question',roles:[roles.USER]},{path:'/questions/:id',title:'Question detail',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:'/questions/:id/edit',title:'Edit question',roles:[roles.USER]},
 {path:routes.review,title:'Pending review',roles:[roles.SUBJECT_ADMIN]},{path:'/review/:id',title:'Review question',roles:[roles.SUBJECT_ADMIN]},
 {path:routes.matrices,title:'Exam matrices',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:'/exam-matrices/new',title:'New matrix',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:'/exam-matrices/:id/edit',title:'Edit matrix',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:'/exam-matrices/:id',title:'Matrix detail',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:routes.exams,title:'Exams',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:'/exams/generate',title:'Generate exam',roles:[roles.SUBJECT_ADMIN]},{path:'/exams/:id',title:'Exam version',roles:[roles.SUBJECT_ADMIN,roles.USER]},
 {path:routes.documents,title:'Documents',roles:[roles.USER]},{path:routes.generate,title:'AI workspace',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:'/ai/analysis',title:'AI analysis',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:'/ai/jobs/:id',title:'AI job',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:routes.aiJobs,title:'AI jobs',roles:[roles.SUBJECT_ADMIN,roles.USER]},{path:routes.chat,title:'Chatbot',roles:[roles.USER]},
 {path:routes.notifications,title:'Notifications',roles:allRoles},{path:routes.users,title:'Users',roles:[roles.SYSTEM_ADMIN]},{path:routes.userDetail,title:'User detail',roles:[roles.SYSTEM_ADMIN]},{path:routes.registrations,title:'Pending registrations',roles:[roles.SYSTEM_ADMIN]},{path:routes.faculties,title:'Faculties',roles:[roles.SYSTEM_ADMIN]},{path:routes.facultyDetail,title:'Faculty detail',roles:[roles.SYSTEM_ADMIN]},{path:routes.settings,title:'System settings',roles:[roles.SYSTEM_ADMIN]},{path:routes.subjects,title:'Subjects',roles:[roles.SUBJECT_ADMIN]},{path:routes.knowledge,title:'Knowledge structure',roles:[roles.SUBJECT_ADMIN]},{path:routes.coverage,title:'Knowledge coverage',roles:[roles.SUBJECT_ADMIN]},{path:routes.help,title:'Help',roles:allRoles},
]
function matches(pattern,pathname){const patternParts=pattern.split('/').filter(Boolean);const pathParts=pathname.split('/').filter(Boolean);return patternParts.length===pathParts.length&&patternParts.every((part,index)=>part.startsWith(':')||part===pathParts[index])}
export function getRouteMeta(pathname){return protectedRoutes.find(route=>matches(route.path,pathname))}
