spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${USER_DB_USERNAME:postgres}
    password: ${USER_DB_PASSWORD:postgres}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

user:
  internal:
    service-token: ${INTERNAL_SERVICE_TOKEN:dev-internal-token}
