package com.notificationservice.domain.model;
import com.notificationservice.domain.exception.InvalidNotificationException;import java.time.Instant;import java.util.*;
public final class ScheduledNotification{
 private final UUID id,createdBy;private final String targetRole,targetFaculty,title,content;private final Instant scheduledAt,createdAt,updatedAt;private final ScheduledStatus status;private final long version;
 public ScheduledNotification(UUID id,String targetRole,String targetFaculty,String title,String content,Instant scheduledAt,ScheduledStatus status,UUID createdBy,Instant createdAt,Instant updatedAt,long version){this.id=Objects.requireNonNull(id);if(blank(targetRole)&&blank(targetFaculty))throw new InvalidNotificationException("A scheduled target is required");this.targetRole=clean(targetRole);this.targetFaculty=clean(targetFaculty);this.title=required(title,200);this.content=required(content,2000);this.scheduledAt=Objects.requireNonNull(scheduledAt);this.status=Objects.requireNonNull(status);this.createdBy=Objects.requireNonNull(createdBy);this.createdAt=Objects.requireNonNull(createdAt);this.updatedAt=Objects.requireNonNull(updatedAt);this.version=version;}
 public static ScheduledNotification pending(String role,String faculty,String title,String content,Instant at,UUID by,Instant now){return new ScheduledNotification(UUID.randomUUID(),role,faculty,title,content,at,ScheduledStatus.PENDING,by,now,now,0);}
 public ScheduledNotification processing(Instant at){if(status!=ScheduledStatus.PENDING)throw new InvalidNotificationException("Only pending schedule can be claimed");return copy(ScheduledStatus.PROCESSING,at);}public ScheduledNotification completed(Instant at){return copy(ScheduledStatus.COMPLETED,at);}public ScheduledNotification failed(Instant at){return copy(ScheduledStatus.FAILED,at);}private ScheduledNotification copy(ScheduledStatus s,Instant at){return new ScheduledNotification(id,targetRole,targetFaculty,title,content,scheduledAt,s,createdBy,createdAt,at,version);}
 private static boolean blank(String v){return v==null||v.isBlank();}private static String clean(String v){return blank(v)?null:v.trim();}private static String required(String v,int m){if(blank(v)||v.trim().length()>m)throw new InvalidNotificationException("Invalid scheduled notification text");return v.trim();}
 public UUID getId(){return id;}public String getTargetRole(){return targetRole;}public String getTargetFaculty(){return targetFaculty;}public String getTitle(){return title;}public String getContent(){return content;}public Instant getScheduledAt(){return scheduledAt;}public ScheduledStatus getStatus(){return status;}public UUID getCreatedBy(){return createdBy;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}public long getVersion(){return version;}
}
