package com.aiservice.application.service;
import com.aiservice.application.port.out.*; import com.aiservice.infrastructure.persistence.entity.*; import com.aiservice.infrastructure.persistence.repository.*; import com.aiservice.domain.exception.*; import java.io.*; import java.time.*; import java.util.*; import java.util.stream.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import tools.jackson.databind.ObjectMapper;
@Service public class AiKnowledgeService { private final AiKnowledgeDocumentRepository documents; private final AiKnowledgeChunkRepository chunks; private final StoragePort storage; private final List<DocumentTextExtractor> extractors; private final ObjectMapper mapper; private final Clock clock;
 public AiKnowledgeService(AiKnowledgeDocumentRepository d,AiKnowledgeChunkRepository c,StoragePort s,List<DocumentTextExtractor> e,ObjectMapper m,Clock k){documents=d;chunks=c;storage=s;extractors=e;mapper=m;clock=k;}
 @Transactional public AiKnowledgeDocumentEntity upload(UUID actor,String title,String description,String name,String type,long size,InputStream input){if(title==null||title.isBlank())throw new IllegalArgumentException("Title is required");if(size<=0||size>10485760)throw new IllegalArgumentException("Document size is invalid");String safe=type==null?"":type.toLowerCase(Locale.ROOT);String ext=extension(name);if(!Set.of("txt","md","pdf","docx","xlsx","pptx","doc","xls","ppt").contains(ext))throw new UnsupportedDocumentException("Unsupported policy document format");var x=extractors.stream().filter(e->e.supports(name,safe)).findFirst().orElseThrow(()->new UnsupportedDocumentException("No extractor for policy document"));var stored=storage.store(name,input);String text=x.extract(name,safe,storage.read(stored.key()));if(text==null||text.isBlank())throw new UnsupportedDocumentException("DOCUMENT_REQUIRES_OCR");var now=Instant.now(clock);var d=new AiKnowledgeDocumentEntity();d.id=UUID.randomUUID();d.title=title.trim();d.description=description;d.originalFileName=name;d.contentType=safe;d.fileSize=size;d.status="READY";d.enabled=true;d.extractedText=text;d.createdBy=actor;d.createdAt=now;d.updatedAt=now;documents.save(d);index(d,text);return d;}
 @Transactional public void reprocess(UUID id){var d=documents.findById(id).orElseThrow(()->new NotFoundException("Knowledge document not found"));chunks.deleteByDocumentId(id);index(d,d.extractedText);d.status="READY";d.processingError=null;d.updatedAt=Instant.now(clock);documents.save(d);}
 @Transactional public AiKnowledgeDocumentEntity toggle(UUID id,boolean enabled){var d=documents.findById(id).orElseThrow(()->new NotFoundException("Knowledge document not found"));d.enabled=enabled;d.updatedAt=Instant.now(clock);return documents.save(d);}
 @Transactional public void delete(UUID id){if(!documents.existsById(id))throw new NotFoundException("Knowledge document not found");documents.deleteById(id);}
 @Transactional(readOnly=true) public List<AiKnowledgeDocumentEntity> list(){return documents.findAll(org.springframework.data.domain.Sort.by(org.springframework.data.domain.Sort.Direction.DESC,"updatedAt"));}
 @Transactional(readOnly=true) public long chunkCount(UUID documentId){return chunks.countByDocumentId(documentId);}
 @Transactional(readOnly=true) public List<Source> retrieve(String question,int limit){var q=vector(question);return documents.findByEnabledTrueAndStatusOrderByUpdatedAtDesc("READY").stream().flatMap(d->chunks.findByDocumentIdOrderByChunkIndex(d.id).stream().map(c->new Scored(d,c,cosine(q,parse(c.embedding))))).filter(x->x.score>=0.08).sorted(Comparator.comparingDouble((Scored x)->x.score).reversed()).limit(limit).map(x->new Source(x.document.id,x.document.title,location(x.chunk.text),excerpt(x.chunk.text))).toList();}
 private void index(AiKnowledgeDocumentEntity d,String text){int i=0;for(String section:semanticChunks(text)){var c=new AiKnowledgeChunkEntity();c.id=UUID.randomUUID();c.documentId=d.id;c.chunkIndex=i++;c.text=section;c.embedding=serialize(vector(section));c.metadataJson="{\"sourceFile\":\""+d.originalFileName.replace("\"","'")+"\",\"chunk\":"+c.chunkIndex+"}";chunks.save(c);}}
 private List<String> semanticChunks(String text){var parts=text.split("(?m)(?=^#{1,6}\\s|^\\[Slide\\s|^# Sheet:|\\n\\n)");var out=new ArrayList<String>();StringBuilder b=new StringBuilder();for(String p:parts){if(p.isBlank())continue;if(b.length()+p.length()>1800&&!b.isEmpty()){out.add(b.toString().trim());b=new StringBuilder(b.substring(Math.max(0,b.length()-250)));}b.append(p).append("\n");}if(!b.isEmpty())out.add(b.toString().trim());return out;}
 private double[] vector(String s){double[] v=new double[128];for(String t:s.toLowerCase(Locale.ROOT).split("[^\\p{L}\\p{N}]+"))if(!t.isBlank())v[Math.floorMod(t.hashCode(),v.length)]++;double n=Math.sqrt(Arrays.stream(v).map(x->x*x).sum());if(n>0)for(int i=0;i<v.length;i++)v[i]/=n;return v;}
 private double cosine(double[] a,double[] b){double s=0;for(int i=0;i<a.length;i++)s+=a[i]*b[i];return s;} private String serialize(double[] v){return Arrays.stream(v).mapToObj(Double::toString).collect(Collectors.joining(","));} private double[] parse(String s){var p=s.split(",");var v=new double[p.length];for(int i=0;i<p.length;i++)v[i]=Double.parseDouble(p[i]);return v;} private String extension(String n){int i=n==null?-1:n.lastIndexOf('.');return i<0?"":n.substring(i+1).toLowerCase(Locale.ROOT);} private String location(String s){return s.startsWith("[Slide")?s.split("\\n",2)[0]:"";} private String excerpt(String s){return s.length()>220?s.substring(0,217)+"...":s;} private record Scored(AiKnowledgeDocumentEntity document,AiKnowledgeChunkEntity chunk,double score){} public record Source(UUID documentId,String title,String location,String excerpt){}
}
