package com.aiservice.application.service;

import com.aiservice.application.port.out.*;
import com.aiservice.domain.exception.*;
import com.aiservice.infrastructure.persistence.entity.TextbookStructureDraftEntity;
import com.aiservice.infrastructure.persistence.repository.TextbookStructureDraftRepository;
import java.io.*;import java.time.*;import java.util.*;import java.util.regex.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.ObjectMapper;

@Service public class TextbookStructureService{
 private static final long MAX=20*1024*1024;private static final Pattern CHAPTER=Pattern.compile("^(?:CHƯƠNG|CHUONG|CHAPTER)\\s+([A-Z0-9IVX]+)[\\s.:\\-]*(.*)$",Pattern.CASE_INSENSITIVE|Pattern.UNICODE_CASE);private static final Pattern TOPIC=Pattern.compile("^(?:CHỦ ĐỀ|CHU DE|TOPIC)\\s*([A-Z0-9.]+)?[\\s.:\\-]*(.*)$",Pattern.CASE_INSENSITIVE|Pattern.UNICODE_CASE);private static final Pattern NUMBERED=Pattern.compile("^(\\d+)\\.(\\d+)(?:\\.(\\d+))?[\\s.:\\-]+(.+)$");
 private final TextbookStructureDraftRepository repo;private final StoragePort storage;private final List<DocumentTextExtractor> extractors;private final TaxonomyImportPort taxonomy;private final ObjectMapper mapper;private final Clock clock;
 public TextbookStructureService(TextbookStructureDraftRepository repo,StoragePort storage,List<DocumentTextExtractor> extractors,TaxonomyImportPort taxonomy,ObjectMapper mapper,Clock clock){this.repo=repo;this.storage=storage;this.extractors=extractors;this.taxonomy=taxonomy;this.mapper=mapper;this.clock=clock;}
 @Transactional public View upload(UUID owner,UUID subject,String name,String type,long size,InputStream input){validate(name,type,size);try{byte[] bytes=input.readAllBytes();if(bytes.length<5||bytes[0]!='%'||bytes[1]!='P'||bytes[2]!='D'||bytes[3]!='F'||bytes[4]!='-')throw new UnsupportedDocumentException("TEXTBOOK_PDF_SIGNATURE_INVALID");var stored=storage.store(name,new ByteArrayInputStream(bytes));Instant now=Instant.now(clock);var e=new TextbookStructureDraftEntity();e.id=UUID.randomUUID();e.subjectId=subject;e.ownerId=owner;e.originalFileName=name;e.storageKey=stored.key();e.status="PROCESSING";e.extractedText="";e.structureJson="{\"chapters\":[]}";e.createdAt=now;e.updatedAt=now;repo.save(e);try{var extractor=extractors.stream().filter(x->x.supports(name,"application/pdf")).findFirst().orElseThrow(()->new UnsupportedDocumentException("PDF extractor unavailable"));e.extractedText=extractor.extract(name,"application/pdf",new ByteArrayInputStream(bytes));Structure structure=parse(e.extractedText);e.structureJson=mapper.writeValueAsString(structure);e.status="READY";}catch(RuntimeException ex){e.status="FAILED";e.processingError=safe(ex.getMessage());}e.updatedAt=Instant.now(clock);return view(repo.save(e));}catch(IOException ex){throw new UnsupportedDocumentException("Unable to read textbook PDF");}}
 @Transactional(readOnly=true)public List<View> list(UUID owner,UUID subject){return repo.findAllByOwnerIdAndSubjectIdOrderByCreatedAtDesc(owner,subject).stream().map(this::view).toList();}
 @Transactional(readOnly=true)public View get(UUID id,UUID owner){return view(owned(id,owner));}
 @Transactional public View confirm(UUID id,UUID owner,Structure edited,String token){var e=owned(id,owner);if(!"READY".equals(e.status))throw new IllegalArgumentException("Only READY textbook structure can be confirmed");validate(edited);taxonomy.confirm(e.subjectId,edited,token);try{e.structureJson=mapper.writeValueAsString(edited);}catch(Exception ex){throw new IllegalArgumentException("Invalid structure");}e.status="CONFIRMED";e.updatedAt=Instant.now(clock);return view(repo.save(e));}
 @Transactional(readOnly=true)public Source source(UUID id,UUID owner){var e=owned(id,owner);return new Source(e.originalFileName,storage.read(e.storageKey));}
 private TextbookStructureDraftEntity owned(UUID id,UUID owner){return repo.findById(id).filter(e->e.ownerId.equals(owner)).orElseThrow(()->new NotFoundException("Textbook draft not found"));}
 private void validate(String name,String type,long size){if(name==null||!name.toLowerCase(Locale.ROOT).endsWith(".pdf")||!"application/pdf".equalsIgnoreCase(type))throw new UnsupportedDocumentException("Only application/pdf .pdf textbooks are accepted");if(size<=0||size>MAX)throw new UnsupportedDocumentException("Textbook PDF size is invalid");}
 private Structure parse(String text){List<MutableChapter> chapters=new ArrayList<>();MutableChapter chapter=null;MutableTopic topic=null;int ci=0,ti=0,ii=0;for(String raw:text.split("\\R")){String line=raw.trim().replaceAll("\\s+"," ");if(line.length()<3||line.length()>240)continue;Matcher c=CHAPTER.matcher(line),t=TOPIC.matcher(line),n=NUMBERED.matcher(line);if(c.matches()){chapter=new MutableChapter("CH"+(++ci),blank(c.group(2),"Chương "+c.group(1)));chapters.add(chapter);topic=null;ti=0;continue;}if(t.matches()){if(chapter==null){chapter=new MutableChapter("CH"+(++ci),"Nội dung giáo trình");chapters.add(chapter);}topic=new MutableTopic("T"+ci+"."+(++ti),blank(t.group(2),"Chủ đề "+blank(t.group(1),String.valueOf(ti))));chapter.topics.add(topic);ii=0;continue;}if(n.matches()){if(chapter==null){chapter=new MutableChapter("CH"+(++ci),"Nội dung giáo trình");chapters.add(chapter);}if(topic==null||n.group(3)==null){topic=new MutableTopic("T"+n.group(1)+"."+n.group(2),n.group(4));chapter.topics.add(topic);ii=0;}else topic.items.add(new Item("KI"+n.group(1)+"."+n.group(2)+"."+n.group(3),n.group(4),0,0,0));}}
  if(chapters.isEmpty()){var c=new MutableChapter("CH1","Nội dung giáo trình");var t=new MutableTopic("T1.1","Nội dung chính");text.lines().map(String::trim).filter(x->x.length()>8&&x.length()<180).limit(20).forEach(x->t.items.add(new Item("KI1.1."+(t.items.size()+1),x,0,0,0)));if(t.items.isEmpty())t.items.add(new Item("KI1.1.1","Nội dung cần biên tập",0,0,0));c.topics.add(t);chapters.add(c);}for(var c:chapters){if(c.topics.isEmpty())c.topics.add(new MutableTopic("T"+(chapters.indexOf(c)+1)+".1","Nội dung chính"));for(var t:c.topics)if(t.items.isEmpty())t.items.add(new Item("KI"+(chapters.indexOf(c)+1)+"."+(c.topics.indexOf(t)+1)+".1",t.name,0,0,0));}
  return new Structure(chapters.stream().map(c->new Chapter(c.code,c.name,c.topics.stream().map(t->new Topic(t.code,t.name,List.copyOf(t.items))).toList())).toList());}
 private void validate(Structure s){if(s==null||s.chapters()==null||s.chapters().isEmpty())throw new IllegalArgumentException("At least one chapter is required");for(var c:s.chapters()){required(c.code());required(c.name());if(c.topics()==null||c.topics().isEmpty())throw new IllegalArgumentException("Each chapter requires a topic");for(var t:c.topics()){required(t.code());required(t.name());if(t.items()==null||t.items().isEmpty())throw new IllegalArgumentException("Each topic requires a knowledge item");for(var i:t.items()){required(i.code());required(i.name());if(i.targetEasy()<0||i.targetMedium()<0||i.targetHard()<0)throw new IllegalArgumentException("Targets cannot be negative");}}}}
 private View view(TextbookStructureDraftEntity e){try{return new View(e.id,e.subjectId,e.originalFileName,e.status,mapper.readValue(e.structureJson,Structure.class),e.processingError,e.createdAt,e.updatedAt);}catch(Exception ex){throw new IllegalStateException("Stored textbook structure is invalid");}}
 private String blank(String v,String f){return v==null||v.isBlank()?f:v.trim();}private void required(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("Structure code and name are required");}private String safe(String v){return v==null?"Processing failed":v.substring(0,Math.min(1000,v.length()));}
 private static class MutableChapter{String code,name;List<MutableTopic>topics=new ArrayList<>();MutableChapter(String c,String n){code=c;name=n;}}private static class MutableTopic{String code,name;List<Item>items=new ArrayList<>();MutableTopic(String c,String n){code=c;name=n;}}
 public record Structure(List<Chapter>chapters){}public record Chapter(String code,String name,List<Topic>topics){}public record Topic(String code,String name,List<Item>items){}public record Item(String code,String name,int targetEasy,int targetMedium,int targetHard){}public record View(UUID id,UUID subjectId,String originalFileName,String status,Structure structure,String processingError,Instant createdAt,Instant updatedAt){}public record Source(String filename,InputStream data){}
}
