import { useEffect, useId, useRef } from 'react';
const focusable = 'button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])';

export function Dialog({ open, title, subtitle, icon, children, onClose, footer, size = 'medium' }) {
  const ref = useRef(null); const previousFocus = useRef(null); const titleId = `dialog-title-${useId().replaceAll(':', '')}`;
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open) { previousFocus.current = document.activeElement; if (!dialog.open) dialog.showModal(); requestAnimationFrame(() => dialog.querySelector(focusable)?.focus()); } else if (dialog.open) dialog.close(); if (!open && previousFocus.current?.focus) previousFocus.current.focus(); }, [open]);
  useEffect(() => { if (!open) return undefined; function handleKeyDown(event) { if (event.key !== 'Tab') return; const items = [...ref.current?.querySelectorAll(focusable) || []].filter(item => !item.disabled); if (!items.length) return; const first = items[0]; const last = items.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } document.addEventListener('keydown', handleKeyDown); return () => document.removeEventListener('keydown', handleKeyDown); }, [open]);
  return <dialog ref={ref} className={`dialog dialog-${size}`} onCancel={event => { event.preventDefault(); onClose(); }} aria-labelledby={titleId}><header className="dialog-head"><div>{icon && <span className="dialog-icon" aria-hidden="true">{icon}</span>}<h2 id={titleId}>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button type="button" onClick={onClose} aria-label="Đóng">×</button></header><div className="dialog-body">{children}</div>{footer && <footer className="dialog-footer">{footer}</footer>}</dialog>;
}
