export function InlineSpinner({label, className=''}){return <span className={`spinner ${className}`.trim()} role={label?'status':undefined} aria-label={label}/>}
export function Loading({label='Đang tải'}){return <div className="loading" role="status" aria-live="polite"><InlineSpinner/><span>{label}</span></div>}
export function PageLoader({label='Đang tải dữ liệu...'}){return <div className="page-loader" role="status" aria-live="polite"><span className="page-loader-spinner" aria-hidden="true"/><span>{label}</span></div>}
export function Skeleton({lines=3,className='',children}){return children||<div className={`skeleton ${className}`.trim()} aria-hidden="true">{Array.from({length:lines},(_,i)=><span key={i}/>)}</div>}
export function SkeletonText({width='100%',height=14}){return <span className="skeleton-block skeleton-text" aria-hidden="true" style={{width,height}}/>}
export function SkeletonAvatar({size=40}){return <span className="skeleton-block skeleton-avatar" aria-hidden="true" style={{width:size,height:size}}/>}
export function SkeletonButton(){return <span className="skeleton-block skeleton-button" aria-hidden="true"/>}
export function SkeletonCard({className=''}){return <div className={`skeleton-card ${className}`.trim()} aria-hidden="true"><SkeletonText width="44%"/><SkeletonText width="68%" height={30}/><SkeletonText width="34%" height={12}/></div>}
export function DashboardMetricSkeleton({count=5}){return <div className="admin-kpi-grid dashboard-metric-skeleton-grid" aria-hidden="true">{Array.from({length:count},(_,i)=><div className="skeleton-card dashboard-metric-skeleton" key={i}><SkeletonText width="48%" height={12}/><SkeletonText width="38%" height={32}/><SkeletonText width="62%" height={11}/><span className="skeleton-icon"/></div>)}</div>}
export function TableSkeleton({rows=6,columns=6}){return <div className="table-wrap table-skeleton" aria-hidden="true"><table><thead><tr>{Array.from({length:columns},(_,i)=><th key={i}><SkeletonText width={i===0?'60%':'72%'} height={11}/></th>)}</tr></thead><tbody>{Array.from({length:rows},(_,row)=><tr key={row}>{Array.from({length:columns},(_,i)=><td key={i}><SkeletonText width={i===1?'90%':i===columns-1?'50%':'66%'} height={i===1?14:12}/></td>)}</tr>)}</tbody></table></div>}
export function QuestionCardSkeleton(){return <div className="skeleton-card question-card-skeleton" aria-hidden="true"><SkeletonText width="52%"/><SkeletonText width="88%"/><SkeletonText width="74%"/><div><SkeletonText width="22%"/><SkeletonText width="18%"/></div></div>}
export function ChartSkeleton(){return <div className="chart-skeleton" aria-hidden="true"><SkeletonText width="34%"/><div className="chart-skeleton-body"><span/><span/><span/><span/><span/></div><div className="chart-skeleton-legend"><SkeletonText width="18%"/><SkeletonText width="22%"/><SkeletonText width="20%"/></div></div>}
export function ProfileSkeleton(){return <div className="profile-skeleton" aria-hidden="true"><div className="profile-skeleton-summary"><SkeletonAvatar size={72}/><div><SkeletonText width="150px"/><SkeletonText width="110px"/><SkeletonText width="130px"/></div></div><div className="profile-skeleton-fields">{Array.from({length:8},(_,i)=><div key={i}><SkeletonText width="38%" height={11}/><SkeletonText width="100%" height={42}/></div>)}</div></div>}
export function NotificationSkeleton({count=4}){return <div className="notification-skeleton-list" aria-hidden="true">{Array.from({length:count},(_,i)=><div className="notification-skeleton" key={i}><SkeletonAvatar size={32}/><div><SkeletonText width="120px"/><SkeletonText width="220px"/><SkeletonText width="70px" height={11}/></div></div>)}</div>}
