package com.aiservice.infrastructure.extraction;
import com.aiservice.application.port.out.DocumentTextExtractor; import com.aiservice.domain.exception.*; import org.apache.pdfbox.Loader; import org.apache.pdfbox.text.PDFTextStripper; import org.apache.poi.hwpf.HWPFDocument; import org.apache.poi.hwpf.extractor.WordExtractor; import org.apache.poi.xslf.usermodel.*; import org.apache.poi.xssf.usermodel.*; import org.apache.poi.hslf.usermodel.*; import org.apache.poi.hssf.usermodel.*; import org.apache.poi.xwpf.usermodel.*; import org.springframework.stereotype.Component; import java.io.*; import java.nio.charset.StandardCharsets; import java.util.*;
public final class DocumentExtractorStrategies {private DocumentExtractorStrategies(){} static String ext(String n){int i=n==null?-1:n.lastIndexOf('.');return i<0?"":n.substring(i+1).toLowerCase(Locale.ROOT);}static void fail(Exception e){throw new DomainException("Document extraction failed",e);}
 @Component public static class Text implements DocumentTextExtractor{public boolean supports(String n,String t){return "text/plain".equals(t)||"text/markdown".equals(t);}public String extract(String n,String t,InputStream d){try{return new String(d.readAllBytes(),StandardCharsets.UTF_8);}catch(IOException e){fail(e);return "";}}}
 @Component public static class Pdf implements DocumentTextExtractor{public boolean supports(String n,String t){return "application/pdf".equals(t)||"pdf".equals(ext(n));}public String extract(String n,String t,InputStream d){try(var doc=Loader.loadPDF(d.readAllBytes())){String s=new PDFTextStripper().getText(doc);if(s.isBlank())throw new UnsupportedDocumentException("DOCUMENT_REQUIRES_OCR");return s;}catch(UnsupportedDocumentException e){throw e;}catch(Exception e){fail(e);return "";}}}
 @Component public static class Word implements DocumentTextExtractor{public boolean supports(String n,String t){return Set.of("doc","docx").contains(ext(n))||t.contains("word");}public String extract(String n,String t,InputStream d){try{StringBuilder s=new StringBuilder();if("docx".equals(ext(n))){try(var x=new XWPFDocument(d)){for(var p:x.getParagraphs())s.append(p.getText()).append('\n');for(var table:x.getTables())for(var row:table.getRows()){for(var c:row.getTableCells())s.append(c.getText()).append(" | ");s.append('\n');}}}else{try(var x=new HWPFDocument(d);var w=new WordExtractor(x)){s.append(w.getText());}}return s.toString();}catch(Exception e){fail(e);return "";}}}
 @Component public static class Excel implements DocumentTextExtractor{public boolean supports(String n,String t){return Set.of("xls","xlsx").contains(ext(n))||t.contains("excel")||t.contains("spreadsheet");}public String extract(String n,String t,InputStream d){try{StringBuilder s=new StringBuilder();if("xlsx".equals(ext(n))){try(var x=new XSSFWorkbook(d)){for(var sh:x){s.append("# Sheet: ").append(sh.getSheetName()).append('\n');for(var r:sh)for(var c:r)s.append(c.toString()).append(" | ");s.append('\n');}}}else{try(var x=new HSSFWorkbook(d)){for(var sh:x){s.append("# Sheet: ").append(sh.getSheetName()).append('\n');for(var r:sh)for(var c:r)s.append(c.toString()).append(" | ");s.append('\n');}}}return s.toString();}catch(Exception e){fail(e);return "";}}}
 @Component public static class PowerPoint implements DocumentTextExtractor{public boolean supports(String n,String t){return Set.of("ppt","pptx").contains(ext(n))||t.contains("presentation")||t.contains("powerpoint");}public String extract(String n,String t,InputStream d){try{StringBuilder s=new StringBuilder();if("pptx".equals(ext(n))){try(var x=new XMLSlideShow(d)){int i=1;for(var slide:x.getSlides()){s.append("[Slide ").append(i++).append("]\n");for(var sh:slide.getShapes())if(sh instanceof XSLFTextShape tx)s.append(tx.getText()).append('\n');}}}else{try(var x=new HSLFSlideShow(d)){int i=1;for(var slide:x.getSlides()){s.append("[Slide ").append(i++).append("]\n");for(var sh:slide.getShapes())if(sh instanceof HSLFTextShape tx)s.append(tx.getText()).append('\n');}}}return s.toString();}catch(Exception e){fail(e);return "";}}}
}
