/* eslint-disable no-empty */
import {useEffect,useRef,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {systemHelpApi} from '../../help/systemHelpApi'
import kute from '../../../assets/Kute.gif'
import {clampKutePosition,exceededDragThreshold} from '../model/kuteDrag'
import './ai-assistant.css'

const routes={PROFILE:'/profile',NOTIFICATIONS:'/notifications',QUESTION_CREATE:'/questions/new',MY_QUESTIONS:'/questions/mine',AI_GENERATE:'/ai/generate',AI_DOCUMENTS:'/ai/documents',QUESTION_REVIEW:'/review',SUBJECTS:'/subjects',EXAM_MATRICES:'/exam-matrices',USERS:'/admin/users',FACULTIES:'/admin/faculties',SYSTEM_SETTINGS:'/admin/settings',CONTACT_REQUESTS:'/admin/contact'}
const quick=['Làm sao tạo câu hỏi?','Làm sao tạo đề?','Hôm nay mình nên bắt đầu từ đâu?']
const KEY='hau-qm-kute-position'

export function AiAssistantWidget({visible=true}){
 const navigate=useNavigate()
 const[open,setOpen]=useState(false),[input,setInput]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const[position,setPosition]=useState(()=>{try{return clampKutePosition(JSON.parse(localStorage.getItem(KEY))||{x:window.innerWidth-96,y:window.innerHeight-126})}catch{return clampKutePosition({x:window.innerWidth-96,y:window.innerHeight-126})}})
 const widget=useRef(null),drag=useRef(null),live=useRef(position),frame=useRef(0),suppressClick=useRef(false),end=useRef(null)
 function paint(next){live.current=next;if(frame.current)return;frame.current=requestAnimationFrame(()=>{frame.current=0;if(widget.current)widget.current.style.transform=`translate3d(${live.current.x}px, ${live.current.y}px, 0)`})}
 useEffect(()=>{paint(position);const onResize=()=>{const next=clampKutePosition(live.current);paint(next);setPosition(next);try{localStorage.setItem(KEY,JSON.stringify(next))}catch{}};window.addEventListener('resize',onResize);return()=>{window.removeEventListener('resize',onResize);if(frame.current)cancelAnimationFrame(frame.current)}},[position])
 useEffect(()=>{end.current?.scrollIntoView({block:'end'})},[messages,busy])
 function down(event){if(event.button!==undefined&&event.button!==0)return;event.currentTarget.setPointerCapture?.(event.pointerId);drag.current={pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,originX:live.current.x,originY:live.current.y,moved:false}}
 function move(event){const current=drag.current;if(!current||current.pointerId!==event.pointerId)return;const dx=event.clientX-current.startX,dy=event.clientY-current.startY;if(!current.moved&&!exceededDragThreshold(dx,dy))return;current.moved=true;suppressClick.current=true;paint(clampKutePosition({x:current.originX+dx,y:current.originY+dy}))}
 function finish(event){const current=drag.current;if(!current||current.pointerId!==event.pointerId)return;event.currentTarget.releasePointerCapture?.(event.pointerId);drag.current=null;if(current.moved){const finalPosition=clampKutePosition(live.current);paint(finalPosition);setPosition(finalPosition);try{localStorage.setItem(KEY,JSON.stringify(finalPosition))}catch{}}}
 function click(){if(suppressClick.current){suppressClick.current=false;return}setOpen(value=>!value)}
 async function send(value=input){const question=value.trim();if(!question||busy)return;setInput('');setBusy(true);setError('');setMessages(items=>[...items,{role:'USER',content:question}]);try{const response=await systemHelpApi.ask(question);setMessages(items=>[...items,{role:'ASSISTANT',content:response.answer||'Mình chưa có đủ thông tin để trả lời.',actions:response.actions||[],sources:response.sources||[]}])}catch(reason){setError(reason.message||'Không thể nhận phản hồi từ Kute.')}finally{setBusy(false)}}
 return <div ref={widget} className="ai-assistant-widget" hidden={!visible} style={{transform:`translate3d(${position.x}px, ${position.y}px, 0)`}}><button type="button" className="ai-assistant-fab kute-fab" aria-label="Mở Kute" aria-expanded={open} onPointerDown={down} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} onClick={click}><img className="kute-avatar" src={kute} alt="" draggable="false"/></button>{open&&<section className="ai-assistant-window" aria-label="Kute"><header><img className="kute-avatar" src={kute} alt=""/><div><strong>Kute</strong><span>Trợ lý AI HAU QM</span></div><button type="button" aria-label="Đóng Kute" onClick={()=>setOpen(false)}>×</button></header><div className="ai-assistant-messages" aria-live="polite">{!messages.length&&<div className="ai-assistant-welcome"><strong>Xin chào, mình là Kute ✨</strong><p>Mình có thể hướng dẫn HAU QM, trả lời kiến thức phổ thông và hỗ trợ theo vai trò của bạn.</p><div>{quick.map(q=><button type="button" key={q} onClick={()=>void send(q)}>{q}</button>)}</div></div>}{messages.map((message,index)=><article key={`${message.role}-${index}`} className={message.role.toLowerCase()}><small>{message.role==='USER'?'Bạn':'Kute'}</small><p>{message.content}</p>{message.actions?.map(action=>routes[action.routeKey]&&<button type="button" className="ai-assistant-action" key={action.routeKey} onClick={()=>{navigate(routes[action.routeKey]);setOpen(false)}}>{action.label}</button>)}{message.sources?.length>0&&<small>Nguồn: {message.sources.map(source=>source.title).join(', ')}</small>}</article>)}{busy&&<p className="ai-assistant-typing">Kute đang chuẩn bị câu trả lời…</p>}<span ref={end}/></div><form onSubmit={event=>{event.preventDefault();void send()}}><textarea value={input} maxLength={1000} onChange={event=>setInput(event.target.value)} placeholder="Hỏi Kute..." aria-label="Câu hỏi cho Kute" rows="2"/><button type="submit" disabled={busy||!input.trim()} aria-label="Gửi câu hỏi">➤</button></form>{error&&<p className="ai-assistant-error" role="alert">{error}</p>}</section>}</div>
}
