import {Link,useNavigate} from 'react-router-dom'
import {routes} from '../../constants/routes'
import {roles} from '../../constants/roles'
import {authApi} from '../../features/auth/api/authApi'
import {useAuth} from '../../features/auth/hooks/useAuth'
import {authStore} from '../../stores/authStore'
import {Icon} from '../ui'
const roleLabel={SYSTEM_ADMIN:'Quản trị viên hệ thống',SUBJECT_ADMIN:'Quản trị viên chuyên môn',USER:'Giảng viên'}
export function UserMenu(){const auth=useAuth();const navigate=useNavigate();const name=auth.currentUser?.fullName||auth.currentUser?.lecturerCode||'Người dùng';const code=auth.currentUser?.lecturerCode;const faculty=auth.currentUser?.facultyName||auth.currentUser?.faculty?.name||auth.facultyId;const initials=(name||'N').trim().split(/\s+/).slice(-2).map(part=>part[0]).join('').toUpperCase();async function logout(){const token=authStore.getRefreshToken();try{if(token)await authApi.logout(token)}finally{authStore.clear();navigate(routes.login,{replace:true})}}return <details className="user-menu"><summary aria-label="Mở menu tài khoản"><span className="user-avatar">{initials}</span><span className="profile-copy"><strong>{name}</strong><small>{roleLabel[auth.role]||'Người dùng'}{faculty?` • Khoa ${faculty}`:''}</small></span><Icon name="file" size={14}/></summary><div className="user-menu-popover"><div><strong>{name}</strong>{code&&name!==code&&<span>{code}</span>}<span>{roleLabel[auth.role]||auth.role||'Người dùng'}{faculty?` • Khoa ${faculty}`:''}</span></div><Link to={routes.profile}>Hồ sơ cá nhân</Link><Link to={routes.help}>Trung tâm trợ giúp</Link>{auth.role===roles.SYSTEM_ADMIN&&<Link to={routes.settings}>Cài đặt hệ thống</Link>}<button type="button" onClick={logout}><Icon name="logout" size={15}/>Đăng xuất</button></div></details>}
