server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: exam-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
