spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${EXAM_DB_URL}
    username: ${EXAM_DB_USERNAME}
    password: ${EXAM_DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI}

exam:
  question-service-url: ${QUESTION_SERVICE_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
