import { api } from "../../../services/api/client";
export const catalogApi = {
  subjects: () => api.get("/api/v1/subjects"),
  createSubject: (body) => api.post("/api/v1/subjects", body),
  updateSubject: (id, body) => api.put("/api/v1/subjects/" + id, body),
  deleteSubject: (id) => api.delete("/api/v1/subjects/" + id),
  chapters: (subjectId, options) =>
    api.get("/api/v1/chapters?subjectId=" + encodeURIComponent(subjectId), options),
  createChapter: (body) => api.post("/api/v1/chapters", body),
  updateChapter: (id, body) => api.put("/api/v1/chapters/" + id, body),
  deleteChapter: (id) => api.delete("/api/v1/chapters/" + id),
  topics: (chapterId, options) =>
    api.get("/api/v1/topics?chapterId=" + encodeURIComponent(chapterId), options),
  createTopic: (body) => api.post("/api/v1/topics", body),
  updateTopic: (id, body) => api.put("/api/v1/topics/" + id, body),
  deleteTopic: (id) => api.delete("/api/v1/topics/" + id),
  knowledgeItems: (topicId, options) => api.get("/api/v1/knowledge-items?topicId=" + encodeURIComponent(topicId), options),
  createKnowledgeItem: (body) => api.post("/api/v1/knowledge-items", body),
  updateKnowledgeItem: (id, body) => api.put("/api/v1/knowledge-items/" + id, body),
  deleteKnowledgeItem: (id) => api.delete("/api/v1/knowledge-items/" + id),
  lecturers: (subjectId) => api.get(`/api/v1/subjects/${subjectId}/lecturers`),
  eligibleLecturers: (subjectId, keyword = "") => api.get(`/api/v1/subjects/${subjectId}/eligible-lecturers${keyword ? `?keyword=${encodeURIComponent(keyword)}` : ""}`),
  assignLecturer: (subjectId, userId) => api.post(`/api/v1/subjects/${subjectId}/lecturers`, { userId }),
  removeLecturer: (subjectId, userId) => api.delete(`/api/v1/subjects/${subjectId}/lecturers/${userId}`),
  textbookList: (subjectId) => api.get(`/api/v1/textbook-structures?subjectId=${encodeURIComponent(subjectId)}`),
  textbookUpload: (subjectId, file) => { const body = new FormData(); body.append('subjectId', subjectId); body.append('file', file); return api.post('/api/v1/textbook-structures', body) },
  textbookGet: (id) => api.get(`/api/v1/textbook-structures/${id}`),
  textbookConfirm: (id, structure) => api.put(`/api/v1/textbook-structures/${id}/confirm`, structure),
  textbookSource: (id) => `/api/v1/textbook-structures/${id}/source`,
};
