import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { PageHeader } from "../../../components/shared/PageHeader";
import { Button, DataTable, Dialog, Input, Select, StatusBadge } from "../../../components/ui";
import { useAuth } from "../../auth/hooks/useAuth";
import { toast } from "../../notifications/store/notificationStore";
import { assignmentsApi } from "../api/assignmentsApi";
import { catalogApi } from "../api/catalogApi";
import "./assignments.css";

const empty = { subjectId:"",chapterId:"",topicId:"",knowledgeItemId:"",lecturerId:"",requiredQuestionCount:1,requiredEasy:1,requiredMedium:0,requiredHard:0,deadline:"",note:"" };

export function AssignmentsPage() {
  const { role }=useAuth(); const admin=role==="SUBJECT_ADMIN";
  const [items,setItems]=useState([]);const[subjects,setSubjects]=useState([]);const[chapters,setChapters]=useState([]);const[topics,setTopics]=useState([]);const[knowledge,setKnowledge]=useState([]);const[lecturers,setLecturers]=useState([]);
  const [form,setForm]=useState(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[filter,setFilter]=useState("");
  async function load(){try{const [a,s]=await Promise.all([assignmentsApi.list(),catalogApi.subjects()]);setItems(a||[]);setSubjects(s||[])}catch(e){setError(e.message)}}
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[]);
  useEffect(()=>{if(!form?.subjectId)return;Promise.all([catalogApi.chapters(form.subjectId),admin?catalogApi.eligibleLecturers(form.subjectId):Promise.resolve([])]).then(([c,l])=>{setChapters(c||[]);setLecturers(l||[])}).catch(e=>setError(e.message))},[form?.subjectId,admin]);
  useEffect(()=>{if(!form?.chapterId)return;catalogApi.topics(form.chapterId).then(setTopics).catch(e=>setError(e.message))},[form?.chapterId]);
  useEffect(()=>{if(!form?.topicId)return;catalogApi.knowledgeItems(form.topicId).then(setKnowledge).catch(e=>setError(e.message))},[form?.topicId]);
  const subjectNames=useMemo(()=>new Map(subjects.map(x=>[x.id,`${x.code} - ${x.name}`])),[subjects]);
  const filtered=items.filter(x=>!filter||x.status===filter);
  async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError("");try{const body={...form,chapterId:form.chapterId||null,topicId:form.topicId||null,knowledgeItemId:form.knowledgeItemId||null,requiredQuestionCount:Number(form.requiredQuestionCount),requiredEasy:Number(form.requiredEasy),requiredMedium:Number(form.requiredMedium),requiredHard:Number(form.requiredHard)};if(form.id)await assignmentsApi.update(form.id,body);else await assignmentsApi.create(body);toast.success("Đã lưu phân công câu hỏi.");setForm(null);await load()}catch(reason){setError(reason.message)}finally{setBusy(false)}}
  const columns=[{key:"subjectId",header:"Môn học",render:x=>subjectNames.get(x.subjectId)||x.subjectId},{key:"lecturerId",header:"Giảng viên",render:x=>x.lecturerId},{key:"requiredQuestionCount",header:"Yêu cầu",render:x=><span>{x.requiredQuestionCount} câu · E/M/H {x.requiredEasy}/{x.requiredMedium}/{x.requiredHard}</span>},{key:"progress",header:"Tiến độ",render:x=><span>{x.progress?.approved||0}/{x.requiredQuestionCount} đã duyệt</span>},{key:"deadline",header:"Hạn"},{key:"status",header:"Trạng thái",render:x=><StatusBadge status={x.status}/>}];
  if(!admin)columns.push({key:"action",header:"Thao tác",render:x=><Link to={`/questions/new?assignmentId=${x.id}&subjectId=${x.subjectId}&chapterId=${x.chapterId||""}&topicId=${x.topicId||""}&knowledgeItemId=${x.knowledgeItemId||""}`}><Button variant="secondary">Tạo câu hỏi</Button></Link>});
  else columns.push({key:"action",header:"Thao tác",render:x=><Button variant="ghost" disabled={(x.progress?.total||0)>0} onClick={()=>setForm({...x})}>Sửa</Button>});
  return <section><PageHeader title={admin?"Phân công câu hỏi":"Công việc được giao"} description={admin?"Giao chỉ tiêu theo môn học, taxonomy, độ khó và thời hạn.":"Tiến độ được tính tự động từ câu hỏi đã liên kết; chỉ câu APPROVED mới hoàn thành chỉ tiêu."} actions={admin&&<Button onClick={()=>setForm({...empty})}>Tạo phân công</Button>}/><div className="assignment-toolbar"><Select label="Lọc trạng thái" value={filter} onChange={e=>setFilter(e.target.value)} options={[{value:"",label:"Tất cả"},...['ASSIGNED','IN_PROGRESS','SUBMITTED','COMPLETED','OVERDUE'].map(value=>({value,label:value}))]}/></div>{error&&<p className="request-error" role="alert">{error}</p>}<div className="surface assignment-table"><DataTable rows={filtered} columns={columns} emptyTitle="Chưa có công việc được giao."/></div>
  <Dialog open={Boolean(form)} title={form?.id?"Sửa phân công":"Tạo phân công"} onClose={()=>!busy&&setForm(null)}><form className="assignment-form" onSubmit={save}><Select label="Môn học" required value={form?.subjectId||""} onChange={e=>setForm({...form,subjectId:e.target.value,chapterId:"",topicId:"",knowledgeItemId:"",lecturerId:""})} options={[{value:"",label:"Chọn môn"},...subjects.map(x=>({value:x.id,label:`${x.code} - ${x.name}`}))]}/><Select label="Giảng viên" required value={form?.lecturerId||""} onChange={e=>setForm({...form,lecturerId:e.target.value})} options={[{value:"",label:"Chọn giảng viên"},...lecturers.map(x=>({value:x.userId,label:`${x.lecturerCode} - ${x.fullName}`}))]}/><Select label="Chương" value={form?.chapterId||""} onChange={e=>setForm({...form,chapterId:e.target.value,topicId:"",knowledgeItemId:""})} options={[{value:"",label:"Toàn môn"},...chapters.map(x=>({value:x.id,label:x.name}))]}/><Select label="Chủ đề" value={form?.topicId||""} onChange={e=>setForm({...form,topicId:e.target.value,knowledgeItemId:""})} options={[{value:"",label:"Không giới hạn"},...topics.map(x=>({value:x.id,label:x.name}))]}/><Select label="Nội dung kiến thức" value={form?.knowledgeItemId||""} onChange={e=>setForm({...form,knowledgeItemId:e.target.value})} options={[{value:"",label:"Không giới hạn"},...knowledge.map(x=>({value:x.id,label:x.name}))]}/><div className="assignment-counts"><Input label="Tổng số câu" name="requiredQuestionCount" type="number" min="1" value={form?.requiredQuestionCount||1} onChange={e=>setForm({...form,requiredQuestionCount:e.target.value})}/><Input label="EASY" type="number" min="0" value={form?.requiredEasy||0} onChange={e=>setForm({...form,requiredEasy:e.target.value})}/><Input label="MEDIUM" type="number" min="0" value={form?.requiredMedium||0} onChange={e=>setForm({...form,requiredMedium:e.target.value})}/><Input label="HARD" type="number" min="0" value={form?.requiredHard||0} onChange={e=>setForm({...form,requiredHard:e.target.value})}/></div><Input label="Deadline" type="date" required value={form?.deadline||""} onChange={e=>setForm({...form,deadline:e.target.value})}/><label className="field"><span>Ghi chú</span><textarea maxLength="1000" value={form?.note||""} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setForm(null)}>Hủy</Button><Button type="submit" loading={busy}>Lưu phân công</Button></div></form></Dialog></section>;
}
