import { useEffect, useState } from "react";
import { PageHeader } from "../../../components/shared/PageHeader";
import { Loading, Select } from "../../../components/ui";
import { api } from "../../../services/api/client";
import { catalogApi } from "../api/catalogApi";
import "./coverage.css";

function percent(summary) { return summary?.percentage == null ? "Chưa cấu hình target" : `${summary.percentage}%`; }

export function CoveragePage() {
  const [subjects,setSubjects]=useState([]);const[selected,setSelected]=useState("");const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{catalogApi.subjects().then(values=>{setSubjects(values||[]);setSelected(values?.[0]?.id||"")}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  useEffect(()=>{if(!selected)return undefined;const timer=setTimeout(()=>{setLoading(true);api.get(`/api/v1/coverage/subjects/${selected}`).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},0);return()=>clearTimeout(timer)},[selected]);
  return <section className="coverage-page"><PageHeader title="Phân tích độ phủ kiến thức" description="Chỉ tính câu hỏi APPROVED và đối chiếu target EASY/MEDIUM/HARD đã cấu hình tại từng nội dung kiến thức."/><div className="surface coverage-controls"><Select label="Môn học" value={selected} onChange={e=>setSelected(e.target.value)} options={subjects.map(s=>({value:s.id,label:`${s.code} - ${s.name}`}))}/>{data&&<article className="coverage-overall"><span>Overall Coverage</span><strong>{percent(data.overall)}</strong><small>{data.overall.approvedQuestions} câu APPROVED / target {data.overall.targetQuestions}{data.overall.unconfiguredItems?` · ${data.overall.unconfiguredItems} mục chưa cấu hình target`:""}</small></article>}</div>{error&&<p className="request-error" role="alert">{error}</p>}{loading?<Loading label="Đang tính độ phủ"/>:data&&<div className="coverage-tree">{data.chapters.map(chapter=><details className="surface coverage-node" key={chapter.id} open><summary><span><strong>{chapter.code} · {chapter.name}</strong><small>{chapter.coverage.approvedQuestions} câu APPROVED</small></span><b>{percent(chapter.coverage)}</b></summary><div>{chapter.topics.map(topic=><details className="coverage-topic" key={topic.id}><summary><span>{topic.code} · {topic.name}</span><b>{percent(topic.coverage)}</b></summary><div className="coverage-items">{topic.knowledgeItems.map(item=><article key={item.id}><header><span><strong>{item.name}</strong><small>{item.code}</small></span><b>{item.percentage==null?"Chưa có target":`${item.percentage}%`}</b></header><div className="difficulty-grid"><span>EASY <b>{item.easy}/{item.targetEasy}</b></span><span>MEDIUM <b>{item.medium}/{item.targetMedium}</b></span><span>HARD <b>{item.hard}/{item.targetHard}</b></span></div>{item.missing.length?<p className="coverage-missing">Thiếu: {item.missing.join(" · ")}</p>:item.targetTotal>0?<p className="coverage-complete">Đã đạt target cấu hình.</p>:<p className="coverage-unconfigured">Cần cấu hình target để tính phần trăm.</p>}</article>)}{!topic.knowledgeItems.length&&<p>Chưa có nội dung kiến thức.</p>}</div></details>)}</div></details>)}</div>} {data&&<p className="coverage-formula">{data.formula}</p>}</section>;
}
