import { useEffect, useRef, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { Button, Dialog, Loading } from '../../../components/ui';
import { PageHeader } from '../../../components/shared/PageHeader';
import { useAuth } from '../../auth/hooks/useAuth';
import { questionsApi } from '../api/questionsApi';
import { QuestionPreview } from '../components/QuestionPreview';
import { ReviewError } from '../components/ReviewError';
import { formatDateTime } from '../model/questionModel';
import { canReview, reviewActions } from '../model/reviewModel';
import { enumLabel, questionTypeLabels, sourceLabels } from '../../../utils/enumLabels';

export function QuestionReviewPage() { const { id } = useParams(); return <ReviewDetail key={id} id={id} />; }
function ReviewDetail({ id }) {
  const auth = useAuth(); const [params] = useSearchParams(); const [state, setState] = useState({ loading: true }); const [refresh, setRefresh] = useState(0); const [action, setAction] = useState(null); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState(''); const submitting = useRef(false);
  useEffect(() => { let current = true; questionsApi.get(id).then(question => current && setState({ question })).catch(error => current && setState({ error })); return () => { current = false; }; }, [id, refresh]);
  async function confirm(event) { event.preventDefault(); if (submitting.current || !canReview(state.question, auth) || !action || (reviewActions[action].required && !reason.trim())) return; submitting.current = true; setBusy(true); try { const updated = await questionsApi[action](id, reason.trim()); setState({ question: { ...state.question, ...updated } }); setSuccess(`${reviewActions[action].label} thành công.`); setAction(null); } catch (error) { setAction(null); setState({ error }); } finally { submitting.current = false; setBusy(false); } }
  if (state.loading) return <div className="question-state"><Loading label="Đang tải câu hỏi xét duyệt" /></div>; if (state.error) return <ReviewError error={state.error} onRetry={() => { setState({ loading: true }); setRefresh(value => value + 1); }} />;
  const q = state.question; const selected = reviewActions[action]; const back = `/review${params.toString() ? `?${params}` : ''}`;
  return <section className="review-workspace"><PageHeader title="Xét duyệt câu hỏi" description="Đối chiếu nội dung, phân loại và đáp án trước khi đưa ra quyết định." actions={<Link to={back}>← Về hàng đợi</Link>} />{success && <p className="review-success" role="status">{success}</p>}<div className="surface question-detail"><div><QuestionPreview question={{ ...q, options: [...q.options].sort((a, b) => a.sortOrder - b.sortOrder) }} /></div><aside><h3>Thông tin câu hỏi</h3><dl><Info label="Mã câu hỏi" value={q.id} /><Info label="Nguồn" value={enumLabel(q.source, sourceLabels)} /><Info label="Tác giả" value={q.createdBy} /><Info label="Khoa" value={q.facultyId} /><Info label="Môn học" value={q.subjectName || q.subjectId} /><Info label="Chương" value={q.chapterName || q.chapterId} /><Info label="Chủ đề" value={q.topicName || q.topicId} /><Info label="Loại câu hỏi" value={enumLabel(q.type, questionTypeLabels)} /><Info label="Đáp án đúng" value={q.options.filter(option => option.correct).map(option => option.label).join(', ')} /><Info label="Ngày tạo" value={formatDateTime(q.createdAt)} /></dl></aside></div><section className="surface review-history"><h2>Lịch sử xét duyệt</h2>{!q.reviewHistory?.length ? <p>Chưa có quyết định xét duyệt.</p> : <ol>{q.reviewHistory.map(item => <li key={item.id}><div><strong>{item.action}</strong><time dateTime={item.timestamp}>{formatDateTime(item.timestamp)}</time></div><small>Người xét duyệt: {item.reviewerId}</small><p>{item.comment || 'Không có nhận xét.'}</p></li>)}</ol>}</section>{canReview(q, auth) && <footer className="review-actions"><span>Đang chờ quyết định xét duyệt</span><div>{['requestRevision', 'reject', 'approve'].map(key => <Button key={key} disabled={busy} variant={key === 'approve' ? 'primary' : key === 'reject' ? 'danger' : 'secondary'} onClick={() => { setReason(''); setAction(key); }}>{reviewActions[key].label}</Button>)}</div></footer>}<Dialog open={Boolean(action)} title={selected?.title || 'Xét duyệt'} subtitle={selected?.description} onClose={() => { if (!busy) setAction(null); }} footer={selected && <><Button variant="secondary" disabled={busy} onClick={() => setAction(null)}>Hủy</Button><Button variant={action === 'reject' ? 'danger' : 'primary'} loading={busy} disabled={busy || (selected.required && !reason.trim())} onClick={confirm}>{selected.label}</Button></>}>{selected && <label className="field"><span>{selected.required ? 'Lý do / nhận xét (bắt buộc)' : 'Nhận xét (không bắt buộc)'}</span><textarea rows="6" required={selected.required} disabled={busy} value={reason} onChange={event => setReason(event.target.value)} /></label>}</Dialog></section>;
}
function Info({ label, value }) { return <div><dt>{label}</dt><dd>{value || '—'}</dd></div>; }
