/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, ConfirmDialog, Loading } from '../../../components/ui';
import { PageHeader } from '../../../components/shared/PageHeader';
import { useAuth } from '../../auth/hooks/useAuth';
import { questionsApi } from '../api/questionsApi';
import { QuestionPreview } from '../components/QuestionPreview';
import { canArchive, canEdit } from '../model/questionModel';
import { enumLabel, questionTypeLabels, sourceLabels } from '../../../utils/enumLabels';

export function QuestionDetailPage() { const { id } = useParams(); const auth = useAuth(); const [question, setQuestion] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(null); const [action, setAction] = useState(null); const load = useCallback(async () => { setLoading(true); setError(null); try { setQuestion(await questionsApi.get(id)); } catch (reason) { setError(reason); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]); async function confirm() { if (busy) return; setBusy(true); try { await questionsApi[action](id); setAction(null); await load(); } catch (reason) { setAction(null); setError(reason); } finally { setBusy(false); } }
  if (loading) return <div className="question-state"><Loading label="Đang tải chi tiết câu hỏi" /></div>; if (error) return <div className="question-state request-error" role="alert"><strong>Không thể tải câu hỏi</strong><span>{error.message}</span><Button onClick={load}>Thử lại</Button></div>;
  return <section><PageHeader title="Chi tiết câu hỏi" description="Xem nội dung, nguồn và trạng thái workflow hiện tại." actions={<div className="page-actions">{auth.role === 'SUBJECT_ADMIN' && <Link to={`/review/${id}`} className="button button-primary">Mở workspace xét duyệt</Link>}{canEdit(question, auth) && <><Link to={`/questions/${id}/edit`}><Button variant="secondary">Chỉnh sửa</Button></Link><Button onClick={() => setAction('submit')}>Gửi duyệt</Button></>}{canArchive(question, auth) && <Button variant="secondary" onClick={() => setAction('archive')}>Lưu trữ</Button>}</div>} /><div className="surface question-detail"><QuestionPreview question={question} /><aside><h3>Thông tin</h3><dl><Info label="Người tạo" value={question.createdByName || question.createdBy} /><Info label="Khoa" value={question.facultyId} /><Info label="Chương" value={question.chapterName || question.chapterId} /><Info label="Chủ đề" value={question.topicName || question.topicId} /><Info label="Loại" value={enumLabel(question.type, questionTypeLabels)} /><Info label="Nguồn" value={enumLabel(question.source, sourceLabels)} /></dl></aside></div><ConfirmDialog loading={busy} open={Boolean(action)} danger={action === 'archive'} title={action === 'archive' ? 'Lưu trữ câu hỏi?' : 'Gửi câu hỏi xét duyệt?'} description="Question Service sẽ xác thực trạng thái và quyền sở hữu trước khi thực hiện." confirmLabel={action === 'archive' ? 'Lưu trữ' : 'Gửi duyệt'} onClose={() => { if (!busy) setAction(null); }} onConfirm={confirm} /></section>;
}
function Info({ label, value }) { return <div><dt>{label}</dt><dd>{value || '—'}</dd></div>; }
