import {useCallback,useEffect,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {Button,ConfirmDialog,Loading} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {roles} from '../../../constants/roles'
import {useAuth} from '../../auth/hooks/useAuth'
import {questionsApi} from '../api/questionsApi'
import {QuestionPreview} from '../components/QuestionPreview'
import {editableStatus} from '../model/questionModel'

export function QuestionDetailPage(){const{id}=useParams();const auth=useAuth();const[question,setQuestion]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState(null);const[action,setAction]=useState(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setQuestion(await questionsApi.get(id))}catch(reason){setError(reason)}finally{setLoading(false)}},[id]);useEffect(()=>{const task=setTimeout(load,0);return()=>clearTimeout(task)},[load]);async function confirm(){const selected=action;setAction(null);try{await questionsApi[selected](id);await load()}catch(reason){setError(reason)}}if(loading)return <div className="question-state"><Loading label="Đang tải chi tiết câu hỏi"/></div>;if(error)return <div className="question-state request-error" role="alert"><strong>Không thể tải câu hỏi</strong><span>{error.message}</span><Button onClick={load}>Thử lại</Button></div>;const ownerActions=auth.role===roles.USER;return <section><PageHeader title="Chi tiết câu hỏi" description="Xem nội dung, nguồn và trạng thái workflow hiện tại." actions={<div className="page-actions">{ownerActions&&editableStatus(question.status)&&<><Link to={`/questions/${id}/edit`}><Button variant="secondary">Chỉnh sửa</Button></Link><Button onClick={()=>setAction('submit')}>Gửi duyệt</Button></>}{ownerActions&&question.status==='APPROVED'&&<Button variant="secondary" onClick={()=>setAction('archive')}>Lưu trữ</Button>}</div>}/><div className="surface question-detail"><QuestionPreview question={question}/><aside><h3>Thông tin</h3><dl><Info label="Người tạo" value={question.createdByName||question.createdBy}/><Info label="Khoa" value={question.facultyId}/><Info label="Chương" value={question.chapterName||question.chapter?.name}/><Info label="Chủ đề" value={question.topicName||question.topic?.name}/><Info label="Loại" value={question.type}/><Info label="Nguồn" value={question.source}/></dl>{question.source==='AI'&&<p className="ai-review-note">Câu hỏi do AI tạo vẫn phải đi qua workflow xét duyệt; nguồn AI không đồng nghĩa đã được phê duyệt.</p>}</aside></div><ConfirmDialog open={Boolean(action)} danger={action==='archive'} title={action==='archive'?'Lưu trữ câu hỏi?':'Gửi câu hỏi xét duyệt?'} description="Question Service sẽ xác thực trạng thái và quyền sở hữu trước khi thực hiện." confirmLabel={action==='archive'?'Lưu trữ':'Gửi duyệt'} onClose={()=>setAction(null)} onConfirm={confirm}/></section>}
function Info({label,value}){return <div><dt>{label}</dt><dd>{value||'—'}</dd></div>}
