import {useCallback,useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {Button,ConfirmDialog,Drawer,Loading} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {routes} from '../../../constants/routes'
import {roles} from '../../../constants/roles'
import {useAuth} from '../../auth/hooks/useAuth'
import {questionsApi} from '../api/questionsApi'
import {QuestionFilters} from '../components/QuestionFilters'
import {QuestionPagination} from '../components/QuestionPagination'
import {QuestionPreview} from '../components/QuestionPreview'
import {QuestionTable} from '../components/QuestionTable'
import {useQuestionCatalogs} from '../hooks/useQuestionCatalogs'
import {normalizePage} from '../model/questionModel'

const initialFilters={facultyId:'',subjectId:'',chapterId:'',topicId:'',difficulty:'',status:'',source:'',keyword:''}
export function QuestionListPage(){const auth=useAuth();const isOwnerView=auth.role===roles.USER;const creatorId=auth.currentUser?.id;const[draft,setDraft]=useState(initialFilters);const[query,setQuery]=useState(initialFilters);const[page,setPage]=useState(0);const[data,setData]=useState(normalizePage());const[loading,setLoading]=useState(true);const[error,setError]=useState(null);const[preview,setPreview]=useState(null);const[confirmation,setConfirmation]=useState(null);const catalogs=useQuestionCatalogs(draft.subjectId,draft.chapterId);const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(normalizePage(await questionsApi.list({...query,creator:isOwnerView?creatorId:undefined,page,size:10})))}catch(reason){setError(reason)}finally{setLoading(false)}},[creatorId,isOwnerView,page,query]);useEffect(()=>{const task=setTimeout(load,0);return()=>clearTimeout(task)},[load]);async function confirmAction(){const{action,question}=confirmation;setConfirmation(null);try{await questionsApi[action](question.id);await load()}catch(reason){setError(reason)}}return <section><PageHeader title={isOwnerView?'Câu hỏi của tôi':'Ngân hàng câu hỏi'} description={isOwnerView?'Theo dõi, chỉnh sửa và gửi duyệt câu hỏi do bạn tạo.':'Tra cứu ngân hàng câu hỏi trong phạm vi khoa được cấp.'} actions={isOwnerView&&<Link to={routes.newQuestion}><Button>Tạo câu hỏi</Button></Link>}/><QuestionFilters filters={draft} catalogs={catalogs} onChange={setDraft} onSubmit={event=>{event.preventDefault();setPage(0);setQuery(draft)}}/><div className="surface question-table-surface">{loading?<div className="question-state"><Loading label="Đang tải câu hỏi"/></div>:error?<div className="question-state request-error" role="alert"><strong>Không thể tải câu hỏi</strong><span>{error.message}</span><Button variant="secondary" onClick={load}>Thử lại</Button></div>:<><QuestionTable questions={data.items} isOwnerView={isOwnerView} onPreview={setPreview} onAction={(action,question)=>setConfirmation({action,question})}/><QuestionPagination {...data} onChange={setPage}/></>}</div><Drawer open={Boolean(preview)} title="Xem trước câu hỏi" onClose={()=>setPreview(null)}><QuestionPreview question={preview}/></Drawer><ConfirmDialog open={Boolean(confirmation)} danger={confirmation?.action==='archive'} title={confirmation?.action==='archive'?'Lưu trữ câu hỏi?':'Gửi câu hỏi xét duyệt?'} description={confirmation?.action==='archive'?'Câu hỏi sẽ được chuyển qua action archive của Question Service.':'Question Service sẽ kiểm tra workflow trước khi chuyển sang chờ duyệt.'} confirmLabel={confirmation?.action==='archive'?'Lưu trữ':'Gửi duyệt'} onClose={()=>setConfirmation(null)} onConfirm={confirmAction}/></section>}
