import { routes } from "../../constants/routes";

export const CURRENT_ONBOARDING_VERSION = 1;
const step = (id, route, target, title, description, position = "bottom") => ({
  id,
  route,
  target,
  title,
  description,
  position,
});

export const onboardingTours = {
  USER: [
    step(
      "dashboard",
      routes.dashboard,
      '[data-tour="page-heading"]',
      "Chào mừng bạn đến với HAU QM",
      "Đây là không gian làm việc chính giúp bạn quản lý câu hỏi, học liệu và các tác vụ AI.",
    ),
    step(
      "dashboard-kpi",
      routes.dashboard,
      '[data-tour="dashboard-kpi"]',
      "Thống kê câu hỏi",
      "Bạn có thể theo dõi nhanh tổng số câu hỏi, câu đã duyệt, đang chờ và cần chỉnh sửa.",
    ),
    step(
      "my-questions",
      routes.myQuestions,
      '[data-tour="my-questions-menu"]',
      "Quản lý câu hỏi",
      "Theo dõi toàn bộ câu hỏi do bạn tạo và trạng thái thẩm định.",
    ),
    step(
      "new-question",
      routes.newQuestion,
      '[data-tour="new-question-menu"]',
      "Tạo câu hỏi mới",
      "Chọn môn học, chương và chủ đề trước khi nhập nội dung, phương án và gửi phê duyệt.",
    ),
    step(
      "question-image",
      routes.newQuestion,
      '[data-tour="question-image"]',
      "Nội dung đa phương tiện",
      "Bạn có thể thêm ảnh minh họa cho câu hỏi hoặc từng phương án trả lời.",
    ),
    step(
      "ai",
      routes.generate,
      '[data-tour="ai-menu"]',
      "Trợ lý AI",
      "AI hỗ trợ phân tích học liệu và tạo câu hỏi nháp để bạn kiểm tra, chỉnh sửa trước khi sử dụng.",
    ),
    step(
      "documents",
      routes.documents,
      '[data-tour="page-heading"]',
      "Tài liệu của tôi",
      "Tải và quản lý học liệu dùng cho quá trình tạo câu hỏi bằng AI.",
    ),
    step(
      "notifications",
      routes.notifications,
      '[data-tour="notifications-menu"]',
      "Thông báo",
      "Nhận phản hồi phê duyệt, yêu cầu chỉnh sửa và trạng thái các tác vụ trong hệ thống.",
    ),
    step(
      "profile",
      routes.profile,
      '[data-tour="profile-menu"]',
      "Hồ sơ cá nhân",
      "Quản lý thông tin cá nhân, ảnh đại diện và thông tin học thuật.",
    ),
    step(
      "help",
      routes.help,
      '[data-tour="help-menu"]',
      "Trung tâm trợ giúp",
      "Bạn có thể xem lại hướng dẫn này hoặc tìm tài liệu hỗ trợ bất kỳ lúc nào.",
    ),
  ],
  SUBJECT_ADMIN: [
    step(
      "dashboard",
      routes.dashboard,
      '[data-tour="page-heading"]',
      "Không gian quản trị chuyên môn",
      "Theo dõi hoạt động câu hỏi và nội dung học thuật trong Khoa được phân công.",
    ),
    step(
      "subjects",
      routes.subjects,
      '[data-tour="subjects-menu"]',
      "Môn học",
      "Quản lý các môn học thuộc phạm vi Khoa của bạn.",
    ),
    step(
      "knowledge",
      routes.knowledge,
      '[data-tour="knowledge-menu"]',
      "Cấu trúc kiến thức",
      "Tổ chức nội dung theo Môn học, Chương và Chủ đề.",
    ),
    step(
      "questions",
      routes.questions,
      '[data-tour="questions-menu"]',
      "Ngân hàng câu hỏi",
      "Theo dõi câu hỏi thuộc phạm vi chuyên môn.",
    ),
    step(
      "review",
      routes.review,
      '[data-tour="review-menu"]',
      "Duyệt câu hỏi",
      "Kiểm tra câu hỏi do giảng viên gửi và đưa ra quyết định phù hợp.",
    ),
    step(
      "coverage",
      routes.coverage,
      '[data-tour="coverage-menu"]',
      "Độ bao phủ kiến thức",
      "Theo dõi mức độ phân bố câu hỏi khi dữ liệu hệ thống hỗ trợ.",
    ),
    step(
      "matrices",
      routes.matrices,
      '[data-tour="matrices-menu"]',
      "Ma trận đề",
      "Xây dựng cấu trúc phân bố câu hỏi phục vụ tạo phiên bản đề.",
    ),
    step(
      "notifications",
      routes.notifications,
      '[data-tour="notifications-menu"]',
      "Thông báo",
      "Nhận thông tin về câu hỏi, AI và các hoạt động liên quan.",
    ),
    step(
      "help",
      routes.help,
      '[data-tour="help-menu"]',
      "Trung tâm trợ giúp",
      "Bạn có thể chạy lại hướng dẫn bất kỳ lúc nào tại đây.",
    ),
  ],
  SYSTEM_ADMIN: [
    step(
      "dashboard",
      routes.dashboard,
      '[data-tour="page-heading"]',
      "Không gian quản trị hệ thống",
      "Theo dõi người dùng, Khoa và các hoạt động quản trị chính.",
    ),
    step(
      "faculties",
      routes.faculties,
      '[data-tour="faculty-menu"]',
      "Quản lý Khoa",
      "Tạo và quản lý danh sách Khoa được sử dụng trong toàn hệ thống.",
    ),
    step(
      "users",
      routes.users,
      '[data-tour="lecturers-menu"]',
      "Quản lý người dùng",
      "Quản lý tài khoản, vai trò, Khoa và trạng thái người dùng.",
    ),
    step(
      "registrations",
      routes.registrations,
      '[data-tour="registrations-menu"]',
      "Tài khoản chờ phê duyệt",
      "Xem yêu cầu đăng ký và quyết định Khoa, vai trò trước khi kích hoạt.",
    ),
    step(
      "contacts",
      routes.contactAdmin,
      '[data-tour="contact-menu"]',
      "Yêu cầu liên hệ",
      "Tiếp nhận và phản hồi các yêu cầu hỗ trợ gửi từ trang công khai.",
    ),
    step(
      "email",
      routes.settings,
      '[data-tour="email-settings"]',
      "Cấu hình Email",
      "Kiểm tra cấu hình gửi email của hệ thống mà không hiển thị mật khẩu.",
    ),
    step(
      "notifications",
      routes.notifications,
      '[data-tour="notifications-menu"]',
      "Thông báo hệ thống",
      "Theo dõi các thông tin quản trị và sự kiện quan trọng.",
    ),
    step(
      "profile",
      routes.profile,
      '[data-tour="profile-menu"]',
      "Hồ sơ cá nhân",
      "Quản lý thông tin tài khoản quản trị.",
    ),
    step(
      "help",
      routes.help,
      '[data-tour="help-menu"]',
      "Trung tâm trợ giúp",
      "Có thể xem lại hướng dẫn sử dụng hệ thống từ đây.",
    ),
  ],
};
