package com.questionservice.infrastructure.persistence.adapter;
import com.questionservice.application.model.*; import com.questionservice.application.port.out.QuestionRepository; import com.questionservice.domain.model.*; import com.questionservice.infrastructure.persistence.entity.QuestionEntity; import com.questionservice.infrastructure.persistence.mapper.QuestionPersistenceMapper; import com.questionservice.infrastructure.persistence.repository.QuestionJpaRepository; import jakarta.persistence.criteria.Predicate; import java.util.*; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Component;
@Component public class QuestionPersistenceAdapter implements QuestionRepository {
 private final QuestionJpaRepository repo; private final QuestionPersistenceMapper mapper; public QuestionPersistenceAdapter(QuestionJpaRepository r,QuestionPersistenceMapper m){repo=r;mapper=m;}
 public Question save(Question q){var entity=mapper.toEntity(q);repo.findById(q.id()).ifPresent(old->entity.version=old.version);return mapper.toDomain(repo.save(entity));} public Optional<Question> findById(UUID id){return repo.findById(id).map(mapper::toDomain);} public void delete(UUID id){repo.deleteById(id);} public boolean existsByAiSourceId(String id){return repo.existsByAiSourceId(id);}
 public QuestionStatistics statistics(String facultyId, UUID createdBy){long total, draft, pending, approved, revision, rejected;if(createdBy!=null){total=repo.countByCreatedBy(createdBy);draft=repo.countByCreatedByAndStatus(createdBy,QuestionStatus.DRAFT);pending=repo.countByCreatedByAndStatus(createdBy,QuestionStatus.PENDING_REVIEW);approved=repo.countByCreatedByAndStatus(createdBy,QuestionStatus.APPROVED);revision=repo.countByCreatedByAndStatus(createdBy,QuestionStatus.NEED_REVISION);rejected=repo.countByCreatedByAndStatus(createdBy,QuestionStatus.REJECTED);}else if(facultyId!=null){total=repo.countByFacultyId(facultyId);draft=repo.countByFacultyIdAndStatus(facultyId,QuestionStatus.DRAFT);pending=repo.countByFacultyIdAndStatus(facultyId,QuestionStatus.PENDING_REVIEW);approved=repo.countByFacultyIdAndStatus(facultyId,QuestionStatus.APPROVED);revision=repo.countByFacultyIdAndStatus(facultyId,QuestionStatus.NEED_REVISION);rejected=repo.countByFacultyIdAndStatus(facultyId,QuestionStatus.REJECTED);}else{total=repo.count();draft=repo.countByStatus(QuestionStatus.DRAFT);pending=repo.countByStatus(QuestionStatus.PENDING_REVIEW);approved=repo.countByStatus(QuestionStatus.APPROVED);revision=repo.countByStatus(QuestionStatus.NEED_REVISION);rejected=repo.countByStatus(QuestionStatus.REJECTED);}return new QuestionStatistics(total,draft,pending,approved,revision,rejected);}
 public PageResult<Question> search(QuestionCriteria c){Specification<QuestionEntity> spec=(root,q,cb)->{List<Predicate> p=new ArrayList<>();add(cb,p,root.get("facultyId"),c.facultyId());add(cb,p,root.get("subjectId"),c.subjectId());add(cb,p,root.get("chapterId"),c.chapterId());add(cb,p,root.get("topicId"),c.topicId());add(cb,p,root.get("difficulty"),c.difficulty());add(cb,p,root.get("status"),c.status());add(cb,p,root.get("source"),c.source());add(cb,p,root.get("createdBy"),c.createdBy());String keyword=c.keyword()==null?null:c.keyword().trim();if(keyword!=null&&!keyword.isBlank())p.add(cb.like(cb.lower(root.<String>get("content")),"%"+keyword.toLowerCase(Locale.ROOT)+"%"));return cb.and(p.toArray(Predicate[]::new));};String[] s=(c.sort()==null?"createdAt,desc":c.sort()).split(",");Sort sort=Sort.by(s.length>1&&"asc".equalsIgnoreCase(s[1])?Sort.Direction.ASC:Sort.Direction.DESC,allowedSort(s[0]));Page<QuestionEntity> page=repo.findAll(spec,PageRequest.of(Math.max(0,c.page()),Math.min(100,Math.max(1,c.size())),sort));return new PageResult<>(page.map(mapper::toDomain).getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages());}
 private static <T> void add(jakarta.persistence.criteria.CriteriaBuilder cb,List<Predicate> p,jakarta.persistence.criteria.Path<T> path,T value){if(value!=null)p.add(cb.equal(path,value));} private static String allowedSort(String value){return Set.of("createdAt","updatedAt","difficulty","status","content").contains(value)?value:"createdAt";}
}
