import {useCallback,useEffect,useState} from 'react'
import {Button,EmptyState,Loading} from '../../../components/ui'
import {PageHeader} from '../../../components/shared/PageHeader'
import {notificationsApi} from '../api/notificationsApi'
import {NotificationItem} from '../components/NotificationItem'
import {useNotifications} from '../hooks/useNotifications'
import {normalizeNotificationPage} from '../model/notificationModel'
import {notificationStore} from '../store/notificationStore'

export function NotificationsPage(){const connection=useNotifications();const[page,setPage]=useState(0);const[data,setData]=useState({items:[],page:0,totalPages:0,totalElements:0});const[loading,setLoading]=useState(true);const[error,setError]=useState(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(normalizeNotificationPage(await notificationsApi.list({page,size:20})))}catch(reason){setError(reason)}finally{setLoading(false)}},[page]);useEffect(()=>{const task=setTimeout(load,0);return()=>clearTimeout(task)},[load]);async function markAll(){try{await notificationStore.markAllRead();setData(current=>({...current,items:current.items.map(item=>({...item,isRead:true}))}))}catch(reason){setError(reason)}}function reflectRead(notification){setData(current=>({...current,items:current.items.map(item=>item.id===notification.id?{...item,isRead:true}:item)}))}return <section><PageHeader title="Thông báo" description="Lịch sử thông báo được đồng bộ từ dữ liệu bền vững của Notification Service." actions={connection.unreadCount>0&&<Button variant="secondary" onClick={markAll}>Đánh dấu tất cả đã đọc</Button>}/><div className="notification-status"><span className={`connection-state is-${connection.connectionStatus}`}>{connection.connectionStatus==='connected'?'Realtime đã kết nối':'Realtime gián đoạn · REST vẫn khả dụng'}</span><span>{connection.unreadCount} chưa đọc</span></div><div className="surface notification-page-list">{loading?<Loading label="Đang tải thông báo"/>:error?<div className="notification-error" role="alert"><strong>Không thể tải thông báo</strong><span>{error.message}</span>{error.correlationId&&<small>Mã đối chiếu: {error.correlationId}</small>}<Button variant="secondary" onClick={load}>Thử lại</Button></div>:data.items.length?data.items.map(notification=><NotificationItem key={notification.id||notification.eventId} notification={notification} onRead={reflectRead}/>):<EmptyState title="Chưa có thông báo" description="Thông báo bền vững của bạn sẽ xuất hiện tại đây."/>}</div>{data.totalPages>1&&<footer className="pagination"><span>Trang {page+1}/{data.totalPages} · {data.totalElements} thông báo</span><div><Button variant="secondary" disabled={page===0} onClick={()=>setPage(value=>value-1)}>Trước</Button><Button variant="secondary" disabled={page+1>=data.totalPages} onClick={()=>setPage(value=>value+1)}>Sau</Button></div></footer>}</section>}
