import { useEffect, useState } from 'react'
import { Button, Input } from '../../../components/ui'
import { PageHeader } from '../../../components/shared/PageHeader'
import { toast } from '../store/notificationStore'
import { telegramApi } from '../api/telegramApi'
import { useAuth } from '../../auth/hooks/useAuth'

const adminKeys = ['newUsers', 'actionable', 'systemEvents', 'loginEvents']
const subjectKeys = ['questionPending', 'questionResubmitted', 'subjectEvents']
const labels = { newUsers: 'Người dùng mới đăng ký', actionable: 'Tài khoản cần xử lý', systemEvents: 'Cảnh báo hệ thống', loginEvents: 'Đăng nhập thành công', questionPending: 'Câu hỏi mới chờ phê duyệt', questionResubmitted: 'Câu hỏi gửi duyệt lại', subjectEvents: 'Thông báo chuyên môn' }

export function TelegramPage() {
  const { role } = useAuth()
  const [status, setStatus] = useState(null), [prefs, setPrefs] = useState(null), [link, setLink] = useState(null)
  const [admin, setAdmin] = useState(null), [token, setToken] = useState(''), [username, setUsername] = useState(''), [busy, setBusy] = useState('')
  useEffect(() => { Promise.all([telegramApi.status(), telegramApi.preferences(), role === 'SYSTEM_ADMIN' ? telegramApi.admin() : Promise.resolve(null)]).then(([s,p,a]) => { setStatus(s); setPrefs(p); if (a) { setAdmin(a); setUsername(a.botUsername || '') } }).catch(() => toast.error('Không thể tải tích hợp Telegram.')) }, [role])
  useEffect(() => { if (!link || status?.connected) return undefined; const timer = window.setInterval(async () => { try { const value = await telegramApi.status(); setStatus(value); if (value.connected) { setLink(null); toast.success('Đã liên kết Telegram.') } } catch { /* manual retry remains available */ } }, 4000); return () => window.clearInterval(timer) }, [link, status?.connected])
  async function checkStatus() { setBusy('status'); try { const value = await telegramApi.status(); setStatus(value); if (value.connected) { setLink(null); toast.success('Đã liên kết Telegram.') } else toast.info('Telegram chưa xác nhận liên kết. Hãy nhấn START trong bot.') } catch { toast.error('Không thể kiểm tra trạng thái Telegram.') } finally { setBusy('') } }
  async function createLink() { const popup = window.open('about:blank', '_blank'); if (popup) popup.opener = null; setBusy('link'); try { const value = await telegramApi.link(); setLink(value); if (popup) popup.location.replace(value.url); else window.open(value.url, '_blank', 'noopener,noreferrer'); toast.success('Đã mở bot Telegram.') } catch { popup?.close(); toast.error('Không thể tạo liên kết Telegram.') } finally { setBusy('') } }
  async function savePreferences() { setBusy('prefs'); try { await telegramApi.savePreferences(prefs); toast.success('Đã lưu tùy chọn thông báo.') } catch { toast.error('Không thể lưu tùy chọn Telegram.') } finally { setBusy('') } }
  async function saveAdmin() { setBusy('admin'); try { const value = await telegramApi.saveAdmin({ botUsername: username, botToken: token || undefined, enabled: true }); setAdmin(value); setToken(''); toast.success('Đã lưu cấu hình Telegram.') } catch { toast.error('Không thể lưu cấu hình Telegram.') } finally { setBusy('') } }
  async function testAdmin() { setBusy('admin-test'); try { const value = await telegramApi.testAdmin(); setAdmin(value); setUsername(value?.botUsername || username); toast.success(`Kết nối bot hoạt động bình thường${value?.botUsername ? ` · @${value.botUsername}` : ''}.`) } catch (error) { toast.error(error.message || 'Không thể kết nối Telegram.') } finally { setBusy('') } }
  async function unlink() { try { await telegramApi.unlink(); setStatus({ connected: false }); toast.success('Đã hủy liên kết Telegram.') } catch { toast.error('Không thể hủy liên kết Telegram.') } }
  const keys = role === 'SYSTEM_ADMIN' ? adminKeys : subjectKeys
  return <section><PageHeader title="Thông báo Telegram" description="Nhận thông báo quan trọng của HAU QM ngay trên Telegram." /><div className="telegram-grid">
    <article className="surface telegram-hero"><div className="telegram-icon">✈</div><h2>Thông báo Telegram</h2><p>Bot: @{username || admin?.botUsername || 'hau_qm_bot'}</p>{status?.connected ? <><p className="telegram-connected">✓ Đã liên kết Telegram</p><p>{status.username ? `@${status.username}` : 'Tài khoản Telegram'}</p><p>Liên kết lúc: {status.linkedAt ? new Date(status.linkedAt).toLocaleString('vi-VN') : '—'}</p><div className="settings-actions"><Button variant="secondary" loading={busy === 'test'} onClick={async () => { setBusy('test'); try { await telegramApi.test(); toast.success('Đã gửi thông báo thử.') } catch { toast.error('Không thể gửi thông báo thử.') } finally { setBusy('') } }}>Test</Button><Button variant="ghost" onClick={unlink}>Hủy liên kết</Button></div></> : <><p>{link?'Đang chờ liên kết...':'Chưa liên kết.'}</p><Button loading={busy === 'link'} onClick={createLink}>Liên kết Telegram</Button>{link && <div className="telegram-link"><a href={link.url} target="_blank" rel="noreferrer">Mở lại Telegram</a><small>Liên kết dùng một lần, có hiệu lực đến {new Date(link.expiresAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}.</small><Button variant="secondary" loading={busy==='status'} onClick={checkStatus}>Kiểm tra trạng thái</Button></div>}</>}</article>
    <article className="surface telegram-guide"><span className="eyebrow">CÁCH KÍCH HOẠT</span><h2>Liên kết trong 5 bước</h2><ol><li>Nhấn “Liên kết Telegram”.</li><li>Hệ thống mở bot HAU QM.</li><li>Nhấn START trong Telegram.</li><li>Quay lại HAU QM.</li><li>Trạng thái chuyển thành “Đã liên kết”.</li></ol><p>Không nhận được thông báo? Kiểm tra kết nối, bỏ chặn bot, bật loại thông báo mong muốn và thử gửi thông báo thử.</p></article>
    <article className="surface telegram-preferences"><span className="eyebrow">TÙY CHỌN</span><h2>Loại thông báo</h2>{prefs && keys.map(key => <label className="settings-toggle" key={key}><input type="checkbox" checked={Boolean(prefs[key])} onChange={e => setPrefs({ ...prefs, [key]: e.target.checked })} /><span>{labels[key]}</span></label>)}<Button loading={busy === 'prefs'} disabled={!prefs} onClick={savePreferences}>Lưu tùy chọn</Button></article>
    {role === 'SYSTEM_ADMIN' && <article className="surface telegram-admin"><span className="eyebrow">INTEGRATIONS · TELEGRAM BOT</span><h2>Bot HAU QM</h2><p>Trạng thái: {admin?.configured ? 'Đã cấu hình' : 'Chưa cấu hình'} · Webhook: {admin?.webhookStatus || '—'}</p><Input label="Bot username" value={username} onChange={e => setUsername(e.target.value)} placeholder="@hau_qm_bot" /><Input label="Token" type="password" value={token} onChange={e => setToken(e.target.value)} placeholder={admin?.configured ? 'Đã cấu hình · nhập mới để thay đổi' : 'Nhập token mới'} /><small>Token chỉ gửi khi lưu, không bao giờ trả về trình duyệt. Để trống để giữ token hiện tại.</small><div className="settings-actions"><Button loading={busy === 'admin'} disabled={!username.trim()} onClick={saveAdmin}>Lưu cấu hình bot</Button><Button variant="secondary" loading={busy === 'admin-test'} onClick={testAdmin}>Kiểm tra kết nối</Button></div></article>}
  </div></section>
}
