package com.notificationservice.infrastructure.persistence.repository;
import com.notificationservice.infrastructure.persistence.entity.SupportConversationEntity; import com.notificationservice.domain.model.SupportStatus; import org.springframework.data.domain.*; import org.springframework.data.jpa.repository.JpaRepository; import java.util.*;
public interface SupportConversationRepository extends JpaRepository<SupportConversationEntity,UUID>{
 @org.springframework.data.jpa.repository.Query("select c from SupportConversationEntity c where ((c.createdByUserId=:a and c.assignedAdminId=:b) or (c.createdByUserId=:b and c.assignedAdminId=:a))")
 java.util.Optional<SupportConversationEntity> findDirect(@org.springframework.data.repository.query.Param("a") UUID a,@org.springframework.data.repository.query.Param("b") UUID b);
 @org.springframework.data.jpa.repository.Query("select c from SupportConversationEntity c where c.createdByUserId=:id and c.assignedAdminId is not null and c.deletedAtCreator is null order by c.lastMessageAt desc") Page<SupportConversationEntity> findMine(@org.springframework.data.repository.query.Param("id") UUID id,Pageable p);
 @org.springframework.data.jpa.repository.Query("select c from SupportConversationEntity c where c.assignedAdminId=:id and c.deletedAtAdmin is null order by c.lastMessageAt desc") Page<SupportConversationEntity> findAssigned(@org.springframework.data.repository.query.Param("id") UUID id,Pageable p);
 Page<SupportConversationEntity> findByCreatedByUserIdOrderByLastMessageAtDesc(UUID id,Pageable p); Page<SupportConversationEntity> findByAssignedAdminIdOrderByLastMessageAtDesc(UUID id,Pageable p); Page<SupportConversationEntity> findByFacultyIdOrderByLastMessageAtDesc(String facultyId,Pageable p); Page<SupportConversationEntity> findAllByOrderByLastMessageAtDesc(Pageable p); Page<SupportConversationEntity> findByStatusOrderByLastMessageAtDesc(SupportStatus s,Pageable p);
}
