const COMMON={
  NETWORK_ERROR:'Không thể kết nối tới máy chủ. Vui lòng thử lại.',SESSION_EXPIRED:'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',FORBIDDEN:'Bạn không có quyền thực hiện thao tác này.',VALIDATION_ERROR:'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại thông tin.',INVALID_REQUEST:'Yêu cầu không hợp lệ.',RESOURCE_NOT_FOUND:'Không tìm thấy dữ liệu yêu cầu.',INTERNAL_ERROR:'Hệ thống đang gặp sự cố. Vui lòng thử lại sau.',CONFLICT:'Dữ liệu đã thay đổi hoặc bị trùng. Vui lòng tải lại.',HTTP_400:'Yêu cầu không hợp lệ.',HTTP_401:'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',HTTP_403:'Bạn không có quyền thực hiện thao tác này.',HTTP_404:'Không tìm thấy dữ liệu yêu cầu.',HTTP_409:'Dữ liệu đã thay đổi hoặc bị trùng. Vui lòng tải lại.',HTTP_413:'Dữ liệu gửi lên vượt quá giới hạn cho phép.',HTTP_500:'Hệ thống đang gặp sự cố. Vui lòng thử lại sau.'}
const AUTH={INVALID_CREDENTIALS:'Mã giảng viên hoặc mật khẩu không chính xác.',ACCOUNT_PENDING:'Tài khoản đang chờ quản trị viên xác nhận.',ACCOUNT_PENDING_APPROVAL:'Tài khoản đang chờ quản trị viên xác nhận.',ACCOUNT_REJECTED:'Đăng ký tài khoản đã bị từ chối. Vui lòng liên hệ quản trị viên.',ACCOUNT_LOCKED:'Tài khoản đã bị khóa. Vui lòng liên hệ quản trị viên.',ACCOUNT_NOT_ACTIVE:'Tài khoản chưa được kích hoạt.',INVALID_REFRESH_TOKEN:'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',INVALID_OTP:'Mã OTP không chính xác hoặc đã hết hạn.',OTP_INVALID:'Mã OTP không chính xác hoặc đã hết hạn.',OTP_EXPIRED:'Mã OTP đã hết hạn. Vui lòng yêu cầu mã mới.',INVALID_RESET_AUTHORIZATION:'Phiên đặt lại mật khẩu không hợp lệ. Vui lòng xác minh lại OTP.',LECTURER_CODE_ALREADY_EXISTS:'Mã giảng viên đã tồn tại.'}
const USER={USER_NOT_FOUND:'Không tìm thấy người dùng.',USER_ALREADY_EXISTS:'Thông tin người dùng đã tồn tại.',INVALID_USER_PROFILE:'Thông tin hồ sơ chưa hợp lệ.',INVALID_STATUS_TRANSITION:'Trạng thái tài khoản không thể chuyển theo thao tác này.'}
const QUESTION={QUESTION_NOT_FOUND:'Không tìm thấy câu hỏi.',SUBJECT_NOT_FOUND:'Không tìm thấy môn học.',CHAPTER_NOT_FOUND:'Không tìm thấy chương.',TOPIC_NOT_FOUND:'Không tìm thấy chủ đề.',INVALID_STATUS_TRANSITION:'Trạng thái câu hỏi không thể chuyển theo thao tác này.',QUESTION_ALREADY_EXISTS:'Câu hỏi đã tồn tại.'}
const AI={AI_JOB_NOT_FOUND:'Không tìm thấy tác vụ AI.',INVALID_JOB_TRANSITION:'Tác vụ AI chưa ở trạng thái phù hợp để thực hiện thao tác này.',INVALID_AI_OUTPUT:'AI trả về kết quả không hợp lệ. Vui lòng thử lại.',PROVIDER_FAILURE:'Nhà cung cấp AI tạm thời không xử lý được yêu cầu.',PROVIDER_RETRY_EXHAUSTED:'Tác vụ AI đã hết số lần thử. Vui lòng tạo lại tác vụ.',UNSUPPORTED_DOCUMENT:'Loại tài liệu hoặc kích thước tài liệu chưa được hỗ trợ.'}
const EXAM={EXAM_NOT_FOUND:'Không tìm thấy bộ đề.',EXAM_MATRIX_NOT_FOUND:'Không tìm thấy ma trận đề.',EXAM_TEMPLATE_NOT_FOUND:'Không tìm thấy mẫu đề.',INSUFFICIENT_APPROVED_QUESTIONS:'Không đủ câu hỏi đã duyệt để sinh bộ đề.',INVALID_EXAM_MATRIX:'Ma trận đề chưa hợp lệ.',INVALID_MATRIX:'Ma trận đề chưa hợp lệ.'}
const NOTIFICATION={NOTIFICATION_NOT_FOUND:'Không tìm thấy thông báo.',INVALID_NOTIFICATION:'Thông tin thông báo chưa hợp lệ.'}
export const errorRegistry={COMMON,AUTH,USER,QUESTION,AI,EXAM,NOTIFICATION}
const messages=Object.values(errorRegistry).reduce((all,group)=>({...all,...group}),{})
export function getErrorMessage(error,fallback='Không thể hoàn tất yêu cầu. Vui lòng thử lại.'){const code=error?.code||`HTTP_${error?.status}`;return messages[code]||fallback}
